### ISSUE TITLE
Pegasus not releasing controller 

### ISSUE THREAD

**Issue by OdessaVBiss** [mmatyas/pegasus-frontend#1002]
When launching games from Pegasus Pegasus does not release the controller to the launched game.  
If I launch RetroArch, I have to reconnect the controller to get the controller to work in RetroArch.
If I launch Ryujinx or a non steam lutris games the controller will not work at all as long as Pegasus is open. Ryujinx for example does not show any controller connected if Pegasus is open.
### System info

Arch Linux. 
Xbox Wireless Controller connected with a USB cable as the computer does not have a BT card.

### Pegasus version

Current version

**Comment by mmatyas** [comment]
Hm are you sure this isn't a system configuration issue, outside of Pegasus? Just like mouse and keyboard, gamepads are usually not locked to a single application either, and Pegasus shouldn't be able to block other apps from seeing connected hardware to your system.

**Comment by OdessaVBiss** [comment]
I don't believe so. 

If I have RetroArch open and then open Ryujinx the controller still shows up in settings input.  The settings for Ryujinx just show the keyboard as long as Pegasus is open. The moment I close Pegasus and open up the input settings in Ryujinx the controller appears.

If I have RetroArch open and then launch a game through Lutris the controller works perfectly fine in the launched game.

Pegasus prevents the controller from showing up in RetroArch, Ryujinx, emulator station, lutris games, and steam.

**Comment by mmatyas** [comment]
I've made some changes to the gamepad handling, could you try the latest version (`alpha16-35-gcf2e2d1c`)?

**Comment by OdessaVBiss** [comment]
This seems to have fix the issue with the controller not showing up in other apps. I still have the issue where I have to reconnect the controller in between apps but that may be an issue with the controller itself. I'm going to install a Bluetooth card into this computer and seeing if it's persistent over Bluetooth.

**Comment by OdessaVBiss** [comment]
I tried four different linux drivers for this controller on Bluetooth and none of them work properly. The X button doesn't work the shoulder buttons doesn't work. All the buttons work correctly when I disconnect from Bluetooth and use USB. I think this is the best I'm going to get. I just have to get used to unplugging and replug in the controller, but at least The controller shows up in the other emulators which was the main problem.

**Comment by mmatyas** [comment]
I suppose this can be closed.
