### ISSUE TITLE
Show multiple images in metadata?

### ISSUE THREAD

**Issue by DeltaGemini** [mmatyas/pegasus-frontend#1010]
I know Pegasus themes can show a single image for screenshot, wheel, logo etc, but can I have screenshot show multiple images? Ideally, show any image that begins with the game name, something like "gamename_*.jpg"/png?

**Comment by mmatyas** [comment]
Hi! Yes, Pegasus itself supports multiple images for all asset types; for example, if you use [media dirs](https://pegasus-frontend.org/docs/user-guide/meta-assets/#the-media-directory) all files starting with `screenshot` will be detected. What is on the screen however always depends on the theme.

**Comment by DeltaGemini** [comment]
Thank you, that's something I can look into. If you do choose screenshot in the metadata file, can you leave the path open ended at a directory, or does it need a single image declared?

**Comment by mmatyas** [comment]
Each path should point directly to files, either as an absolute path, or a path relative to the metadata file. For example:
```
assets.screenshots:
    MyGame/screenshot1.png
    MyGame/screenshot2.png
    MyGame/screenshot3.png
```

**Comment by JHK80** [comment]
Hi, i tried to follow the instructions on the official website but i can't understand how to add other media in addition to the basic ones (box2d, screenshot, wheel, fanart, video)

For example, all of my collections have Game Cartridge images in a folder called "Cartridge" at the following path:
C:\GAMES\ROMS\"console name"\media\Cartridge

How can I display it in the theme like the other basic ones for all consoles?
Do I need to add a path to the pegasus settings.txt file?

Thanks for your help

**Comment by mmatyas** [comment]
Hi! The assets displayed depend on the theme; the default one uses `cartridge` only when there's nothing else available. You can find more themes at https://pegasus-frontend.org/tools/themes/.

**Comment by JHK80** [comment]
Thanks for the quick response!
I'm using the Minimis theme which has the following assets: box2d, screenshot, wheel, fanart, video

So can I add new assets by modifying only the theme code with Qt Creator without modifying the Pegasus files? 
I would like to have some more "folders" like cartride, box2dBack, Box3d
Thanks again
