### ISSUE TITLE
Ability to track playtime

### ISSUE THREAD

**Issue by Deregon** [mmatyas/pegasus-frontend#1011]
It would be really nice to have playtime tracked per game, much like Playnite and EmulationStation.

**Comment by mmatyas** [comment]
Hi, this is an already supported feature. Have you run into any issues?

**Comment by Deregon** [comment]
My bad, I was trying a custom theme and that's why it did not show up.

**Comment by Deregon** [comment]
In fact, even the default theme does not show the amount of time played. How do I view the tracked playtimes ?

**Comment by mmatyas** [comment]
You can see it by opening the game's details with the I key. See https://pegasus-frontend.org/docs/user-guide/controls/ for gamepad controls.

**Comment by Deregon** [comment]
Then again, my bad, I did not know of this option. Thanks !

**Comment by JHK80** [comment]
I copied the pegasus folder and the Roms folder to the external hard disk and the playing times were reset, why? Is there a way to get them back? Thanks

**Comment by mmatyas** [comment]
At the moment the playtimes use absolute paths, this is tracked at https://github.com/mmatyas/pegasus-frontend/issues/1097.
