### ISSUE TITLE
help me,J2ME

### ISSUE THREAD

**Issue by Chenwq297** [mmatyas/pegasus-frontend#1013]
[J2ME_Loader-1.7.5-open-release.zip](https://github.com/mmatyas/pegasus-frontend/files/9302633/J2ME_Loader-1.7.5-open-release.zip)
Help create a [metadata.Pegasus.TXT]，
[metadata.pegasus.txt](https://github.com/mmatyas/pegasus-frontend/files/9302660/metadata.pegasus.txt)

**Comment by mmatyas** [comment]
Hi! I'm not familiar with J2ME, but maybe someone in our community could help. Feel free to visit our Discord channel!

**Comment by mmatyas** [comment]
I suppose this can be closed, as it's not something we can fix on the code side.
