### ISSUE TITLE
Cloning systems like Dig Frontend

### ISSUE THREAD

**Issue by chelnov5** [mmatyas/pegasus-frontend#1016]
Hi, maybe there is a way but I can't seem to find it. I like to separate my systems according to region like nes into nes and Famicom, msx into msx and msx2 etc. I have separate folders and separate metadata text files but pegasus merges them under same title like nes and msx and also genesis and mega drive into one system. In Dig Frontend there is an option of cloning system, is there any feature like that in pegasus and if not kindly make that option.

**Comment by mmatyas** [comment]
Hi! Pegasus merges collections when they have the same name in the metadata file. If you set a different name for your collections, then the games will belong to different collections as well.

**Comment by mmatyas** [comment]
I suppose this can be closed.
