### ISSUE TITLE
Support for Colem deluxe, mastergear and fmsx

### ISSUE THREAD

**Issue by chelnov5** [mmatyas/pegasus-frontend#1017]
There is a metadata for Colem, but sadly even now it doesn't load roms and neither fmsx and mastergear. Other Frontend also had problem with these emulators but now are all fixed except for Pegasus. Please make them work in next update kindly

**Comment by mmatyas** [comment]
I'm afraid I don't have any control over _how_ the games launch. Pegasus simply runs the command you set in the metadata file.; if the command is wrong, I can't do anything about it. Instead, you can try contacting the emulator developers, and ask if they can help with the command (if they support running games from the command line).

**Comment by chelnov5** [comment]
Ok Man I figured it out and now these emulator will work with peagsus
Line -d "{file.path}" should be changed to -d "{file.uri}" and emulators will work
.............................................................................................................................................
collection: ColecoVision
shortname: colecovision
extensions: bin, col, cv, rom
launch: am start
  --user 0
  -n com.fms.colem.deluxe/com.fms.emulib.MainActivity
  -a android.intent.action.VIEW
  -d "{file.uri}"
  --activity-clear-task
  --activity-clear-top
  --activity-no-history
...............................................................................................................................................

This is correct Metadata Entry and kindly update it on your website. I haven't checked it on fmsx Deuluxe or MasterGear but I think it will work.

Also few Metadata that wasn't on you site but I made them myself in case someone are usine them

REAL3DOPLAYER  (Note this emulator doesn't load cue file but work with bin, img and iso)
......................................................................................................................................
collection: 3DO
shortname: 3do
extensions: bin, iso, img
launch: am start
  -n ru.vastness.altmer.real3doplayer/.MainActivity
  -a android.intent.action.VIEW
  -e cd "{file.path}"
  --activity-clear-task
  --activity-clear-top
  --activity-no-history
.....................................................................................................................................

IRATAJAGUAR
...................................................................................................................................
collection: Atari Jaguar
shortname: Jaguar
extensions: abs, bin, cof, j64, jag, prg, rom, zip
launch: am start
  -n ru.vastness.altmer.iratajaguar/.MainActivity
  -a android.intent.action.VIEW
  -e rom "{file.path}"
  --activity-clear-task
  --activity-clear-top
  --activity-no-history
....................................................................................................................................


Hope this will help

**Comment by mmatyas** [comment]
Thanks! I've added them to the list.
