### ISSUE TITLE
Add 64bit/aarch64 version to pi4 ?

### ISSUE THREAD

**Issue by darksaviorx** [mmatyas/pegasus-frontend#1021]
On my 64bit pi4 setup I need to manually install the 32bit packages required by Pegasus. It would save me a lot of time if there was a 64bit build. Thanks.

**Comment by mmatyas** [comment]
If there would be a 64-bit version, you'd still need to install the dependencies, just the 64-bit versions of them.

Or, if by automatic installing you mean RetroPie, then perhaps the install script there could be made smarter, so it installs the 32-bit dependencies for you.

**Comment by darksaviorx** [comment]
A 64bit version would (probably?) use the listed dependencies from the Retropie Pegasus installer. For 32bit, I need to install the armhf architecture first and then install the same dependencies with :armhf at the end. Pegasus is the only 32bit app I use so I thought it was worth asking.

**Comment by mmatyas** [comment]
The build log seems to be fine, if Pegasus starts up, the compilation is OK. The grey screen sounds like a rendering or Qt related issue, eg. problem with a particular QML element. Take a look at the Pegasus log or the console output for any issues.

I've also sent a pull request for the RetroPie 32-bit dependencies.

**Comment by mmatyas** [comment]
I _think_ this can be closed in favor of https://github.com/RetroPie/RetroPie-Setup/pull/3586 which discusses the dependencies, and https://github.com/RetroPie/RetroPie-Setup/pull/3881 which provides a script for on-device builds.
