### ISSUE TITLE
collection option for adding rules to titles

### ISSUE THREAD

**Issue by silentnoodlemaster** [mmatyas/pegasus-frontend#1023]
Would love an option where i could use similar methods that I could with the `launch` options but for titles, 

if metadata.txt would look like:
```
collection: cool games
regex: start.*\.sh
title: "{file.dir}"
``` 

and the library would be:
```
<Library>
    <Game Name> 
        start.sh
    <Another Game>
        start.sh
```

then I would not need to add metadata for each game separately

**Comment by mmatyas** [comment]
Hi! A single game may consist of multiple files, which may be in separate directories, so I'm afraid the metadata file wouldn't work like this.

**Comment by silentnoodlemaster** [comment]
Thanks for clarifying, I suppose my laziness has to be defeated in some other way
