### ISSUE TITLE
Pegasus crashes when navigating to some Steam games

### ISSUE THREAD

**Issue by Tvangeste** [mmatyas/pegasus-frontend#1028]
### The issue

In Pegasus, when I navigate to a couple of auto-detected Steam games, Pegasus crashes.
The two games that exhibit this problem are:
* SteamWorld Dig 2
* Deathspank

Just to clarify, I don't launch the games, I just navigate to them. Even when I pass though to some other games in the grid, as soon as I  select any of those two games, Pegasus dies.

### System info

Windows 10 Pro 22H2 (OS Build 19045.2193)

### Pegasus version

Freshly downloaded alpha16-44-g8119fcec, 2022-10-14

### Pegasus log

The log is attached
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/9979123/lastrun.log)

**Comment by mmatyas** [comment]
Hi! According to the log, you are missing some video codecs:
```
DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()
```
You can find more info about it here: https://pegasus-frontend.org/docs/user-guide/platform-windows/#multimedia-support

**Comment by Tvangeste** [comment]
Indeed, installing additional kodecs fixed the issue, thanks,
