### ISSUE TITLE
Videos don't play on Steam Deck

### ISSUE THREAD

**Issue by YamMario** [mmatyas/pegasus-frontend#1029]
### The issue

I've downloaded MP4s of videos I'd like Pegasus to play when selecting games, they play fine on Windows but don't on Steam Deck (Arch Linux I guess). The MP4s were downloaded from Youtube using DLG and are 24 FPS and have a total bitrate of 1776kbps.

### System info

Steam Deck, Steam OS/Arch Linux

### Pegasus version

pegasus-fe_alpha16-42-g996720eb

I changed my setup after it didn't work so I don't have the log file on hand, sorry.

**Comment by mmatyas** [comment]
Hi! Pegasus uses the system's built-in video playback support for playing videos, and the system can only play video formats for which it has the necessary video codecs. It is possible that the videos you downloaded require a video codec that's not available out of the box on the Steam deck.

I'm not familiar with how the Deck works, but here are the Arch packages that provide the video codecs: https://wiki.archlinux.org/title/GStreamer#Installation

**Comment by YamMario** [comment]
All right, after installing gstream, gst-libnav, gst-plugins-base, and gst-plugins-good, they started playing!
A bit annoying that you have to install extra stuff to get it to work (I had MPV installed as my video player on the system but I guess it doesn't install any system wide codecs), but it does work now.

**Comment by mmatyas** [comment]
Great!

**Comment by YamMario** [comment]
Hello again,
It seems like Steam's own updates to the OS overwrite the installation of the gst-plugins, so I have to reinstall every time they update. Is there any way around this?

**Comment by mmatyas** [comment]
I'm afraid I'm not familiar enough with the Steam Deck to know a fix for that. I think you might have more luck with some Steam Deck related forums and communities.
