### ISSUE TITLE
[Enhancement] Add Scoop installation instructions to the downloads section of the pegasus website.

### ISSUE THREAD

**Issue by Zliced13** [mmatyas/pegasus-frontend#1031]
Hello @mmatyas, 

I am sorry that I didn't tell you that I added your program to Scoop right away, I was pre-occupied with other personal responsibilities at the time. Now that I have more time, I will tell you what I did.

A few months I got **pegasus** added to [Scoop](https://scoop.sh/#/apps?s=2&d=1&o=true&p=1&q=pegasus).  If you don't know what Scoop is, it's a package manager for Windows, maintained by the Scoop community.

Scoop can be installed into your Windows OS by following the instructions [here](https://scoop.sh/). After Scoop is installed into your system, you can install **pegasus** with the following commands.

_First Command_
```
scoop bucket add games
```
_Second Command_
```
scoop install pegasus
```
#

I suggest adding these instructions to this part of your website:
![(firefox)V380S0_12-18-2022](https://user-images.githubusercontent.com/101912712/208322279-62d0b5ce-b1b5-4598-89b3-10789c1eb64a.jpg)

**Comment by mmatyas** [comment]
Interesting! I wasn't familiar with Scoop, but I can mention it on the main page.

**Comment by mmatyas** [comment]
Ok! Added to the Windows downloads section.
