### ISSUE TITLE
cross platform command support

### ISSUE THREAD

**Issue by xrain0610** [mmatyas/pegasus-frontend#1035]
I use nas manage games, and run it on linux/mac/windows , can't use same metadata for now , can you add a platform command support one meta for all platform?

**Comment by mmatyas** [comment]
Hi, at the moment Pegasus supports exactly one launch command for each game. However this command can be anything, so when you need platform- or device-specific commands, that is usually handled by external programs.

A good example is eg. RetroPie: it is available on several platforms and supports many emulators, but all of that is managed by one tool, the `runcommand` script. Similarly, if you use the same data on multiple devices, but the emulators have different location, or require different command line parameters, you will need to write an external script that knows about such differences.

**Comment by xrain0610** [comment]
thanks.
