### ISSUE TITLE
Feature Request: Kiosk Mode

### ISSUE THREAD

**Issue by Danhanado** [mmatyas/pegasus-frontend#1043]
A kiosk mode would be nice, ideally it would not show the loading screen on launch and it would disable the Pegasus escape menu, making it only closeable through alt+f4.
Perhaps through launch parameters?

**Comment by mmatyas** [comment]
Hi, there's already a kiosk mode, which you can use by the `--kiosk` command line argument.

**Comment by Danhanado** [comment]
Oh wow, I should've checked, cheers
