### ISSUE TITLE
Module Request: QTGamepad

### ISSUE THREAD

**Issue by Danhanado** [mmatyas/pegasus-frontend#1045]
Just thought I'd add this as an issue.
Would allow for more theme freedom and intuitive control for alternate peripherals such as racing wheels

**Comment by mmatyas** [comment]
Hi, Qt Gamepad is no longer maintained by Qt, so it's been deprecated here as well. It also supports far less devices than we do currently. If you'd like to, you can still build Pegasus from source, and use Qt Gamepad; you can find more details in the build documentation.
