### ISSUE TITLE
Nintaco Emulator Force Close

### ISSUE THREAD

**Issue by gisatendo** [mmatyas/pegasus-frontend#1047]
Hello, first, sorry if my english is so bad,

I want to ask, how to launch emulator with .jar extension? is it possible?

Because i want to launch emulator named "Nintaco" to play Miracle Piano & Stack-Up for NES,
I choose Nintaco because this emulator has 99% complete peripheral for NES System, (but in other game i choose Mesen :D)

But when i want to launch Nintaco with Pegasus, the program is closed,

This is my setup for Nintaco,

collection: Nintendo Entertainment System
extension: nes, fds
launch: D:\Emulators\Nintaco\Nintaco.jar {file.path}

I also to try change {file.path} with {file.name}, {file.basename}, and {file.dir} but the result is similar.

Thanks

**Comment by mmatyas** [comment]
Hi! JAR files are launched by the Java Runtime, like this: `java -jar path\to\jarfile.jar`. In this case, the command is probably `launch: java -jar D:\Emulators\Nintaco\Nintaco.jar {file.path}` (assuming that Java is properly installed).

If, for some reason Pegasus crashes, please follow the [issue template](https://github.com/mmatyas/pegasus-frontend/blob/master/.github/ISSUE_TEMPLATE/bug.md), and share some more details and the log file.

**Comment by gisatendo** [comment]
> Hi! JAR files are launched by the Java Runtime, like this: `java -jar path\to\jarfile.jar`. In this case, the command is probably `launch: java -jar D:\Emulators\Nintaco\Nintaco.jar {file.path}` (assuming that Java is properly installed).
> 
> If, for some reason Pegasus crashes, please follow the [issue template](https://github.com/mmatyas/pegasus-frontend/blob/master/.github/ISSUE_TEMPLATE/bug.md), and share some more details and the log file.

That is work! Thank You Very Much mmatyas! :D
