### ISSUE TITLE
Can't run pegasus on Raspberry Pi 3 with Raspberry Pi OS (debian bullseye) due to libbrcmOpenVG.so

### ISSUE THREAD

**Issue by michaelbutler** [mmatyas/pegasus-frontend#1049]
### The issue

When I try to run ./pegasus-fe, I get this error:

```
pi@raspberrypi:~/src/pegasus $ ./pegasus-fe 
./pegasus-fe: error while loading shared libraries: libbrcmOpenVG.so: cannot open shared object file: No such file or directory
```

There isn't much info on Google about this error, which is why I'm posting this here. 

### System info

Raspberry Pi 3
OS: Rasbian GNU/Linux 11 (bullseye) AKA Raspberry Pi OS
1 GB RAM
Basically a fresh install.

### Pegasus version

I tried both of:

Stable release for Pi 3: [alpha16-42-g996720eb (2022-08-02)](https://github.com/mmatyas/pegasus-frontend/releases/download/weekly_2022w30/pegasus-fe_alpha16-42-g996720eb_rpi3-static.zip)
    Latest version for Pi 3: [alpha16-47-gb0366487 (2023-02-28)](https://github.com/mmatyas/pegasus-frontend/releases/download/continuous/pegasus-fe_alpha16-47-gb0366487_rpi3-static.zip)

and got the same issue.

### Pegasus log

Log doesn't exist since the executable can't load the shared library.

If possible, please attach the file to this bug report.

**Comment by mmatyas** [comment]
Hi, the `libbrcm*` libraries are the Broadcom video drivers: if they are not preinstalled, they should come with one of firmware packages, as far as I know. I'm not sure which one though, perhaps `dpkg -S libbrcmOpenVG.so` would tell that? It is also possible that there were some driver changes yet again in Raspbian.

**Comment by michaelbutler** [comment]
I gave up on this so I'll close the issue. I'm now having a problem running Pegasus on a basically stock PopOS! 22.04 desktop PC but I'll open another issue for that.
