### ISSUE TITLE
Unable to open the DraStic games

### ISSUE THREAD

**Issue by fokhei** [mmatyas/pegasus-frontend#1051]
### The issue

Unable to open the DraStic games (DraStic is launched, but shows the error message "unable to open game from content://org.pegasus_frontend.android.files/ext/roms/xxxx....."). I using the config from pegasus config generator:

```
collection: Nintendo DS
shortname: nds
extensions: bin, dsi, nds
launch: am start
  -n com.dsemu.drastic/.DraSticActivity
  -a android.intent.action.VIEW
  -d "{file.uri}"
  --activity-clear-task
  --activity-clear-top
  --activity-no-history
```

I also use the Daijisho frontend and compare its amStartArguments, it is almost the same but Daijisho works fine. 
https://github.com/TapiocaFox/Daijishou/blob/main/platforms/NintendoDS.json

So I guess it is a bug of pegasus frontend

### System info

Android 12 on Galaxy Note 10+
DraStic r2.6.0.4a

### Pegasus version

pegasus-fe_alpha16-42-g996720eb_android.apk

### Pegasus log

(the log is empty)

**Comment by mmatyas** [comment]
Hi, unfortunately after the launch command runs, and the emulator launches, there's not much Pegasus can do about how the emulator behaves. "Unable to open" issues usually indicate that the app expects the file path in a different format (`file.uri` or `file.path` or `file.documenturi`), you could try to experiment with that first. The config generator uses launch commands submitted by our community members, so if it doesn't work out, you might also find some more help on Discord too.
