### ISSUE TITLE
scanning from a selected file

### ISSUE THREAD

**Issue by ninonook1** [mmatyas/pegasus-frontend#1057]
i have alot of games (roms included) that are in an external drive, and i have noticed that your application wont read those files, is there a way to where i could manually scan a file, if not, could that be added in

**Comment by mmatyas** [comment]
Hi! You can add metadata files manually from the Settings menu. If you are not familiar with metadata files, please take a look in the [documentation](https://pegasus-frontend.org/docs/user-guide/adding-games/). If you tried to add a metadata file, but it didn't work, or did not detect all the files please report this as a bug, and follow the instructions described there.
