### ISSUE TITLE
Does this let you install window games?

### ISSUE THREAD

**Issue by DOOMMARINE117** [mmatyas/pegasus-frontend#1064]
is this just for retro games? or can it be used to install dos games and pc games in general?

**Comment by mmatyas** [comment]
Hi! It can be used for all kinds of games, or even non-games like movies or other applications too.

**Comment by DOOMMARINE117** [comment]
> Hi! It can be used for all kinds of games, or even non-games like movies or other applications too.

sweet, awesome. thanks.
