### ISSUE TITLE
macOS reports Pegasus is "not responding" after launching a game.

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [mmatyas/pegasus-frontend#1066]
### The issue

Hi-hi! This is the dude who you helped out with his really silly problem of wanting to modify the macOS icon permanently. Thank you so-so much, again, for creating the most beautiful launcher ever. I've gone from [games](https://skyetheguy.com/pegasuscollectionjul312023A.png) to even [launching eBooks](https://skyetheguy.com/pegasuscollectionjul312023B.png) in this, which really brings back the magic of physically having a book in the digital age.

This probably isn't even a bug but just some kind of inner working of, like, Qt or something, but I was wondering about why, after launching a game, after a few seconds, Pegasus reports as "[not responding](https://skyetheguy.com/youwhoismovingnow.png)"? Obviously, the moment I quit out of the game I'm playing, then Pegasus stops flashing that error and all and "responds", but it's still not a nice thing to see.

I've noticed that other launchers on macOS have the same exact problem, like Playnite. Two launchers that don't do this are GOG Galaxy or Steam, but I definitely don't want to use either of those, hahaha. I don't know if this alert doesn't suck up a lot of energy that shouldn't be being used, but playing a game and then leaving Pegasus spinning the loading-beach-ball-of-death the whole time just doesn't seem healthy, in a way. All the best!

### System info

macOS Monterey 12.5

### Pegasus version

Tried on the latest alpha version, alpha16-51-g6421d7a7 (2023-05-21), didn't fix the problem.

### Pegasus log

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/12224675/lastrun.log)

If possible, please attach the file to this bug report.

**Comment by mmatyas** [comment]
Hi! Happy to hear Pegasus worked out well for you! When Pegasus launches a game, it tries to minimize its usage of system resources (like memory), and it doesn't do anything until you return from the game. In that sense, it's technically true that it's not responding: it is waiting for the launched game to end. Contrary to that, Steam and GOG keep running alongside the games, mainly to use their storefront and social features.

Now I'm not that familiar with Mac, what side effects do you run into? Where you see this "not responding" message or alert?

**Comment by HomeStarRunnerTron** [comment]
Oh, thank you for the explanation! Maybe it's not a problem at all. I just get paranoid that, because it says "not responding" (this is in the Force Quit Applications menu or Activity Monitor) that it's actually taking up a lot of memory. But if you're telling me that it's taking up even LESS memory, I totally believe you, that really quells my fears that I need to force-quit it when I leave Pegasus open too long waiting for the game to close.

**Comment by HomeStarRunnerTron** [comment]
Man, that's a major weight off of my mind, I'm so glad I asked even though it turned out to be a non-problem. Just did a little half-hour test and checked in Activity Monitor, and [these are the sorts of numbers I'm getting](https://www.skyetheguy.com/thatisnotabignumberthatisasmallnumber.png)! Very-extremely itty-bitty. Gonna call this one closed, and hope this reaches someone else who's worrywarting about it.
