### ISSUE TITLE
Scrolling on macOS Trackpad causes glitches.

### ISSUE THREAD

**Issue by HomeStarRunnerTron** [mmatyas/pegasus-frontend#1067]
### The issue

I have a good feeling that this is going to be the last negligible oddity I'll be posting for a while-- thank you so much for your patience and kindness-- this community's really wonderful. :  )

Pegasus ree-lee doesn't like when I try to scroll a list of games. At least when I'm using my MacBook's built-in trackpad. I found out it functions like a dream if I just plug in a mouse! Here's video of my demonstration of both methods: https://www.youtube.com/watch?v=G6bDcU4d-dE

Obviously, scrolling is scrolling, and really, it's a secondary feature for most people-- but I found it really fun to scroll-- but it doesn't always getchya where you need to be when your scrolling keeps sending you back half a grid row. I bet it's just Qt responding badly to the hardware-- surely there's no problems with scrolling on ANY Windows machine-- but I just thought I'd bring it up, in-case there's anyone else just talking about this for some other Qt-developed project! Enjoy the jitter!

### System info

macOS Monterey 12.5

### Pegasus version

Pegasus alpha16-44-g8119fcec-dirty (2022-10-14), but the same effect can be seen in the both the stable & latest releases, as of today.

### Pegasus log

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/12321479/lastrun.log)

**Comment by mmatyas** [comment]
Thanks for bringing this up, and thanks for the video, really helpful! This does sound like a Qt problem, and I _think_ I've found the issue in their bug tracker. I'll try updating the Qt version Pegasus uses.

**Comment by HomeStarRunnerTron** [comment]
Huge thank-you for looking into it-- my trackpad will truly be blessed by your care. :  D

**Comment by HomeStarRunnerTron** [comment]
WA & A HOO! That was INSANELY fast, and it completely fixes the scrolling problem! (The collections tab on Pegasus Grid still goes crazy, but that might just be a sensitivity issue that's being worsened by the fact I only have two collections-- which, no one who uses THAT would only have two collections. But yeah, no longer a Qt problem, for sure.)

As thanks, here's another demonstration video: https://www.youtube.com/watch?v=TZs0NDJMPdo All the best!

**Comment by mmatyas** [comment]
Haha, thanks for the follow up video, much appreciated!
