### ISSUE TITLE
Reloading the game cache automatically.

### ISSUE THREAD

**Issue by Midnite59** [mmatyas/pegasus-frontend#1075]
So I am making this console with Pegasus as a front end. I want to have it dynamically update when a cartridge is connected. How would I be able to do this if I can?

**Comment by mmatyas** [comment]
Hi! I assume you're making some custom controller chip or an USB device based solution. When you plug the cartridge into the device, your operating system probably generates some system event, which should be captured by Pegasus. You probably have to modify Pegasus' source code to listen to the system event your device generates, add the cartridge's drive to the list of game directories, and refresh the game list. I've never tried doing this, but these links seem to be useful: https://stackoverflow.com/questions/29414329/is-there-a-qt-solution-for-detecting-usb-events-insertion-and-removal

(Not sure if this is the kind of answer you were looking for.)

**Comment by Midnite59** [comment]
Guess I have to wait so someone PRs it for me. (Kinda dumb)

**Comment by Midnite59** [comment]
What I really wanted to do was find a bash command or such to reload the game cache with a script. I know you can make scripts for certain events, but I was wondering if there was a command, directory to delete, or some flag that would reload the games. I would love to know if there was a way to do it without modifying the source (Since I am dumb as heck)

**Comment by mmatyas** [comment]
Pegasus calls external scripts based on actions done _inside_ Pegasus, but it doesn't monitor external files or commands for changes. I think the closest you could do is to just restart Pegasus: If you can write a script that detects the connection/disconnection of the cartridge, then there you can quit Pegasus, modify its config file that stores the game directories (which is a plain text file), and then restart Pegasus.

**Comment by mmatyas** [comment]
I think I'll close this issue, as it sounds very specific to the device you're building, but the workaround mentioned above could be used.
