### ISSUE TITLE
Doesn't work on X11

### ISSUE THREAD

**Issue by YourFriendly14YearOldNerd** [mmatyas/pegasus-frontend#1076]
### The issue
Whenever I try to load Pegasus on LXDE or OpenBox, Pegasus returns an Error over and over.

How to reproduce:
Have a raspberry pi running Raspbian bullseye (Not Lite).
Download the raspberry pi version of Pegasus.
Make the bin executable.
Run pegasus-fe with a terminal emulator.

### System info

 Rasbian Bullseye on a Raspberry Pi 4 with 4GB RAM

### Pegasus version

Latest version as of posting issue.

### Pegasus log

Normal but all of a sudden.
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)
Could not queue DRM page flip (Permission Denied)

**Comment by YourFriendly13YearOldNerd** [comment]
The pi keeps throwing an error "Could not queue DRM page flip (Permission Denied)"
Doing the exact same steps on a normal amd64 debian distro throws no error.

**Comment by mmatyas** [comment]
This sounds like https://pegasus-frontend.org/docs/user-guide/platform-raspberry/#gpu-driver-notes

**Comment by YourFriendly14YearOldNerd** [comment]
I fixed it by compiling. Also today is my birthday :)
