### ISSUE TITLE
Add or optimize support for. pkg format Roms such as PS3 and WIIU.

### ISSUE THREAD

**Issue by wangjingshan2555** [mmatyas/pegasus-frontend#1078]
During the process of adding EBOOT.BIN file of PS3 game, many unnecessary BIN files will be imported. After adding WIIU game, running the game through Pegasus can only open CEMU, but not the game. I hope to simplify the operation of importing PS3 and WIIU games, just like the 13.3 version of launchbox.
![Uploading fcde5b54-e7f5-4173-9789-4e5599dea2dd.jpg…]()

**Comment by mmatyas** [comment]
Hi! Pegasus does not include any emulator or console specific information. It allows you to use _any_ emulators and _any_ kind of files, if you know how to launch them.

If you have issues with WiiU or PS3, you might wish to look into the documentation of the emulators. If you're using a larger package that includes Pegasus, you might wish to report the issue to the maintainers of that package.

**Comment by wangjingshan2555** [comment]
This is the latest version of Pegasus that I downloaded from your website. This is my metadata, file path and display effect.
![Uploading IMG_20231014_183412.jpg…]()

**Comment by wangjingshan2555** [comment]
This is the latest version of Pegasus that I downloaded from your website. This is my metadata, file path and display effect.
![Uploading IMG_20231014_183444.jpg…]()
![Uploading IMG_20231014_183412.jpg…]()
![Uploading IMG_20231014_183336_1.jpg…]()
![Uploading IMG_20231014_183323.jpg…]()

**Comment by wangjingshan2555** [comment]
![IMG_20231014_183412](https://github.com/mmatyas/pegasus-frontend/assets/132395729/305061e9-3dbd-41f4-88b0-fc501a350b5d)
![IMG_20231014_183444](https://github.com/mmatyas/pegasus-frontend/assets/132395729/4b257f03-1efa-47bf-94b4-a3cdbb6ab47b)
![IMG_20231014_183336_1](https://github.com/mmatyas/pegasus-frontend/assets/132395729/5bf42a89-d59e-4dd9-a723-7409819186ec)

This is the latest version of Pegasus that I downloaded from your website. This is my metadata, file path and display effect.

**Comment by wangjingshan2555** [comment]
I just added a game, and the result was as shown. I hope that future versions can be optimized.

**Comment by mmatyas** [comment]
For the launch command, I'm not familiar with the emulator, so I can't help with that. However, there are many people on Discord, who might help with that, so feel free to ask there.

For the many BIN files issue, I've answered on Discord:

> The `extensions:` line tells Pegasus to include all files with `.BIN` extension. If you don't want that, you don't need the `extensions:` line. It is enough to add the `EBOOT.BIN` path to the games as a `file:`.
