### ISSUE TITLE
Scraped images and description not showing

### ISSUE THREAD

**Issue by AndersHP84** [mmatyas/pegasus-frontend#108]
As stated by Fluffypillow at [RetroPie Forum](https://retropie.org.uk/forum/topic/9598/announcing-pegasus-frontend/336) I'm opening this issue, as I cannot get images and description to show, even though they do in ES. 

RetroPie v. 4.3, RPi Model 3B. Pegasus Alpha4-1 (2017-04-10)
Here's what I did:
[Where my Gameboy Advance gamelist is located](https://c1.staticflickr.com/5/4480/36828775293_0d954c65a4_n.jpg)
[Desc, image and marquee references in the Gamelist](https://c1.staticflickr.com/5/4443/23645492358_7919864678_b.jpg)
[Controlled that the filenames and location matches](https://c1.staticflickr.com/5/4454/37498053251_e7f8750089.jpg)
[How it looks in Pegasus](https://c1.staticflickr.com/5/4472/36828774393_116e36d215_z.jpg)
[How it looks in ES](https://c1.staticflickr.com/5/4455/36829011833_56395e1896.jpg)

I'm sorry if I'm wasting your time here, I just cannot seem to find out why it works in ES and not in Pegasus.

**Comment by mmatyas** [comment]
Looks like it works. Yay!
