### ISSUE TITLE
Allow Relative Path to Theme in settings.txt

### ISSUE THREAD

**Issue by doakey3** [mmatyas/pegasus-frontend#1082]
**Where**: `/config/settings.txt`
**What**:  general.theme should accept a relative path to a theme. E.g.: `general.theme: ./themes/MyTheme/`

I tried launching pegasus-fe.exe with the `--portable` flag and moving the "themes" and "config" folders to the same location as the executable. No luck.

**Comment by miguelguzmanr** [comment]
A quick observation: `general.theme` does accept a relative path e.g. `../themes/Flixnet/` (tested on `pegasus-fe_alpha16-67-g40b9b63a_win-mingw-static`), however, switching themes will use an absolute path, even in portable mode.

**Comment by doakey3** [comment]
So the path is relative to the settings.txt file. Thank you!
