### ISSUE TITLE
Unable to install latest Android APK

### ISSUE THREAD

**Issue by nicjansma** [mmatyas/pegasus-frontend#1086]
### The issue

It looks like at some point recently, the Android `versionCode` dropped from ~1914 to ~200.

If you already have Pegasus installed, this causes the _Latest version_ APK downloads on https://pegasus-frontend.org/#downloads to block from being installed:

```
11-07 21:56:33.150  1139  1247 W PackageManager: Downgrade detected: Update version code 200 is older than current 1914
11-07 21:56:33.151  1139  1247 E PackageInstallerSession: Failed to verify session 1111955993 [INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result]
```

In order to install the current _Latest version_ (~200), you need to uninstall the previous version.

Ultimately the uninstall and re-install of the _Latest version_ works fine, but I thought I would open this issue to (1) see if the `versionCode` drop was intentional and (2) let others that are having this issue find the solution easily if they're searching Github issues.

Feel free to close this issue if the `versionCode` drop was intentional.

### System info

Retroid Pocket 3+

### Pegasus version

I was previously on: `alpha16-44-g8119fcec 2022-10-14`.  Upgrading to current _Stable version_ is OK, but _Latest version_ fails.

I was trying to upgrade to [alpha16-67-g40b9b63a (2023-10-23)](https://github.com/mmatyas/pegasus-frontend/releases/download/continuous/pegasus-fe_alpha16-67-g40b9b63a_android.apk), which is listed as _Latest version_, and has a version code of `200`.

The stable release at [alpha16-51-g6421d7a7 (2023-08-16)](https://github.com/mmatyas/pegasus-frontend/releases/download/weekly_2023w20/pegasus-fe_alpha16-51-g6421d7a7_android.apk) has a version code of `1914`.

### Pegasus log

n/a

**Comment by mmatyas** [comment]
Thanks for the report! This was a configuration issue,and should be fixed now.
