### ISSUE TITLE
Entire screen blinks black for certain processes in fullscreen on Windows.

### ISSUE THREAD

**Issue by Danhanado** [mmatyas/pegasus-frontend#1093]
### The issue

Certain program processes cause the entire screen to blink black in fullscreen on Windows.
Occurs on the initial loading screen when scanning for games and occurs when first drawing with the Shapes QML type on a fresh reboot
This doesn't occur in windowed mode nor when using external software to force borderless windowed mode

People have reported issues with other QML applications in fullscreen so it seems to be a QML + Windows error.

I'm pretty certain adding a borderless option would remedy this

### System info

Tested on 2 different windows PCs, one with a RTX 2060 and one with a GTX 950

**Comment by Danhanado** [comment]
It seems that the Qt::FramelessWindowHint flag for the main window will achieve this, maybe there could be a launch command to change the fullscreen mode to this?

**Comment by mmatyas** [comment]
Hm considering that the issue started appearing after the QML Shapes addition, I wonder if the issue occurs with older versions?

**Comment by Danhanado** [comment]
It does, my other PC uses the build from when timeline was added

**Comment by Danhanado** [comment]
Oddly enough, now that my page that utilises shapes is more populated, it no longer flashes black. It does still happen on boot however. It would still be great to have a borderless fullscreen option however

**Comment by mmatyas** [comment]
I think I've managed to reproduce this on Windows, but unfortunately the Qt::FramelessWindowHint flag didn't help. Will need some further work.

**Comment by RBertoCases** [comment]
I don't think I'm experiencing this issue as of the latest version from 1/8/2024. At the very least, it's no longer forcing itself to stay on top. Which I very much appreciate so thank you!

**Comment by mmatyas** [comment]
I'll close this then, let me know if the issue still occurs.
