### ISSUE TITLE
Error: "" : "no element \"identity\"" when trying to run on EmuELEC on Amlogic s922x

### ISSUE THREAD

**Issue by shantigilbert** [mmatyas/pegasus-frontend#1101]
### The issue

I am not sure this is an issue with Pegasus or with my build of QT, but trying to make this run on EmuELEC using this:

```
export QML2_IMPORT_PATH=/emuelec/lib/plugins:/usr/plugins/
export QT_PLUGIN_PATH=/emuelec/lib/plugins:/usr/plugins/
export QT_QPA_EGLFS_DEPTH=32
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=135
export QT_QPA_EGLFS_PHYSICAL_WIDTH=217
export QT_QPA_FONTDIR=/usr/share/fonts/liberation
export QT_QPA_PLATFORM=eglfs
export QT_QPA_EGLFS_INTEGRATION=none
#export QT_DEBUG_PLUGINS=1
#export QML_IMPORT_TRACE=1
./pegasus-fe
``` 
Everything seems to work fine, I can see the splash screen but as soon as it finishes loading this error happens: 
```
[i] Game list post-processing took 1178ms
[i] 28712 games found
[w] Error: "" : "no element \"identity\""

(<unknown>:5277): GLib-GObject-CRITICAL **: 01:03:37.382: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(<unknown>:5277): GLib-GObject-CRITICAL **: 01:03:37.382: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
```

EDIT: Forgot to mention if I compile QT5 without qtgraphicaleffects `-skip qtgraphicaleffects ` then after it finishes loading pegasus tells me there was an error loading the theme, but I can navigate the settings and menus

### System info

aarch64 EmuELEC running on Odroid N2+ (Amlogic s922x) 

### Pegasus version

I compile it myself using latest commit c7103cd4d0e23a2af6ee570b57417379345cd0b6

### Pegasus log
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/13533651/lastrun.log)

**Comment by mmatyas** [comment]
Hm, I don't think the message comes from Pegasus' code, it seems as if the QML support is missing some compile-time features.

Yes, the default theme uses qtgraphicaleffects, so if it's missing, it will not load. Maybe the two issues are related?
