### ISSUE TITLE
Multiple gamepad profiles for UI

### ISSUE THREAD

**Issue by doakey3** [mmatyas/pegasus-frontend#1104]
Current behavior: 
Pegasus allows users to configure the UI for one gamepad. If a different gamepad is used, the configuration may not be consistent.

Desired behavior:
Allow users to customize gamepad input for multiple controllers, allowing consistent menu navigation across different similar controllers.

Note: 
I'm using the 8bitdo Pro 2 for my setup. Some games play better with the controller in "Switch" mode and other games play better with "Xbox" mode, so I'm switching the mode back and forth. Currently my solution is to launch a python script that checks which controller is in use and swap out /pegasus/config/settings.txt with a settings.txt that is specific for my current controller. This script then launches Pegasus-frontend. I would prefer a solution that was native to Pegasus-frontend.

**Comment by mmatyas** [comment]
Hi! If there are multiple controllers connected, you should be able to change which controller you're currently setting up on the gamepad screen. The settings for different gamepads are stored separately from each other, by the device's model identifier. Is this not the behavior you see?

**Comment by doakey3** [comment]
I see it now. The "Change controls..." menu sets the controls for all gamepads, but the "Change gamepad layout..." menu allows me to set the layout for specific controllers. In this way, I can make button behavior consistent for all my different types of gamepads. Thank you!
