### ISSUE TITLE
Pegasus not playing emulator videos on ui screen

### ISSUE THREAD

**Issue by Jafoolery** [mmatyas/pegasus-frontend#1108]
Hi I recently installed Pegasus on my windows 11 pc and I’m noticing there are no video previews for emulator games nor steam games when going through the ui, I used the scrapper to get the assets and everything works perfectly except for the videos. I use movies and TV to play these files.

### System info

Using Windows 11

### Pegasus version

alpha16-51-g6421d7a7

**Comment by mmatyas** [comment]
Hi! Well, it's hard to say what could be the problem, without knowing the files or seeing the log. Try looking into the log file if you see something weird, or attach it to this issue.

**Comment by mmatyas** [comment]
I'll assume the issue got solved since then, feel free to leave comments and attach log files if not.
