### ISSUE TITLE
Support for desktop files on Linux

### ISSUE THREAD

**Issue by rawdatafeel** [mmatyas/pegasus-frontend#1114]
Ryujinx, RPCS3, and an increasing amount of emulators support creating desktop shortcuts on Linux that automatically open the ROM through the emulator.

For RPCS3 especially, this is helpful as a way to circumvent the file type oddities (installed PKGs and extracted folders). Desktop shortcuts can be treated as the ROM instead and you don't have to worry about trying to figure out how to parse these other file types through a frontend like Pegasus. 

I've tried adding desktop as a file type to my metadata file, but I don't think launching desktop files through the command-line (or a frontend) is as simple as that. 

ES-DE currently supports launching desktop files so there likely is a way to launch these files through a frontend and it would be great to see if this could somehow be implemented in Pegasus.

**Comment by mmatyas** [comment]
Hi! On most systems `.desktop` files can be launched by `gtk-launch` or, alternatively, `xdg-open`. Eg. `xdg-open /usr/share/applications/firefox.desktop`.

**Comment by mmatyas** [comment]
Hm, I'm still not convinced this is supposed to be done in Pegasus. Unlike URIs, symlinks, or platform shortcuts, the desktop files are regular files. When you double click on them, there's some program on your system that opens them, reads them, and executes their command, with regards to a defined specification. Therefore, it is not Pegasus' job to reinvent or replace this mechanic. As for what this program is exactly, that's an interesting question; I assume that this is the "default program" `xdg-open` would use, and it does work on my PC, but the exact setup might differ between distros.

**Comment by mmatyas** [comment]
I'll close this for now, then, as there's a workaround discussed above.
