### ISSUE TITLE
Pegasus not reopening ui when closing Steam game, unless i exit Steam manually

### ISSUE THREAD

**Issue by AlbertDaYoungYT** [mmatyas/pegasus-frontend#1115]
This is probably a stupid question, but is there a way to disable Pegasus closing when launching games (to maybe fix it). Or maybe if this is a steam issue this would be nice to see a fix or if someone knows how to fix it.

For clarity i am running debloated Windows 11 on a Steam Deck LCD, with EmuDeck (which installed Pegasus) and i've added registry keys to "replace" windows lauching explorer.exe with Pegasus to give a better ui experience.

Am also using Handheld Companion to map the Steam Deck Controller to a Xbox Controller.

**Comment by mmatyas** [comment]
Hi! Pegasus returns when the launched program finishes running. However, if the program keeps running in the background, then Pegasus will never return either. Unfortunately, that's how Steam happens to work, so the usual workaround is to configure closing Steam manually by eg. a hotkey or a script.

I'm closing this in favor of #442, where this Steam behavior is discussed.
