### ISSUE TITLE
Adding a session for Pegasus-FE

### ISSUE THREAD

**Issue by Lokito23** [mmatyas/pegasus-frontend#1122]
# Description

It would be interesting if Pegasus on Linux had a [Batocera]/[Lakka]/SteamOS like session, in order to use it as a main frontend.

## Blocking issue

The following issue however, does not allow for this, or would make it clunky to use: #442 

Granted, I know that this issue is more on Valve's side than yours...

I have also ran into problems trying to open Steam games (Steam launches visually), but that is beyond the scope of this issue, and I will open another issue to report it (#1123).

## Concepts

You might be able to use [gamescope-session-plus](https://github.com/ChimeraOS/gamescope-session) in order to create said session, but it has problems with the `-e` or `--steam` property, [since said properties are known for not allowing clients not considered a steam game to render](https://github.com/ChimeraOS/gamescope-session/tree/main?tab=readme-ov-file#window-visibility).

Another option would be to use kiosk window managers, like [cage], which allow you to run a single, fullscreen app, and does not suffer from the issue that [gamescope-session-plus] has.

A problem with [cage] might be setting up WiFi though, since Pegasus (by default), does not give the menus to configure it (and I am not sure if it is even possible).

# Finishing thoughts

While opening Pegasus on fullscreen with another desktop on start-up would also work, I feel like that solution isn't as clean as if a session existed,  as it does not require to wait for a full desktop/WM to load.
It also allows to use Pegasus as a Frontend for controller-first computers (like the Steam Deck, or TV Boxes).

[batocera]: https://batocera.org/
[lakka]: https://www.lakka.tv/
[gamescope-session-plus]: https://github.com/ChimeraOS/gamescope-session
[cage]: https://github.com/cage-kiosk/cage

**Comment by mmatyas** [comment]
Hi! Could you describe what is a "Batocera/Lakka/SteamOS like session"? Do you mean using Pegasus without a window manager? On the Raspberry Pi 4, Pegasus directly uses KMS, so this is probably possible on other platforms too. It also depends mainly on the Qt backend, so if you can build Qt for your use case, then Pegasus too should work on top of it.

**Comment by Lokito23** [comment]
> Could you describe what is a "Batocera/Lakka/SteamOS like session"? 

What I meant there was a session where the frontend is the main GUI of it (like gamepadUI/Big Picture from Steam)

> On the Raspberry Pi 4, Pegasus directly uses KMS, so this is probably possible on other platforms too.

I was unaware of this, not sure if it is in Linux though, would have to check, could you tell me how it is done in rp4? Should be a similar process.

**Comment by mmatyas** [comment]
Sure, for RPi4, Qt is built with the [EGLFS](https://doc.qt.io/qt-6/embedded-linux.html) backend, which handles the lack of window manager. However, because Pegasus have to close and reopen its own window, a [workaround patch](https://github.com/mmatyas/pegasus-frontend/blob/master/etc/rpi4/kms_launch_fix.diff) is also applied to connect/disconnect from the screen.

Basically if there are any graphics requirement, you'll have to start making Qt work there, then you can continue with Pegasus, which might just work out of the box.

**Comment by Lokito23** [comment]
It does work, but with a caveat.

I'm using a laptop, the moment I opened Pegasus with EGLFS it disabled the keyboard.

Not sure what happened there, I'll try connecting an external keyboard.

**Comment by Lokito23** [comment]
Not even using SDDM to load it, the keyboard still didn't work.

I used the following command: `pegasus-fe --platform eglfs`

**Comment by Lokito23** [comment]
Upon further investigation, I have found that the root cause of the keyboard problem is the permissions of `/dev/input/event`, since it's necessary for input in QT to work.

Seems like running it like root is a fix, but I doubt that is a good solution...

However, since I have now seen that it is possible, I don't see much reason to maintain this issue open. As such, I'm closing it.

**Comment by Lokito23** [comment]
As for the implementation, it shouldn't be that different to the one used in RPi4, since they also use Linux.

**Comment by Lokito23** [comment]
Update: I have tried to apply the RPi4 patch, but it keeps giving me libdl errors, so that happened.


I can't seem to find a way to fix it, yet.

**Comment by mmatyas** [comment]
Try the following qmake build parameter: `QMAKE_LIBS_LIBDL=-ldl`

**Comment by Lokito23** [comment]
It compiled, but I tested with a steam game, it didn't find the session.

Log: [lastrun.log](https://github.com/user-attachments/files/15936694/lastrun.log)

That isn't all, will edit an attachment of the output of the command:
