### ISSUE TITLE
Wii U, Wii, DS, and 3DS Support

### ISSUE THREAD

**Issue by LordZane** [mmatyas/pegasus-frontend#130]
This looks like an awesome project, although very wip (no idea how to add emulators or games, my steam games were auto detected but I couldn't seem to launch them, and holding down the enter button on a game makes tons of instances of this program). However im sure that will all be fixed eventually, and so I just wanted to let you know that themes for the platforms I listed in the title would be great. Keep up the good work!

**Comment by mmatyas** [comment]
Thanks, and yeah it's still in alpha, but feel free to report any issues you find (I'll check the bugs you've mentioned). At the moment the config files (`es_systems.cfg`) of EmulationStation are used (until #14 is done), you can find its documentation [here](https://github.com/Aloshi/EmulationStation#configuring) and [here](https://github.com/Aloshi/EmulationStation/blob/master/SYSTEMS.md).

**Comment by mmatyas** [comment]
I've just fixed the Steam launching bug, should work fine now.
Couldn't reproduce the enter key problem though, could you share more details or a screenshot/video of it?

**Comment by LordZane** [comment]
Yep steam launching works now, and I think it was connected to the enter key bug. Before launching a steam game would close the window and then reopen it, and holding enter would do that, spawning many windows. Now its no longer a problem. Ill leave this open until theme support for the platforms I listed is done though

**Comment by mmatyas** [comment]
A bit late, but now all the requested logos are available in the latest version.
