### ISSUE TITLE
Feature request a way to ignore Quit scripts when you select Reboot or Shutdown

### ISSUE THREAD

**Issue by shantigilbert** [mmatyas/pegasus-frontend#179]
As I understand right now every time you select Reboot or shutdown and have scripts on Quit they also get executed, or at least that is whats happening right now. 

If you have a program that runs over Pegasus on quit (in my case Kodi) then Kodi starts even when I select Reboot or Shutdown and the reboot/shutdown never happens. 

There should be a way to ignore quit scripts, maybe using names? maybe a suffix nr = not at reboot ns = not at shutdown.

a-script-nrns.sh

**Comment by mmatyas** [comment]
Yes, the onQuit scripts are called before reboot and shutdown too, and the reboot/shutdown happens only after all scripts have finished running. I'd prefer not changing that, but I can add a new category of scripts that'd run on the regular close event. Would that solve the problem?

**Comment by shantigilbert** [comment]
I don't think I understand the solution. My idea was to have an option to not run onQuit scripts since right now the shutdowm/reboot keeps getting interrupted by the quit script. 

I know this might be another odd request from me and I totally I understand if you don't want to change it. 

Another solution for me is to create a patch for the Reboot and Shutdown functions, that way you won't change anything and I get the functionality I need. I see on https://github.com/mmatyas/pegasus-frontend/blob/master/src/backend/SystemCommands.cpp that you use QProcess::startDetached to start another process, could I modify this to run any command? like
 `QProcess::startDetached("/usr/bin/sh /path/to/my/script.sh"); `
?

Thank you and sorry for all the bother!

**Comment by mmatyas** [comment]
I mean, currently on restart/shutdown, you run the quit scripts and the restart/shutdown scripts, while on regular application close, only the quit scripts. I could change that so on app close, other than the quit scripts, a new category (directory) of scripts would run too. You could create a completely different set of scripts to run on app close, restart and shutdown, with all three calling the on quit scripts first.

In your case, I suppose you'd want to restart Kodi only on close, but not on reboot/shutdown, so you'd put that script into this new directory.

**Comment by shantigilbert** [comment]
Yeah I think that would work, but unless you think its a good idea to implement it, otherwise I don't want to waster your time. But I like I mentioned, I could create a patch that works only for me, would something like this work in my case? 

```
void onAppClose(AppCloseType type)
{
    using ScriptEvent = ScriptRunner::EventType;

     switch (type) {
       case AppCloseType::QUIT:
            ScriptRunner::findAndRunScripts(ScriptEvent::QUIT);
            break;
        case AppCloseType::REBOOT:
            ScriptRunner::findAndRunScripts(ScriptEvent::REBOOT);
            break;
        case AppCloseType::SHUTDOWN:
            ScriptRunner::findAndRunScripts(ScriptEvent::SHUTDOWN);
            break;
        default: break;
    }

    qInfo().noquote() << QObject::tr("Closing Pegasus, goodbye!");

    QCoreApplication::quit();
    switch (type) {
        case AppCloseType::REBOOT:
            SystemCommands::reboot();
            break;
        case AppCloseType::SHUTDOWN:
            SystemCommands::shutdown();
            break;
        default: break;
    }
}
```

**Comment by mmatyas** [comment]
Yes, that'd work, then the quit scripts will be only called on app close, but not by restart/shutdown.

Another idea: if you want to start Kodi right after Pegasus quits, you could create a script and call that in the systemd module, something like

```sh
#!/bin/bash

/path/to/pegasus-fe
/path/to/kodi
```

(which is the reason for not having an on-app-close category, as I've just remembered)

**Comment by shantigilbert** [comment]
Yes that works, but in my case I need to run them with systemd-run which does not wait for program to end to continue. 

The patch solution works perfectly for me :) 

Thanks again for your help! and sorry to have bothered you with my odd requests again.
