### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend#181]
Ideally with automatic builds, Intent support and proper metadata. Depends on #14. Fun idea: detect Android games.

**Comment by mmatyas** [comment]
Auto build added in #233.

**Comment by Yabuato** [comment]
@mmatyas 
You're doing an unbelievable amazing project,hopefully we will finally have a frontend like ES on Android! Keep going!

**Comment by Yabuato** [comment]
Hi,mmatyas thanks for developing android version.Can the android build be used now?

**Comment by mmatyas** [comment]
Still in progress, but i think I can work on it some more this week.

**Comment by mmatyas** [comment]
Ok, proper Android builds are now available, confirmed working and has documentation.

- demo video: https://www.youtube.com/watch?v=d4kvUZjZ_tI
- documentation: http://pegasus-frontend.org/docs/user-guide/platform-android

I'm closing the issue, but if you see anything strange on Android, feel free to report it!
