### ISSUE TITLE
Stats in menu: Top 20 Games List

### ISSUE THREAD

**Issue by AndersHP84** [mmatyas/pegasus-frontend#194]
A fun feature for the future menusystem could be a "Stats" section containing a "Top 20 Games List" with Number of times played next to the games, or something like that.

I believe stats are automatically generated and part of the gamelists?

**Comment by mmatyas** [comment]
Yeah this could be an interesting feature, I can imagine some kind of dashboard with stats, maybe even with Achievements and such. Stats are not saved *yet*, but they'll likely end up stored in a separate file, in order to keep the metadata files read-only.

**Comment by mmatyas** [comment]
It is possible now to create themes with such feature (eg. gameOS), so I think the issue can be closed. The default theme at the moment doesn't have a top games list, in order to keep things simple.
