### ISSUE TITLE
Draw icon/logo

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend#24]
One does not simply release a beta without style.

**Comment by mmatyas** [comment]
In case someone is interested in this issue, here's a little history for inspiration:

"Pegasus" comes from an extremely popular (and at the time about the only available) game console in [my country](https://en.wikipedia.org/wiki/Hungary). Here's a nice article as a background: http://www.retrojunk.com/article/show/4938/pegasus-polish-nes-clone. For more history, see also [[1]](https://en.wikipedia.org/wiki/Pegasus_(console)), [[2]](https://en.wikipedia.org/wiki/Dendy_(console)), [[3]](https://en.wikipedia.org/wiki/Terminator_2_(console)), [[4]](https://en.wikipedia.org/wiki/Micro_Genius). To me, this is what feels truly retro (not eg. arcades, which still don't seem to exist here).

**Comment by mmatyas** [comment]
Some sketches I've made for an icon:

![pegasus_logos](https://user-images.githubusercontent.com/4354863/30242292-0ca93dfe-9594-11e7-8964-ee10527fb793.png)

Apparently it looks like a medical symbol to some...

**Comment by hex007** [comment]
How about this? 

![pegasus](https://user-images.githubusercontent.com/1689246/30243234-3137532a-955a-11e7-93f1-c69237ca2bab.png)

**Comment by mmatyas** [comment]
I'm leaving this open for a while, no need to hurry with the decision. Some **general** guidelines I've copied from the RetroPie logo contest, which one *could* use during the design:

 **Musts**

- Something that looks good small as well as in larger formats.
- Something that we could also use on merchandise, stationary and in publicity materials.
- Flexibility is important in colour as well as style.
- The logo should look good in b/w as well as in colour.
- Be generic enough to not favour or promote any one system or game.

**Ideal**

- We’re after something that will be recognisable.
- It should capture retro gaming as a whole.
- Avoid clichés or the obvious.
- The fewer colours you can use the better.

Also I'd like to mention that since choosing the logo depends on personal preferences, you might not agree with the end result or my opinions.

**Comment by mmatyas** [comment]
Here's a nice literal-Pegasus symbol ([source](https://thenounproject.com/term/pegasus/203551/)):

![kep](https://user-images.githubusercontent.com/4354863/30244002-f7579c94-95b5-11e7-9160-a5c13e818083.png)

**Comment by lilbud** [comment]
Just did a crappy sketch, what do you think?
![image](https://user-images.githubusercontent.com/9311410/30250323-38f10d20-961a-11e7-9539-3d14481aed78.png)

**Comment by mmatyas** [comment]
@hex007 Sorry for the late reply, I wasn't sure if I should comment the logos during this issue or only at the end -- I think I'll do it continuously. As for the logo, I'm looking for something more consistent; there's a bit too much going on there (a P with one color scheme, a flat big circle, a different colored small circle with multiple shadows, a small dpad, etc.). 

@lilbud this looks really well composed. The hole in the P kind of resembles a keyhole or a scale; combined with deep blue it gives the feeling of a legal agency to me. You can also see the left side as the front of a ship, with the additional idea of flying/wings, which would be a clever logo for a travel agency.

**Comment by lilbud** [comment]
The hole in the 'P' is meant to look like a arcade joystick. The left side is meant to look like a Pegasus wing, but not as stylized. I tried to make the logo look professional.

**Comment by mmatyas** [comment]
Ah don't get me wrong, I do see those features, and the logo indeed looks professional. I'm merely listing some points that might affect the initial impression the logo creates in a user.

**Comment by lilbud** [comment]
Well if anything needs changing, let me know and I'll fix them this afternoon

**Comment by mmatyas** [comment]
Ok, your turn now. Had some ideas the weekend:

<table>
 <tr><td rowspan="2"><img src="https://user-images.githubusercontent.com/4354863/30512421-8fe1bc36-9aef-11e7-8451-b4fc3c45f016.png"/>
</td><td><img src="https://user-images.githubusercontent.com/4354863/30512427-a0fbbd00-9aef-11e7-91f8-22d643e47af1.png"/>
</td></tr>
  <tr><td>
<img src="https://user-images.githubusercontent.com/4354863/30512435-d4df204e-9aef-11e7-9399-5ae9b71acdcb.png"
</td></tr>
</table>

What do you think?

**Comment by lilbud** [comment]
That looks really good. Though I'm having trouble seeing where it fits into gaming.

**Comment by mmatyas** [comment]
Yeah I was thinking about adding little hints, like making the circle-cut at the top into a pacman and such, but in the end it didn't really look good.

**Comment by The8bitOwl** [comment]
Here something, to help with the inspiration...

**Comment by mmatyas** [comment]
I've made a v2, the base form hasn't changed, but it's less wide and fills the icon-square better:

![pegasus-logo-kockasabb-clean svg](https://user-images.githubusercontent.com/4354863/30782243-7598e38c-a12e-11e7-8db0-8c74817c75f6.png)

**Comment by websterkk** [comment]
Any idea that the logo has to incorporate some retro gaming icon is stupid.  The last few logos that mmatyas showed are great. I prefer the older version because it better resembles a wing. The red on black background especially looks slick. All the other suggestions are pretty terrible.

**Comment by lilbud** [comment]
Well the retro gaming aspect of the logo is kind of important seeing as Pegasus is a _graphical frontend for launching emulators and managing your game collection_

**Comment by mmatyas** [comment]
Yeah it'd be nice if I could add some hints that this is a gaming-related program, I'm just not sure yet how to show that properly on the logo. It's true though that most other frontends don't have gaming elements either (see eg. [ES2](https://github.com/Aloshi/EmulationStation/blob/master/data/resources/splash.svg) or [attract](http://attractmode.org/) or [mehstation](https://github.com/remeh/mehstation/blob/master/res/splashscreen.png)).

**Comment by websterkk** [comment]
It is absolutely not important to add a retro gaming aspect to the logo. There's a reason why the majority of logos don't include some hint about the product. Whether or not it would be cool is hardly relevant to any criticism about a logo that is really good, and frankly, way better than any of the other ideas shown here. Obviously it's not my project and I'm not offering anything other than some praise for a great design that I think was stupidly criticized, but if someone thinks it needs to have a retro gaming twist, put up something that doesn't suck.

**Comment by websterkk** [comment]
![base](https://user-images.githubusercontent.com/18541959/31630579-d46a788c-b26b-11e7-99ab-9163f2be3409.jpg)
![md](https://user-images.githubusercontent.com/18541959/31630578-d469ad80-b26b-11e7-9c72-60e7520f7269.png)
![p](https://user-images.githubusercontent.com/18541959/31630577-d4503af8-b26b-11e7-8b00-298b0d9a8f42.png)
![peg](https://user-images.githubusercontent.com/18541959/31630576-d4440c7e-b26b-11e7-8a05-1227654f5146.jpg)
![mario](https://user-images.githubusercontent.com/18541959/31630580-d48902ac-b26b-11e7-8b65-9b29860a61db.png)

mmatyas, here's something I threw together quickly. Please incorporate everything. Now go be inspired.

**Comment by mmatyas** [comment]
Heh, okay okay, I get the point, thanks :)

The wings are indeed a bit too small in the rectangular version (people I've showed the logo didn't really see them either), so I made a sketch somewhere between the two:

![screenshot from 2017-10-16 22-46-13](https://user-images.githubusercontent.com/4354863/31634444-d815b1f6-b2c3-11e7-87a7-ade4587b0bde.png)

**Comment by mmatyas** [comment]
So if there are no new entries, I'd like to close this thread by the end of the month.

**Comment by tronkyfran** [comment]
That logo is awesome right now. I vote for it, no need for further searching ;)

**Comment by mmatyas** [comment]
All right, ladies and gentlemen, this issue is now *closed*. I'll now start using the logo I've posted just above. Thanks everyone for the participation and comments!
