### ISSUE TITLE
Emulator crashes soon after I launch it with Pegasus

### ISSUE THREAD

**Issue by shantigilbert** [mmatyas/pegasus-frontend#28]
I finally managed to get Pegasus running on my Amlogic S905 device, and I am super excited for this FE is amazingly fast and it looks very cool already!

however I seem to be having a problem when I launch an emulator, it crashes after about 1 minute inside, here are some examples, one launching Advmame and the second launching Retroarch.

```
Executing command: `/usr/bin/advmame.sh /storage/roms/mame-advmame/dbreed.zip`
Process 3098 started
The external program `/usr/bin/advmame.sh` has crashed
The external program has crashed on exit, with exit code 15
```

```
Executing command: `/usr/bin/retroarch -L /tmp/cores/snes9x2010_libretro.so "/storage/roms/snes/2020 Super Baseball (USA).zip"`
Process 3003 started
QProcess: Destroyed while process ("/usr/bin/retroarch") is still running.
The external program `/usr/bin/retroarch` has crashed
The external program has crashed on exit, with exit code 9
```

I understand this is in alpha but I am jut letting you so you can be aware.
not sure if there is some sort of debugging log I can provide to help with this.

**Comment by mmatyas** [comment]
Thanks! When does the crash happens exactly? *After* you've finished playing a game, and you're on the UI, where it suddenly crashes? Or when you finish a game, it can't restore the UI?

At the moment, the log is only the terminal output, but there'll be a separate file eventually.

**Comment by shantigilbert** [comment]
It happens just after launching the game, unexpectedly and it goes back to the UI, I can keep using it and select another game but it does the same thing. sometimes it takes 1 minute, sometimes it takes less. 

On the same device I have ES and it works as it should.

**Comment by mmatyas** [comment]
I've confirmed this bug on Raspberry as well; for some reason the process handling code doesn't work well with RetroPie's `runcommand`. I'll try debugging this next week.

**Comment by shantigilbert** [comment]
The latests commits from the process_improvements branch fixed the issue for me.

**Comment by mmatyas** [comment]
Great, thanks for checking!
