### ISSUE TITLE
Android - controller input issues

### ISSUE THREAD

**Issue by RexBorova** [mmatyas/pegasus-frontend#328]
Not sure if this is a known issue on Android devices or not, but whenever I use Pegasus on my shield TV or my Galaxy S9 phone, navigating with the dpad and/or left analog stick will always give me double input. It will recognize an input from either or, and output both a press from the dpad and analog stick, if that makes sense. I've tried to unbind inputs for either dpad or analog but I can only rebind atm. Also, I cannot exit out of controller configurations holding down the "B" button. It will go have way and keep resetting, so I have to hard quit out to main menu. Just thought I should mention this in case anyone else has this same issue on Android devices. as well.

Edit: I've tested an Xbox one controller and a 8bitdo controller on android for this behavior. I've also tested the same Xbox controller on Win10 and works perfectly fine there. Tested stable and latest nightly build too.

**Comment by mmatyas** [comment]
Thanks for testing! So for example, using the default theme, when you press DPad Right, the selection goes 2 games to the right?

**Comment by RexBorova** [comment]
Correct @mmatyas , it takes the input of the dpad and left analog stick at the same time. So dpad up will go 2 games up, or even navigating the menu will move 2 spaces anywhere. Affects any theme i use too. This behavior only occurs on Android when I tested it, Windows 10 works flawless.

I also want to note that the Shield TV controller behaves perfectly fine with input, and also a wireless keyboard that I have used. This behavior only occurs with gamepads for some reason. Sorry for the late reply!

**Comment by mmatyas** [comment]
Hm so the Shield controller and the keyboard works fine, but the Xbox One and the 8bitdo controllers has this navigation issue?

**Comment by mmatyas** [comment]
Also, is [this](https://www.amazon.co.uk/Nvidia-945-12920-2500-000-NVIDIA-SHIELD-Controller/dp/B01N7DQ0L6) the kind of Shield controller you're using? I wonder if it works differently than the others...

**Comment by mmatyas** [comment]
I see, will look into the issue. Thanks for testing!

**Comment by Purq** [comment]
i noticed, that the right thumb stick is doing well - but not every controller have a (right) stick ...is there a possibility that android uses the left stick (also) as dpad and the right one actually as a "stick" ?

**Comment by mmatyas** [comment]
I think it's just that for some reason (compatibility?) dpad presses also acts as if the left stick was pressed, and left stick movements count as dpad pressed too. No idea if this is an Android "feature" or a Qt bug or something.

**Comment by RexBorova** [comment]
Just to add to this, I've tried my x360 controller with the wireless adapter, and I didn't have navigation issues. I'm beginning to think this is only an issue with wireless Bluetooth devices. I can navigate just fine with any device that uses it's own wireless dongle to connect ex: Xbox 360 Wireless controller with Wireless adapter, and my Logitech wireless KB and mouse with USB dongle. (Testing on latest stable 10 release)

**Comment by mmatyas** [comment]
Hm that's really interesting. Also didn't you mention the USB gamepad failing too?

**Comment by mmatyas** [comment]
I've just managed to fix the navigation issue, there were indeed some duplications between the Dpad and the left stick. Tested with an Xbox One controller using regular Bluetooth, seems to be working fine now.

As for the back button, it seems when you hold down a button, it starts to get repeated, like when you hold a keyboard key in a text editor. Except with keyboards, Pegasus can detect which key presses were caused by this autorepeat, and which ones are real key presses. Now it seems the gamepad also autorepeats for some reason (which it should not do though), but does not mark the button presses as autogenerated. So it's as if you're repeatedly pressing and releasing the button (you can also see it if you try to open the main menu by holding down B). I wonder if this is a device specific thing, or happens with all controllers.

**Comment by RexBorova** [comment]
I can confirm the same issue for the "repeated button" that @Purq mentioned. Great work as always and thank you very much @mmatyas , can't wait to test it out myself!

**Comment by mmatyas** [comment]
It's been a while, but as of the latest version, there's no longer any settings screen that uses press-and-hold for an action. I think this can be closed now.
