### ISSUE TITLE
[BUG] If no games are present the theme won't load

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#330]

**Comment by RexBorova** [comment]
I don't believe this is a bug. Pegasus requires a collection of games before a theme can be present. You should be prompted to a screen that says "we didn't detect a list of games", or something along those lines.

**Comment by PlayingKarrde** [comment]
> I don't believe this is a bug. Pegasus requires a collection of games before a theme can be present. You should be prompted to a screen that says "we didn't detect a list of games", or something along those lines.

Sorry I should have elaborated on the bug. The error I get is the same as if there is an error in the QML. I only tested this on the mac build so it may be mac specific. I definitely didn't get the error message you suggest.

**Comment by RexBorova** [comment]
Ah, gotcha!

**Comment by mmatyas** [comment]
@PlayingKarrde You should see a screen like this when there are no games available:

![screenshot_2018-10-22_19-33-29](https://user-images.githubusercontent.com/4354863/47308404-cadca700-d631-11e8-8bed-60d373d243dd.png)

What happens for you instead? Could you post the log file? There should be QML errors in it if there were loading issues.

**Comment by PlayingKarrde** [comment]
Ah yes sorry my mistake. I was used to seeing the error screen during theme deveopment so didn't read it closely. I just double checked and indeed this is the error screen. My bad.
