### ISSUE TITLE
Add LaunchBox support

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend#334]

**Comment by PlayingKarrde** [comment]
[Here's a Metadata.xml](https://www.dropbox.com/s/905zmpiiwqnyki4/Metadata.xml?dl=0)

**Comment by spektor56** [comment]
Just making my own C# app to do this.  If you haven't done it already I will have something fully working soon.  Right now i have the metadata files generating just need to add the asset scraping.

**Comment by spektor56** [comment]
actually i'm dumb, scraping all the previous work and making a launchbox plugin that will do it instead.

**Comment by mmatyas** [comment]
You mean a plugin for launchbox that exports in Pegasus' format? Yeah, that's certainly a nice option too! I've started working on the reverse direction, reading the files from Pegasus, just haven't had the time to finish it properly yet (there's so little work left! but still, it requires time).

**Comment by spektor56** [comment]
Yes, my first program was reading the xml's and copying the images from the proper folders and got my setup working that way.  Then I realized shit, launchbox supports plugins why the hell did I do it that way!?  So yea, redoing it in plugin format even though my old program works fine.  This will guarantee

**Comment by spektor56** [comment]
Ok, here's my initial commit:
https://github.com/spektor56/PegasusExportPlugin

Currently has no error handling and no options to select which platforms / games to export.  Also in the case for duplicate media types, doesn't let you choose which one you want.  Will add all that stuff later.

**Comment by mmatyas** [comment]
LaunchBox support is now available in both the latest and the stable releases, it should work out of the box. Feel free to open issues if something doesn't seem to work as expected!
