### ISSUE TITLE
Add relative command support

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend#341]
"Is there a way to specify a relative directory for collections commands rather than absolute? I'm trying to make my build as portable as possible so having

`command: G:\Dropbox\Emulation\PegasusLauncher\systems\redream\redream.exe "{file.path}"`

Is definitely less desirable than

`command: systems\redream\redream.exe "{file.path}"`"

**Comment by substring** [comment]
I'm using quite often portable mode, and by manually editing the `config/game_dirs.txt` you can use relative paths. For example: 
```
./collections/megadrive
./collections/snes
```

**Comment by mmatyas** [comment]
This was a forum comment originally, and I *think* I've implemented something related already. Someone mentioned another related problem though so I'll have to double check.
