### ISSUE TITLE
Pass arguments to game launcher

### ISSUE THREAD

**Issue by yoyofr** [mmatyas/pegasus-frontend#354]
Hi,
congratulation for the great work so far. I've started to implement some mod on the standard grid template to add savestates feature => build a row of existing savestate (with thumbnails).
The idea is to mimic the nes or snes classic mini frontend "suspend point" feature.
I miss a way to pass additional arguments when launching a game to the emulator (retroarch) to reload the selected savestate.
Is it something you could add please ?

**Comment by mmatyas** [comment]
Hi, themes have no information about the launch commands of the games, as that differs on each platform. So themes aren't the best place to this, but could be done either in a script or by Pegasus.

I'm not familiar with the exact commands, but you could make a wrapper script for RetroArch where you could find out the game for a save state. Eg, if you have `gamename.state`, you'd launch `gamename.rom` with the savestate. Or something like that.

It's also possible to add save support to Pegasus itself too, but that will take some time.

**Comment by HerbFargus** [comment]
As far as I'm aware there isn't a command line argument for launching save states with retroarch (yet)

See https://forums.libretro.com/t/can-i-load-a-saved-state-through-command-line-cli/18364/4

Related: https://github.com/libretro/RetroArch/issues/7398

**Comment by yoyofr** [comment]
thanks for the replies. To integrate savestate concept into pegasus would be the best, meanwhile I would need at least a way to position a flag somehwere that I could intercept in a script.
I would like to avoid to create dummy roms entries in the collection (for example adding fake entries in the gamelist.xml for each available savestate) => it would grow the gamelist and require lots of management in the qml themes.
A quick (and dirty) way to do it could be to be able to write to a tmp file from the qml themes => I would write the savestate nb to a /tmp file (to determine) and implement the logic describred by HerbFargus in a wrapper script.
I tried to setup a cross compiling env from a linux mint VM, was able to build QT 5.9 with EGLFS support but I'm stuck with the additional modules :-(

**Comment by yoyofr** [comment]
small update: I was able to install a full QT cross compile env and rebuild pegasus. Seems to work ok. I will work on adding required features and if it works well I'll post some updates here

**Comment by mmatyas** [comment]
There haven't been much activity on this topic, and alternative concepts have been popping up on the Discord channel, so I think this can be closed for now.
