### ISSUE TITLE
Skraper assets overwritten by EmulationStation

### ISSUE THREAD

**Issue by waldnercharles** [mmatyas/pegasus-frontend#356]
The title is pretty specific, but, this might apply to all providers.

It seems like assets from Skraper aren't being picked up at all if EmulationStation is selected.

Repro steps:
1. Scrape for assets using Skraper (Get something that EmulationStation doesn't pick up, like wheel)
2. Run Pegasus with both EmulationStation and Skraper providers active, notice that wheel assets do not appear.
3. Run Pegasus with only Skraper provider active, notice that wheel assets now correctly appear.

I understand that there is a priority to loading, but I think the expected behavior should be to only overwrite assets if they are found.

**Comment by waldnercharles** [comment]
This only seems to happen if collections.txt does not exist in each rom folder.

**Comment by mmatyas** [comment]
Sorry for such a late reply; I've tried with some freshly scraped assets but could not reproduce the issue, and, with your comment added, I'm not sure if this is an actual bug.

- The ES provider uses the assets defined in `gamelist.xml` of a rom folder, for each rom folder defined in `es_systems.cfg`. On its own this means only box front, marquee and video assets.
- The Skraper provider looks for asset directories under `<romfolder>/media` and `<romfolder>/skraper`, for each rom folder added in Pegasus' settings menu, ie. directories with `collections.txt` in them.

If I understand the comment correctly, this setup also works for you as well. But then how exactly did you produce the error again? Have you found a bug where the Skraper provider runs for directories *not* added in the menu?

**Comment by waldnercharles** [comment]
I agree that this is probably not a bug. I think my original assumption was that the ES provider, and the Skraper provider would communicate.

For instance, if there was no collections.txt, the skraper provider could find the media assets via the ES provider's es_systems.cfg/gamelist.xml

Feel free to close this if you think there's no action to take.

**Comment by mmatyas** [comment]
Ah I see, yes, it'd be certainly possible. I'll see if I can add support for that in a clean way.

**Comment by mmatyas** [comment]
Ok, this should be fixed now in the latest release. Media and Skraper directories are now searched in both Pegasus' and ES2's directories.
