### ISSUE TITLE
Duplicates added when games are found via collections.txt and ES scraper

### ISSUE THREAD

**Issue by waldnercharles** [mmatyas/pegasus-frontend#364]
If a game is found via both the ES2 scraper and a collections.txt, it is duplicated in api.collections.

Ideally, if a game with the same path already exists in api.collections, it won't be added.

**Comment by mmatyas** [comment]
There have been quite some changes since opening this issue, does this still happen?

**Comment by mmatyas** [comment]
Hopefully this got resolved then.
