### ISSUE TITLE
Portable mode saves an absolute path for the theme

### ISSUE THREAD

**Issue by substring** [mmatyas/pegasus-frontend#368]
Hi,

It would be great if the theme  setting could be saved as "just its name":
- when in normal mode, you are anyway looking in the application folder according to the system
- when in portable mode, the path is necessarily the themes subfolder sitting next to the binary

This way, pegasus would be more portable. In my case I'm having fun with a portable pegasus, using it in both Linux and Windows. As the selected theme is saved with an absolute path, changing OS resets to the default pegasus-grid.

**Comment by mmatyas** [comment]
Good idea! The problem with names only however is that in normal mode more than one theme directory is checked, and those may contain themes with the same name. Something like using relative paths but only in portable mode would be possible though.

**Comment by substring** [comment]
As the problem is just for portable mode, use relative path for themes only in portable mode then. That' sounds just perfect

**Comment by mmatyas** [comment]
Ok, this should be working now in the latest version.
