### ISSUE TITLE
Slow performance on Windows

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend#374]

**Comment by iwubcode** [comment]
I'm not sure what the slow performance issue is around but I've noticed a couple of things:

* Starting up with only two games + two directories to search is very slow.  I launched multiple times thinking it was frozen (stuck on a screen saying '0 games') until I let it continue.  Just using steam startup is quite quick (only a handful of games though)
* Moving the game selection cursor back and forth between icons is sometimes responsive and other times laggy.  This might be related to the video playback so switching to the QtMultimedia thing might help there too.

**Comment by iwubcode** [comment]
You might already have ideas on what the performance issue is, so I might just be adding noise here.  My apologies if so.

I will say I am not well versed with Qt but some searching seems to indicate that `QDirIterator` may be part of the culprit.  If you switch to C++17, you could leverage `std::filesystem` to iterate.

**Comment by mmatyas** [comment]
That's a quite extreme startup time; does it happen every time you launch Pegasus? Is it affected by any of the data sources you can enable/disable in the Settings menu? Anything in the log?

**Comment by iwubcode** [comment]
@mmatyas - yes, reproducible every time I start the program.  I have all data sources turned off.  I have turned on steam and still see the same behavior.  (however if I remove the games as mentioned in the other issue, steam starts up instantly).

I do not see anything in the log.  I'm hoping to install Qt when I get some time so that I can try to help diagnose issues.  I might even try and write some code, I love the base you have here, very excited about it!

**Comment by iwubcode** [comment]
Alright, so see the other bug for detailed information but I believe the slow startup performance was due to the bad file format.  It is now quite fast to start up.

**Comment by mmatyas** [comment]
There have been a few improvements related to the loading time in the latest version. Could someone try and see how much it helps on Windows?

**Comment by HerbFargus** [comment]
Just to add some context on some of my test cases.

Leaving a metadata.txt in the root yields 7+ seconds loading time to load one game

Running it portable with metadata in the metafiles folder is only a few milliseconds.

I need to run more tests to see if I can reproduce it and provide more context on my filepaths to see if I can narrow down what the real issue might be.

**Comment by mmatyas** [comment]
I'm closing this in favor of #839 and #825.
