### ISSUE TITLE
Relative commands don't work on Windows

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend#375]
See https://retropie.org.uk/forum/post/173863 and https://retropie.org.uk/forum/post/174463.

**Comment by HergBlerg** [comment]
Maybe related, i can't seem to use Environment Variables in paths either.
As you stated in your second link, working directories seem to be broken as well, which is causing unexpected behavior with my apps. One emulator started saving it's config files to the rom's path, rather than it's own.

**Comment by mmatyas** [comment]
Should be fixed now, including the working directories.
