### ISSUE TITLE
Add Compatible Emulators/Systems to README.md

### ISSUE THREAD

**Issue by PizzaLovingNerd** [mmatyas/pegasus-frontend#377]
I think that a list of compatible systems should be added to the read me...

**Comment by mmatyas** [comment]
Hi, Pegasus itself doesn't contain any game-specific code, it supports each and every emulator and system that you can launch. There are some optional compatibility modules, like Steam, for convenience, they are documented [here](http://pegasus-frontend.org/docs/user-guide/meta-sources/).

**Comment by mmatyas** [comment]
I guess this can be closed, feel free to ask if you have any other questions!
