### ISSUE TITLE
Option to hide mouse cursor when in full screen

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#378]
Having a cursor is nice but when set to full screen it would be ideal to be able to hide the mouse cursor for the 10ft experience on Windows.

**Comment by sergioad** [comment]
Agree, same in RetroPie, having a mouse on a gamepad centric environment is pointless, a hide cursor option in the settings would be awesome

**Comment by mmatyas** [comment]
Ok, this should now work in the latest release.

**Comment by mmatyas** [comment]
-> #838
