### ISSUE TITLE
Metadata.txt no longer detected

### ISSUE THREAD

**Issue by RexBorova** [mmatyas/pegasus-frontend#379]
Recently with the latest builds my metadata.txt files are no longer detected in Pegasus for my NES collection , and will not show descriptions for games, ratings, etc. The collection.txt file is detected and will produce a game list though. Unless the format has changed that I'm not aware of lol

**Comment by mmatyas** [comment]
Sorry for the late reply, yes, there was a format change recently, the collection and metadata files have been merged into one. You can find more details [here](https://retropie.org.uk/forum/post/177477), and convert between the previous (alpha 10) and the current format [here](http://pegasus-frontend.org/tools/convert/). A proper update guide is also in the works but it's not finished yet.

**Comment by RexBorova** [comment]
ah i gotcha! Thank you and no need for the apology. I should of did a bit more research. Thanks for the reply.
