### ISSUE TITLE
Feature Request - load multiple files from 'global_collection' directory

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-frontend#382]
I don't like to muddy up my game folders with other files.  However, it seems the 'global_collection' directory only supports a single collection file.  I'd like to specify one per platform to keep it easy to manage.  I'm using the portable option if that  matters.

Very cool frontend though, thank you!

**Comment by mmatyas** [comment]
That's a good idea! Might need some work but should be doable.

**Comment by mmatyas** [comment]
Added support for this in the latest version, Pegasus will now try to read all files ending with `.metadata.txt` (or `.metadata.pegasus.txt`)  under `[configdir]/metafiles/`. Feel free to report if something doesn't seem to work!

**Comment by iwubcode** [comment]
@mmatyas - it works perfectly.  Thank you!
