### ISSUE TITLE
Bug - games found but pegasus showing no games?

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-frontend#383]
I might be doing something wrong but was wanting to test this out a bit before Launchbox support is added.  My log is showing:

```
2019-02-24T14:16:04 [i] Collections: found pegasus-fe_alpha10-129-g05880d0_win-mingw-static/config/global_collection/collections.pegasus.txt`
2019-02-24T14:16:04 [w] No games found for collection 'platform', ignored
2019-02-24T14:16:04 [i] Games found in 1ms
2019-02-24T14:16:04 [i] Assets and metadata found in 0ms
2019-02-24T14:16:04 [i] 2 games found
```

collections file:

```
collection: platform
extensions: iso
launch: emulator.exe "{file.path}"


game: Game1
files:
  "C:/games/platform/test game.iso"
developer: Game dev
genre: Adventure
players: 1
description: A description for game 1

game: Game2
files:
  "C:/games/platform/test game2.iso"
developer: Another
genre: Something
players: 1-4
description: A description for game 2
```

(stripped out real details)

Tested in portable mode on `alpha10-129-g05880d0` using Windows 10

**Comment by mmatyas** [comment]
Looks like a bug, thanks!

As for *why* they are not found, where exactly is your collections file located? Could you try listing the `files` without quotes?

**Comment by iwubcode** [comment]
My collection is in 'global_collection'

I am pretty sure I tried it without the quote but I will give that another shot.  Thank you!

**Comment by mmatyas** [comment]
Ah I see, somehow I didn't notice it in the first post, this explains it. By default, collections search for files in the directory of the collection file. So in your case if there are no iso files there, none of the game paths will match, but will incorrectly get printed as found. 

To add more directories, you can use the `directories` (or `directory`, whatever) property of `collection`. Interestingly it's not documented, will fix this too. Adding `directory: C:/games/platform/` for the collection should make the files get found.

**Comment by iwubcode** [comment]
Thank you for your help.  It'd be nice to be able to specify full pathes for `file` but I tried what you suggested.

Here's the various configuration samples I used:

```
directories:  "C:/dir1", "/dir2"
```

```
directories: "C:/dir1"
directories: "C:/dir2"
```

and

```
directory: "C:/dir1"
directory: "C:/dir2"
```

All failed to find the files.  Each directory has all of 3 files with one matching the extension.  The games were listed in the `file` property and I tried both quoting or not quoting them (since they contain spaces).

I called out the performance on #374 but it might be taking a long time since there's some bug here?

**Comment by iwubcode** [comment]
Ok, so my guess now is that `QDirIterator` is having issues with the fact my games are on a separate internal hard drive.  My example file:

```
collection: MINEEEEEE
extension: foobar
launch: C:/mytest/test.exe "{file.path}"
directories: "F:/test/game1" "F:/test/game2"


game: Dummy game 1
file: "dummy.foobar"
developer: Dev1
genre: Test
players: 1
release: 2019-02-26
description: Testing 1,2,3


game: Dummy game 2
file: "dummy 2.foobar"
developer: Dev2
genre: Test
players: 1-4
release: 2019-02-26
description:
 Testing again
 .
 4,5,6
```

works fine when I move the files to `C:\` but if I use another drive, it fails.

**Comment by mmatyas** [comment]
Could you try this config? (Feel free to change the paths of course)

```make
collection: MINEEEEEE
extension: foobar
launch: C:/mytest/test.exe "{file.path}"
directories:
  F:/test/game1
  F:/test/game2


game: Dummy game 1
file: F:/test/game1/dummy.foobar
developer: Dev1
genre: Test
players: 1
release: 2019-02-26
description: Testing 1,2,3


game: Dummy game 2
file: F:/test/game2/dummy 2.foobar
developer: Dev2
genre: Test
players: 1-4
release: 2019-02-26
description:
 Testing again
 .
 4,5,6
```

`directories` works similarly to `files`: there's either only one value, or a list of them, one item per line (which is why quoting is not needed). File paths are relative to the collection file, so in case they're placed somewhere else the path must also point to there (this could be improved in the future).

**Comment by iwubcode** [comment]
First of all, thank you very much.  That fixed the problem.

However, I was personally curious what was happening so I did more testing.  I used this file:

```
collection: MINEEEEEE
extension: foobar
launch: C:/mytest/test.exe "{file.path}"
directories: F:/test/game1 F:/test/game2


game: Dummy game 1
file: F:/test_again/game1/dummy.foobar
developer: Dev1
genre: Test
players: 1
release: 2019-02-26
description: Testing 1,2,3


game: Dummy game 2
file: F:/test_again/game2/dummy 2.foobar
developer: Dev2
genre: Test
players: 1-4
release: 2019-02-26
description:
 Testing again
 .
 4,5,6
```

I also had these file layouts (ignore the silly names):

```
C:\hello-dear
├───ooooga
│       dummy.foobar
│
└───pancakes
    └───with-syrup
            dummy 2.foobar
```

and

```
F:/test
├───game1
│       dummy.foobar
│
└───game2
        dummy 2.foobar
```

It *still* found the files.  My guess is that if it receives an invalid `directories` option it is scanning all the drives (or at least one of them).  That would explain why it took so long when the file format was wrong.

**Comment by mmatyas** [comment]
Turned out to be a Windows issue; when a `directory`  entry didn't exist the system returned the whole "My Computer" for some reason, which caused the long load times and such. This should be fixed now, and also the original issue as well. Could you test if it works correctly for you too?

**Comment by iwubcode** [comment]
@mmatyas - yes, this has fixed the issue!  While the extra logging isn't always say the exact issue, it is also very helpful.  I'm not sure if it's ok but I will go ahead and close the issue.

Thank you very much for all the help.
