### ISSUE TITLE
Bug - flashing screenshot art for steam using the default theme

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-frontend#384]
While I eventually plan on using my own theme, it seems the built in theme will show a games screenshot for a split second (when selecting) and then it will disappear.  The oddest part is this doesn't seem to happen with every game.

Tested with the built-in Steam loader using `alpha10-129-g05880d0` and portable-mode (windows 10)

**Comment by iwubcode** [comment]
Hmm, just guessing but if the games are supposed to be part of a 'scroll wheel', maybe they aren't looping properly?  Or possibly a list of 1 screenshot is not working?

**Comment by mmatyas** [comment]
Steam uses video codecs that aren't available system-wide by default, which usually causes such problems. If you check Pegasus' log file, you might also see DirectShow/DirectPlay errors there as well. Installing the [necessary codecs](http://pegasus-frontend.org/docs/user-guide/meta-sources/#steam) should fix this issue (unless you see something else being wrong in the log of course).

**Comment by iwubcode** [comment]
Thank you!
