### ISSUE TITLE
Add Arch Linux installation instructions

### ISSUE THREAD

**Issue by severinkaderli** [mmatyas/pegasus-frontend#385]
Hello

I created a package for this project on the [Arch User Repository](https://aur.archlinux.org/packages/pegasus-fe-git/). It may be a good idea to indicate this installation possibility for Arch Linux on the README.md or on the website.

**Comment by mmatyas** [comment]
Thank you! It now is mentioned on the website and in the [documentations](http://pegasus-frontend.org/docs/user-guide/platform-linux/#arch) too.
