### ISSUE TITLE
Bug - holding down joystick on 360 controller does not continue to change selection

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-frontend#389]
When holding down a d-pad direction or the left joystick on my 360 controller, the game selection does not update.  Tapping continuously obviously moves it.  The arrow keys on the keyboard work perfectly (this might be a theme issue?  But it's happened on all the themes I've tested)

**Comment by mmatyas** [comment]
Yes, there is an issue that gamepads don't have the same "key repeating" like keyboards. This will be fixed eventually (the gamepad handling as a whole could see some updates).

Related: #328 and issues labeled `gamepad`.

**Comment by mmatyas** [comment]
Ok, this should be fixed now.
