### ISSUE TITLE
Using folder names

### ISSUE THREAD

**Issue by Kupo91** [mmatyas/pegasus-frontend#397]
Hi,
could you maybe implement an option for using the names of the folders which include the rom files instead of the names of the rom files itself?
Because I am used to put all my games in subfolders. The folders have the actual game names and the rom names often include tags. Furthermore in some cases I can't even rename the rom files because the games wouldn't start then. The easyrpg player for example  (I'm using the easyrpg libretro core) always load the RPG_RT file of a game. Thats an issue because I can't have more than one artwork in the assets folder with the same name.

**Comment by mmatyas** [comment]
Hi, yes, I do plan to add support for that in the near future (related: #391).

**Comment by mmatyas** [comment]
Added support for this in the latest version; feel free to report if something doesn't work!

**Comment by Kupo91** [comment]
Sorry obviously I'm blind. Where do I find this option to use folder/game names?

**Comment by Kupo91** [comment]
It still shows the file names instead of folder names. Maybe because I imported it from Emulationstation?

**Comment by mmatyas** [comment]
Ah sorry it seems I've misread the original issue... (late night programming).

The ES compatibility will always try to match how ES reads the gamelist XMLs: it will launch the file defined in `<path>` and will give it the name in `<name>`. Since the goal is compatibility, that's something I'd rather not change.

However, you can use Pegasus' own metadata format instead. For example, assuming this directory structure:

```
My RPG Games/
|-- metadata.txt
|-- First Game/
|   |-- easyrpg-player
|   `-- ...
|-- Second Game/
|   |-- easyrpg-player
|   `-- ...
`-- media/
    |-- First Game/
    |   `-- box_front.png
    `-- Second Game/
        `-- box_front.png
```

, you could write a `metadata.txt` like this:

```make
collection: EasyRPG Games
extension: easyrpg-player
launch: {file.path}

game: First Game
file: First Game/easyrpg-player
description: Some cool game

game: Second Game
file: Second Game/easyrpg-player
description: Another cool game

# etc.
```

(If I remember correctly, `easyrpg-player` is what you use to launch EasyRPG, but feel free to tweak the metafile if I'm wrong. You can also find more detailed docs [here](http://pegasus-frontend.org/docs/user-guide/meta-files/)).

**Comment by Kupo91** [comment]
Thanks for your explanation. Can I change the structure of "media"?
I also use Rom Collection Browser as frontend and my folder structure looks like this:
- Games
  - RPG-Maker
    - Roms
      - Vampires Dawn
        - RPG_RT.ini
      - Vampires Dawn II
        - RPG_RT.ini
      - Unterwegs in Düsterburg
        - RPG_RT.ini
      - ...
    - Artworks
      - boxfront
        - Vampires Dawn.png
        - Vampires Dawn II.png
        - Unterwegs in Düsterburg.png
      - clearlogo
      - fanart
      - screenshot
      - ...
    - Savegames
  - Playstation 1
  - Gameboy Advance
  - SNES
  - N64
  - Wii
  - ...

So currently my media structure is media art -> game.png, and in pegasus its game -> media art.png
Would be nice if I could change this, so I could use both frontends

**Comment by mmatyas** [comment]
The media dir structure is fixed, but it sound like your Artworks directory is similar to what Skraper uses (or maybe you actually used that?), in which case there could be support added for that.

Alternatively, you can also define the assets manually in the metadata file (see [here](http://pegasus-frontend.org/docs/user-guide/meta-assets/)).

**Comment by mmatyas** [comment]
I suppose this can be closed now.
