### ISSUE TITLE
Certain SVGs are rendered black

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend#398]
See mmatyas/pegasus-theme-es2-simple#5. Maybe [QTBUG-58326](https://bugreports.qt.io/browse/QTBUG-58326)?

**Comment by iwubcode** [comment]
The bug mentioned was closed, so I guess we just need an update of the Qt version to pick it up?

**Comment by mmatyas** [comment]
Hopefully yes, but would need to test again with it on Windows. If it does work, I plan to update to Qt 5.12.3 when it comes out in about 2 weeks, so this will get fixed then too.

**Comment by fastpop72** [comment]
Any news about this bug? I have the "arcade" svg logo in total black!

**Comment by mmatyas** [comment]
The new Qt version just came out today a few hours ago, I think I can do some tests builds on the weekend.

**Comment by mmatyas** [comment]
Turns out this isn't really a bug. In the SVG format there are two ways to set the fill color:

- Using `fill`:

```svg
<path d="..." fill="#8C8C8C"/>
```

- Using CSS `style`:

```svg
<path d="..." style="fill:#8C8C8C;"/>
```

 Qt supports a mobile-friendly subset of the SVG format ("SVG Tiny"), where you can only use the first option. On the other hand many vector editors target web browsers primarily and use the second method, which however may cause black output depending on the application.

Luckily, there is a way to convert from the second method to the first using Inkscape (and possibly other tools too). Open the SVG in Inkscape, then *File -> Save As*. Select *Optimized SVG* as the output format, and press *Save*. A small window will come up where you can set the optimizations. Make sure *Convert CSS attributes to XML attributes* is turned on (the rest doesn't matter) and press *OK*. The resulting file should work properly in Pegasus.

![svgsave](https://user-images.githubusercontent.com/4354863/56597693-49bb9800-65f3-11e9-955b-ecf63e5cf7c5.png)

**Comment by fastpop72** [comment]
Thanks!! I'll give it a try now!
