### ISSUE TITLE
Feature Request - shifting between collections should clamp to the end of the game list

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-frontend#409]
If you're on a collection with a lot of games, then you switch to a collection with a few games, your cursor will be on nothing.  It'd be a nice added touch to clamp whatever index you are using to the game list size.

(tested on default theme)

**Comment by 5schatten** [comment]
Basically it doesn't matter if you a lot of games or not. If you switch between two collections and the cursor is at a position beyond the last game it's not visible anymore. So either store the last postion for each collection or jump to the first game if none is available.

I guess this should be a proper behaviour?

**Comment by mmatyas** [comment]
Yes, this used to work fine, but then broke when I re-added the filtering support. Will get fixed.

**Comment by mmatyas** [comment]
Ok, this should be fixed now in the latest release.
