### ISSUE TITLE
Segmentation Fault - Raspberry Pi 0W

### ISSUE THREAD

**Issue by withgallantry** [mmatyas/pegasus-frontend#444]
Hi,
I'm getting a segmentation fault on a fresh install of RetroPi.

RetroPie-Setup version: 4.4 (cda9ffcb)
System: Linux retropie 4.14.30+ #1102 Mon Mar 26 16:20:05 BST 2018 armv6l GNU/Linux

This happens when using the experimental install on RetroPi and when downloading the binary manually.

**Comment by mmatyas** [comment]
Thanks, managed to reproduce it, seems to be either a configuration issue or (more likely) a Qt bug. Will do some more testing later today.

**Comment by withgallantry** [comment]
Thank you for looking into this. I can't wait to get it working again on the Pi Zero.

**Comment by mmatyas** [comment]
After doing several tests with different configurations, it seems this is indeed a Qt bug. I'll still have to do one more build to be 100% sure, but then I'll report the issue to the Qt devs and see how can it be fixed.

It's unfortunate but as a workaround using one of the older stable releases should work fine in the meantime.

**Comment by withgallantry** [comment]
Thanks for investigating this. I'll use an older stable release for now.

**Comment by mmatyas** [comment]
Ok this should be fixed now (tested on Stretch). The problem was caused by the compiler actually, which generated incorrect code for the Pi 1/Zero. Using a different one fixed the issue.
