### ISSUE TITLE
Nvidia shield external HDD

### ISSUE THREAD

**Issue by fiqabumm** [mmatyas/pegasus-frontend#445]
First of all I am a real noob. I love the look of the front end so I said I'll try it out. When I launch it it only shows me games and apps that are stored on the shield. But all my ROMs are stored in my external drive and I have no clue how to tell Pegasus to go look for the ROMs folder.

**Comment by mmatyas** [comment]
Hi, support for external storages have been added just recently, have you tried the latest release yet ([`alpha11-74-g23056ea`](https://pegasus-frontend.org/#dl-block-android))?

**Comment by fiqabumm** [comment]
Yes sorry I tried it last night. Now I can see my HDD drive. Would love a video tutorial online. As I don't know much I can do simple things. I did found a conversion tool for metadata but it is still not working out for me.

**Comment by mmatyas** [comment]
Yes, I do plan to make video tutorials eventually, it's just that I want Pegasus to be in its best form on the screen so I always end up working on bugs instead :)

**Comment by mmatyas** [comment]
I guess this issue is now resolved.
