### ISSUE TITLE
Bug - holding down joystick does not continue to change selection

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-frontend#449]
This is minor but with the latest build, holding down the left thumbstick on a gamepad does not continuously change the selection.  However, after #389 has been fixed the d-pad works perfectly.  Some might try the joystick first instead of the d-pad when moving the cursor.

**Comment by mmatyas** [comment]
Ok, should be fixed now!

**Comment by iwubcode** [comment]
Awesome!  Thank you very much
