### ISSUE TITLE
Improve error reporting

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/pegasus-frontend#45]
On errors,

- [ ] Pegasus should show the error message on the screen
- [x] Pegasus should save it to a log file

**Comment by mmatyas** [comment]
Logging to file is now implemented (#55)

**Comment by mmatyas** [comment]
There's now an error message for themes and lack of games (#97), but the actual errors are still only in the log file.

**Comment by iwubcode** [comment]
Additional error reporting would be useful (toggle?).  There's still a collection of games that is somehow getting dropped.  I'm probably going to crank open the IDE when I get some time.

**Comment by mmatyas** [comment]
Closed by #459.
