### ISSUE TITLE
Asset media not being loaded

### ISSUE THREAD

**Issue by prototypeshogun** [mmatyas/pegasus-frontend#462]
The documentation indicates assets will be loaded from "A file with a recognized name under <directory>/media/<gamename>/".

I have Pegasus/metadata.pegasus.txt containing the following:
collection: All Games
shortname: all
extension: zip

game.zip is located at Pegasus/arcade/game.zip
game.zip is shown as an item in the UI

Media is not loaded despite having tried the following setups:
Pegasus/game/boxFront.png
Pegasus/media/game/boxFront.png
Pegasus/arcade/game/boxFront.png
Pegasus/arcade/media/game/boxFront.png

**Comment by prototypeshogun** [comment]
I am using the stable release for macOS currently on the site today.

**Comment by mmatyas** [comment]
Hi, Pegasus will look for the `media` dir in the same directory as the metadata file, and its contents should match the structure of the metadata file's directory too.

In your case, if the file is at `Pegasus/metadata.pegasus.txt`
and the game at `Pegasus/arcade/game.zip`,
then the media dir will be checked at `Pegasus/media`
and the assets at `Pegasus/media/arcade/game/boxFront.png`.

Does this work for you correctly?

**Comment by prototypeshogun** [comment]
That makes complete sense. And to zero surprise by me that worked perfectly.
