### ISSUE TITLE
Themes are not searched in config folder (as docs read)

### ISSUE THREAD

**Issue by bleuge** [mmatyas/pegasus-frontend#463]
hi, new user here, 
I wanted to make a portable pegasus-fe installation, 
Downloaded it to a folder, downloaded some themes from github, and unpacked them  in the config folders /config/pegasus-theme-es2-simple-master/ (for example, as referenced in https://pegasus-frontend.org/docs/user-guide/config-dirs/) 

Run pegasus-fe, no themes found, run it with --portable, none. 
After some investigation, put them in Themes folder, all are ok now. 
Maybe you want to modify docs, or indicate in some way. 
Thanks! I'll continue to report, it seems fast, logical, etc...

**Comment by mmatyas** [comment]
Hi, the theme directories are listed here: https://pegasus-frontend.org/docs/user-guide/installing-themes/, is this what you were looking for? Hmm perhaps I could improve it a bit...

**Comment by bleuge** [comment]
Thanks, it's normal to have docs a bit behind code :D Just thought I was nice to fix it for other users, thanks!
