### ISSUE TITLE
Allow --portable to read es_systems.cfg

### ISSUE THREAD

**Issue by dschu012** [mmatyas/pegasus-frontend#465]
On Windows 10 I'm trying to get Pegasus to read a gamelist.xml generated from https://www.skraper.net/. In order to do so it looks like Pegasus looks for `/.emulationstation/es_systems.cfg`. It'd be cool if when passing `--portable` that it would look for `./config/es_systems.cfg` so the gamelist.xml could be used without any kind of conversion.

**Comment by mmatyas** [comment]
By default Pegasus looks for ES files under `C:/Users/[username]/AppData/.emulationstation`; however you can override the `C:/Users/[username]/AppData/` path by setting the `HOME` environment variable, which can also be used to bundle ES2 with a portable Pegasus.

You could do such setup by placing `.emulationstation` next to `pegasus-fe.exe`, and writing a Batch script like this:

```batch
set HOME=%~dp0
pegasus-fe.exe --portable
```

**Comment by dschu012** [comment]
That worked great. Thanks.
