### ISSUE TITLE
Gradient banding on RPi 3b+

### ISSUE THREAD

**Issue by asdfgasfhsn** [mmatyas/pegasus-frontend#467]
While working on a theme I found that on RPi (3b+ to be exact) that gradients suffer from a banding effect that is not visible when testing my theme on x86 Linux, Windows or MacOS.

If I have `QT_QPA_EGLFS_FORCE888=1` in my environment before starting pegasus-fe the banding issue goes away.

This [forum post](https://www.raspberrypi.org/forums/viewtopic.php?t=17067) covers background information and was where I sourced the environment variable.

I can provide screenshots if required.

**Comment by mmatyas** [comment]
Thanks, will try it! I did notice the banding too, but it also seemed to happen with all the other EGL-based programs I have so wasn't sure about the cause of it. Will experiment with these settings next week.

**Comment by mmatyas** [comment]
Took some time but finally I could try it on a Pi, and looks very nice! I'm not sure if this also happens on other kind of devices, like Odroid, so for now I've sent a patch to the RetroPie repo, and I'll also add a note about this to the documentation. Thanks again!

**Comment by asdfgasfhsn** [comment]
The issue seemed to be with the way QT determined bit depth so this fix may apply to a variety of devices. Thanks for looking in to this.
