### ISSUE TITLE
Gamepad is unresponsive and unrecognized.

### ISSUE THREAD

**Issue by bgillman22** [mmatyas/pegasus-frontend#469]
I am new to emulation frontends and started with EmulationStation, which was a little intimidating. So, I started Pegasus (windows PC) and was pleasantly surprised at the ease. After updating the metadata files, I had a great new frontend. I turned on my Mocute bluetooth controller, which has worked on anything I have thrown at it so far (android and PC) but it had no menu navigation, nor was it recognized in the 'Change game layout' menu. The controller worked in EmulationStation but I didn't like the complexity. The only reason I am posting is because I didn't see any documentation on the supported devices. Once again, love the application...

**Comment by mmatyas** [comment]
Hi, yes the gamepad support is a bit basic at the moment, unfortunately, but improving that part is planned in the future. Is this a Mocute 050 v3.0 controller? Does it work in web browsers, for example [here](https://html5gamepad.com/)? Does it work on Android with the Android release of Pegasus?

**Comment by bgillman22** [comment]
Hey! It is a Mocute 054 but I'm not sure of the version. Yes, it works on
the HTML5 tester and I have used it in Android but I haven't used it on the
Pegasus android build.

**Comment by bleuge** [comment]
Same here with 8bitdo SF30 pro, via BT, it works with games and get recognized in my W10, all 4 variants are accepted by W10 BT stack (as you can pair the 8bitdo in 4 different ways, Xbox, Dpad, switch, macos), but it seems Pegasus can't see it. Also Retroarch detects it in each of the 4 ways.
Any way I can help debug this? Thanks!

**Comment by mmatyas** [comment]
Thanks, I have an idea for improving gamepad support, just haven't had the time yet to implement it :) As soon as it's done though it should support 8bitdo (and likely Mocute too), so that'd be something to test.

**Comment by magadan** [comment]
Gamepad on ANDROID TVBOX  bug.

Hello, Im using cheap USB gamepads from china. It woking OK on Mame4droid, retroarch and the android operating system itselfs. But on Pegasus front end only directional is working i can navigate on caalog but not choose a game... I tried to remap key on the Layout Manager but it dont recognize when i choose a new button to accept, back, etc...  

I alredy tried stable version and the latest github releases...

OBS: All is working when i used a keyboard.

More info: Android 512 Mb, CPU Rockchip 3022 Android 7.1.2

Any idea?

**Comment by bleuge** [comment]
@mmatyas : if you need testing with joypads, I can test and report I have 1 8bitdo sn30pro, and old generic bt one (with analogs and triggers) and many wired ones.

**Comment by mmatyas** [comment]
Thanks, I think I'll be able to add some improvements to the gamepad handling next week, testing that would be great. Will update this issue when it's available.

**Comment by mmatyas** [comment]
There have been improvements to the gamepad handling in the past weeks, I'd be interested in how well it works with your controllers. These changes are available only in the Linux and Windows releases at the moment.

**Comment by bgillman22** [comment]
Sorry, still not working for me with the mocute bluetooth controllers.

**Comment by mmatyas** [comment]
Hm could you post the log file? It should be at `C:/Users/[username]/AppData/Local/pegasus-frontend/lastrun.log`

**Comment by bgillman22** [comment]
2019-09-03T22:42:49 [i] Program settings loaded
2019-09-03T22:42:49 [i] Pegasus alpha11 (2019-03-06)
2019-09-03T22:42:49 [i] Running on Windows 7 SP 1 (6.1) (x86_64, windows)
2019-09-03T22:42:49 [i] Found locale `de`
2019-09-03T22:42:49 [i] Found locale `en`
2019-09-03T22:42:49 [i] Found locale `es`
2019-09-03T22:42:49 [i] Found locale `fr`
2019-09-03T22:42:49 [i] Found locale `hu`
2019-09-03T22:42:49 [i] Found locale `pt-BR`
2019-09-03T22:42:49 [i] Found locale `ru`
2019-09-03T22:42:49 [i] Locale set to `en`
2019-09-03T22:42:49 [i] Found theme 'Pegasus Grid'
(`:/themes/pegasus-theme-grid/`)
2019-09-03T22:42:49 [i] Theme set to 'Pegasus Grid'
(`:/themes/pegasus-theme-grid/`)
2019-09-03T22:42:52 [i] Steam: no installation found
2019-09-03T22:42:52 [i] GOG: 0 games found
2019-09-03T22:42:52 [i] ES2: found
`C:/Users/brian/.emulationstation/es_systems.cfg`
2019-09-03T22:42:53 [i] Games found in 773ms
2019-09-03T22:42:53 [i] ES2: found
`C:/Users/brian/.emulationstation/gamelists/genesis/gamelist.xml`
2019-09-03T22:42:53 [i] ES2: found
`C:/Users/brian/.emulationstation/gamelists/snes/gamelist.xml`
2019-09-03T22:42:53 [i] ES2: found
`C:/Users/brian/.emulationstation/gamelists/nes/gamelist.xml`
2019-09-03T22:42:54 [i] ES2: found
`C:/Users/brian/.emulationstation/gamelists/mame/gamelist.xml`
2019-09-03T22:42:54 [i] ES2: found
`C:/Users/brian/.emulationstation/gamelists/arcade/gamelist.xml`
2019-09-03T22:42:54 [i] ES2: found
`C:/Users/brian/.emulationstation/gamelists/ps2/gamelist.xml`
2019-09-03T22:42:54 [i] ES2: found
`C:/Users/brian/.emulationstation/gamelists/pc/gamelist.xml`
2019-09-03T22:42:54 [i] ES2: found
`C:/Users/brian/.emulationstation/gamelists/n64/gamelist.xml`
2019-09-03T22:42:54 [i] Skraper: Looking for assets...
2019-09-03T22:42:54 [i] Skraper: 0 assets found
2019-09-03T22:42:54 [i] Assets and metadata found in 661ms
2019-09-03T22:42:54 [i] 658 games found
2019-09-03T22:42:54 [w]
qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:73:5: QML
Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/ps2.svg
2019-09-03T22:43:55 [i] Closing Pegasus, goodbye!

**Comment by mmatyas** [comment]
> `2019-09-03T22:42:49 [i] Pegasus alpha11 (2019-03-06)`

It seems like your version is not particularly up to date?

**Comment by bgillman22** [comment]
Oops, your right. I'll update and let you know.

**Comment by bgillman22** [comment]
Working!!! Great job!

**Comment by mmatyas** [comment]
So the gamepad handling improvements are now available for most platforms except Android/Android TV. Is there someone who can test controllers on these devices?

**Comment by nwildner** [comment]
Hi @mmatyas 

Don't know if this relates but, when using a Xbox 360 USB controller, all Axis/Pads are mapped but not the buttons themselves( A,B,X,Y,triggers,start,select,home). I can navigate through the "Android" section of Pegasus but cant further configure cause there are no buttons available.

Anything i could help on investigating this issue(or maybe, open a new issue) ?

**Comment by mmatyas** [comment]
@nwildner if I remember correctly Xbox+Android used to work, but I think I'll be able to test it again tomorrow or next week.

**Comment by mmatyas** [comment]
Ok, managed to get some controllers for testing Android, I'll list the results for the record (tested on an Android 8.0 tablet):

- Xbox One Wireless controller: works without problems
- Logitech F310, Xinput mode: doesn't work at all, not in Pegasus nor in other apps (including RetroArch), and it's not recognized as a gamepad
- Logitech F310, Dinput mode: works without problems
- Cheap Chinese USB SNES gamepad: the dpad works, but none of the buttons record as Accept, thus the layout can't be remapped. The buttons don't work in other apps either and the device is not recognized as a gamepad. It doesn't work at all in RetroArch, not even the dpad.

Now, I can only support gamepads that the Android system itself supports properly. There's this [gamepad tester site](https://html5gamepad.com/), if you open it on Android and the gamepad works there (with the gamepad name "android"), I think it should also work in Pegasus. If you all could try it, I'd be interested in the result you get there.

**Comment by mmatyas** [comment]
Anyone?

**Comment by bgillman22** [comment]
I tested with a wireless (non-bluetooth) x-box controller and the Mocute bluetooth controller and it worked great with both controllers. Great work!

**Comment by bgillman22** [comment]
I would consider this particular issue closed but since there were others who may be testing, I will leave it up to mmatyas to close. Thanks again.

**Comment by mmatyas** [comment]
Well it's been a while so I think I'll just close this for now. Feel free to report any further issues!
