### ISSUE TITLE
Pegasus + Retroarch 64 bit Android

### ISSUE THREAD

**Issue by RexBorova** [mmatyas/pegasus-frontend#476]
Was just curious if Pegasus supports Retroarch 64 bit. I was trying to revise some of the parameters to see if I could launch RA 64 bit with pegasus, but it either launches 32bit RA for me or just goes back to Pegasus.

**Comment by spektor56** [comment]
Yes, this is how i use it.  Here are my parameters:

launch: am start
 --user 0
 -n com.retroarch.aarch64/com.retroarch.browser.retroactivity.RetroActivityFuture
 -e ROM "{file.path}"
 -e LIBRETRO /data/data/com.retroarch.aarch64/cores/fceumm_libretro_android.so
 -e CONFIGFILE /storage/emulated/0/Android/data/com.retroarch.aarch64/files/retroarch.cfg
 -e IME com.android.inputmethod.latin/.LatinIME
 -e DATADIR /data/data/com.retroarch.aarch64
 -e APK /data/app/com.retroarch.aarch64-Lw-HOvybuHeHxQbE451e4g==/base.apk
 -e SDCARD /storage/emulated/0
 -e DOWNLOADS /storage/emulated/0/Download
 -e SCREENSHOTS /storage/emulated/0/Pictures
 -e EXTERNAL /storage/emulated/0/Android/data/com.retroarch.aarch64/files
 --activity-clear-top

**Comment by RexBorova** [comment]
Thanks a bunch man. I'll compare your parameters with mine and give it a shot.
