### ISSUE TITLE
Pegasus turns off screen after inactivity?

### ISSUE THREAD

**Issue by fastpop72** [mmatyas/pegasus-frontend#477]
I have a little problem with my bartop system, it's a PC with debian stretch and retropie and i'm using Pegasus.

During installation i added some "xset" commands to turn off screen blanking because i need to have my screen always ON.

Everything works OK during X11 sessions, the commands i use are:

xset s off
xset s noblank
xset -dpms

But when i start Pegasus front-end these settings are completely ignored and after some minutes of inactivity my Pegasus turns off my monitor (i have to push any key to turn on).

It's a normal behaviour for Pegasus? Can i turn off the inactivity timer?

Thanks.

**Comment by mmatyas** [comment]
Hi, there's no built-in inactivity timer in Pegasus, so not sure what could cause this. Does it happen with other frontends or emulators? I wonder if there's a way to disable screensavers on a system level, other than xset.

**Comment by fastpop72** [comment]
> Hi, there's no built-in inactivity timer in Pegasus, so not sure what could cause this. Does it happen with other frontends or emulators? I wonder if there's a way to disable screensavers on a system level, other than xset.

Thanks for claryfing this! I will investigate my problem elsewhere...

PS: I have a segmentation fault error after the "exit Pegasus" option, how can i trace it? Can i run pegasus with a log report?

**Comment by mmatyas** [comment]
> PS: I have a segmentation fault error after the "exit Pegasus" option, how can i trace it? Can i run pegasus with a log report?

Yes, that seems to be a bug related to Qt, see at #458. Actually I was just about to update the Qt versions, hopefully that will fix it too.

**Comment by fastpop72** [comment]
> Hi, there's no built-in inactivity timer in Pegasus, so not sure what could cause this. Does it happen with other frontends or emulators? I wonder if there's a way to disable screensavers on a system level, other than xset.

I found my issue, it's a retroarch problem.

If the "Suspend Screensaver" option is set to TRUE when i exit retroarch it sets back my screensaver to ON (and not to "last state").



> Yes, that seems to be a bug related to Qt, see at #458. Actually I was just about to update the Qt versions, hopefully that will fix it too.

Wow thanks!

**Comment by mmatyas** [comment]
Glad to see this got resolved! I'm closing the issue then, but feel free to report if you run into anything else.
