### ISSUE TITLE
Pegasus won't start

### ISSUE THREAD

**Issue by shawnshyguy** [mmatyas/pegasus-frontend#479]
On windows. Whenever I try to start up pegasus, I get the loading bar, it gets about halfway and says "54 games found", and then closes. Happens every time I try to run it.

I'll attach a reference photo, but windows doesn't like capturing the loading bar in the screencap for whatever reason.
![loaading](https://user-images.githubusercontent.com/18062048/61114091-9af25f80-a45d-11e9-9049-b5d80aa95551.png)

**Comment by shawnshyguy** [comment]
Okay, so I tried running the latest version, opposed to the stable version, and seems to be fixed there. Hopefully that means when 12 has a stable release, it'll play nicely as well.

**Comment by mmatyas** [comment]
Hi, do you have any GOG games installed? It might be related to [#464](https://github.com/mmatyas/pegasus-frontend/issues/464#issuecomment-493767717).
