### ISSUE TITLE
Environmental Variables in Windows

### ISSUE THREAD

**Issue by breadcat** [mmatyas/pegasus-frontend#480]
Potentially related to this issue: https://github.com/mmatyas/pegasus-frontend/issues/375

The launch string I was intending to use is:
```
launch: "%appdata%\RetroArch\retroarch.exe" -L "%appdata%\RetroArch\cores\mednafen_psx_libretro.dll" "{file.path}"
```

`%appdata%` when echo'd expands to `C:\Users\Peter\AppData\Roaming`. All the paths exist and work, but when I try to launch a game, nothing happens.

I need to fully expand the paths (to the following) to get the game to launch correctly.
```
launch: "C:\Users\Peter\AppData\Roaming\RetroArch\retroarch.exe" -L "C:\Users\Peter\AppData\Roaming\RetroArch\cores\mednafen_psx_libretro.dll" "{file.path}"
```

**Comment by mmatyas** [comment]
Hi, for env vars you can use this form:

```
{env.VARNAME}
```

in your case that would be `{env.appdata}`. Launch commands aren't passed through other command line environments, which is why `%`s and `$`s and such are left as is.

**Comment by breadcat** [comment]
You're absolutely right, should have checked the documentation a little better! The following line works perfectly:
```
launch: "{env.appdata}\RetroArch\retroarch.exe" -L "{env.appdata}\RetroArch\cores\mednafen_psx_libretro.dll" "{file.path}"
```

Closing ticket.
