### ISSUE TITLE
Significant increase on loading time when adding collections

### ISSUE THREAD

**Issue by guibera** [mmatyas/pegasus-frontend#485]
I had 4 collections, if I add more 4 collections, its double the startup's loading time. Even if the new collections have just one game each.

**Comment by mmatyas** [comment]
Hi, could you share some example files for which this issue happens?

**Comment by guibera** [comment]
Hi, I tried with the simplest collections.txt as possible to eliminate any complex issue, I tested with these two, work with any games: 

1. First file, opened in 3 seconds:
```
collection: PC All
shortname: .All
file: _installs/Move or Die.url
file: _installs/Terraria.url
file: _installs/Magicka Wizard Wars.url

launch: "{file.path}"

game: Move or Die
file: _installs/Move or Die.url

game: Terraria
file: _installs/Terraria.url

game: Magicka Wizard Wars
file: _installs/Magicka Wizard Wars.url
```

2. Second file, opened in 9 seconds:
```
collection: PC All
shortname: .All
file: _installs/Move or Die.url
file: _installs/Terraria.url
file: _installs/Magicka Wizard Wars.url

launch: "{file.path}"

game: Move or Die
file: _installs/Move or Die.url

game: Terraria
file: _installs/Terraria.url

game: Magicka Wizard Wars
file: _installs/Magicka Wizard Wars.url


collection: PC Example 1
shortname: . Example 1
file: _installs/Move or Die.url

collection: PC Example 2
shortname: .Example 2
file: _installs/Terraria.url

collection: PC Example 3
shortname: .Example 3
file: _installs/Magicka Wizard Wars.url
```

**Comment by mmatyas** [comment]
Thanks! It's interesting loading takes so long for you though, may I ask what platform/device are you using? In case the issue ends up related to that. I'll look through the code meanwhile.

**Comment by guibera** [comment]
Yeah... I thought that this loading time is a bit boring so I made these
test collections.

I'm using on Windows, I'll confirm what is the release version when I get
home, but it was the last one a three weeks ago.

Em seg, 12 de ago de 2019 13:15, Mátyás Mustoha <notifications@github.com>
escreveu:

**Comment by guibera** [comment]
Pegasus alpha11-100-ga1f400c (2019-07-11)
Running on Windows 10 (10.0) (x86_64, windows)

**Comment by mmatyas** [comment]
There have been a few loading time improvements added in the latest version, could you try if it helps with this issue too?

**Comment by j8r** [comment]
Can be closed, the discussion can be continued to https://github.com/mmatyas/pegasus-frontend/issues/839.

**Comment by mmatyas** [comment]
Closing for #839.
