### ISSUE TITLE
Launchbox Integration - No Images when Title Contains a Colon

### ISSUE THREAD

**Issue by ecleese** [mmatyas/pegasus-frontend#499]
Just doing some more testing and noticed that any title that contains a colon ":" will not show any images for that game. Once I changed the title name deleting the colon all images appeared.

**Comment by mmatyas** [comment]
Ok should be fixed now, could you try the latest release?

**Comment by ecleese** [comment]
All good now!

**Comment by mmatyas** [comment]
Great!
