### ISSUE TITLE
Support for alternative databases (e.g. IGDB, RAWG, etc.)

### ISSUE THREAD

**Issue by rogersachan** [mmatyas/pegasus-frontend#501]
This would be useful for more recent games that are not distributed via Steam or GOG.

**Comment by mmatyas** [comment]
Hi, desktop games are either detected when installed through Steam/GOG/etc., or defined manually in metadata files. In the first case, the assets of the particular store are used, eg. Steam games will have the same images as in the Steam store. In the second case, the assets you defined in the metadata file will be used. There's no auto-guessing for the missing assets or information, as those cannot be automatically deduced with 100% accuracy.

It would be possible to make a friendly app though, that would help looking for games on such sites, download data/assets and/or write a metadata file for you. If I see correctly, this is what you'd like to see. This seems to be a bit larger project for Pegasus' current scope however, unfortunately I don't think I'll have the time and energy to create such program at the moment :(
