### ISSUE TITLE
Pegasus won't start on RPI4

### ISSUE THREAD

**Issue by maran** [mmatyas/pegasus-frontend#504]
I tried installing the RPI4 binary (alpha12-34-g834fc53) but I got greeted with a error:

```
$ ./pegasus-fe
Could not find DRM device!
Aborted
```

Anything I can try to work around this?

**Comment by mmatyas** [comment]
Hm it used to work, perhaps there have been some video driver changes? It might require rebuilding Qt or other libs, but I can only work on this next week.

**Comment by maran** [comment]
Sure thing, If I can help you somehow let me know.

**Comment by mmatyas** [comment]
Just to make sure, could you check whether [Alpha 12](https://github.com/mmatyas/pegasus-frontend/releases/download/alpha12/pegasus-fe_alpha12_rpi4-static.zip) also fails on the Pi 4?

**Comment by maran** [comment]
Just to confirm: I extracted `pegasus-fe_alpha12_rpi4-static.zip` and got the same result.

```
pi@raspberrypi:~ $ ./pegasus-fe
Could not find DRM device!
Aborted
```

**Comment by mmatyas** [comment]
Hmm I just updated my Pi (kernel 4.19.58, 20190718) and tried the latest version, but everything seems to be working fine. Is there any setting changed on your Pi that could affect OpenGL? Are you running a Raspbian with desktop/X11, for example? Perhaps the libraries are incorrect, could you post the output of `ldd ./pegasus-fe`?

**Comment by maran** [comment]
I've done a fresh install of Raspian (Full Desktop) (I minimal) and it all works cleanly now. I was probably missing some package or other. Sorry for the false alarm!

**Comment by mmatyas** [comment]
That's good to hear! There was also a [report](https://retropie.org.uk/forum/post/198747) that emulator launching also produces DRM errors, have you noticed something like that?

**Comment by maran** [comment]
Actually I experienced this today while playing more with it. I decided to fake the run to see if it was something to do with the actual emulator but even with it happened.

```
[i] Executing command: [`echo`,`#/home/pi/roms/Romancing SaGa 3.7z`]
[i] Working directory: `/home/pi/roms`
[i] Process 1917 started
[i] ----------------------------------------
#/home/pi/roms/Romancing SaGa 3.7z
[i] ----------------------------------------
[i] The external program has finished cleanly, with exit code 0
[e] Could not queue DRM page flip on screen HDMI1 (Device or resource busy)
[e] Could not queue DRM page flip on screen HDMI1 (Device or resource busy)
[e] Could not queue DRM page flip on screen HDMI1 (Device or resource busy)
[e] Could not queue DRM page flip on screen HDMI1 (Device or resource busy)
... 
```
