### ISSUE TITLE
Multi disc game support for Launchbox integration

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#505]
Multi-discs within Launchbox are called Additional Applications. Examples of the data xml can be found here: https://www.dropbox.com/s/8n9wwqvrqafnc0f/Sony%20Playstation.xml?dl=0 (there's a lot of redundant additional apps here due to Launchbox adding all the videos from my media folder by accident, but look at Final Fantasy VII as a good example).

**Comment by mmatyas** [comment]
Hm I seem to get a 404 for the link.

**Comment by PlayingKarrde** [comment]
Whoops: https://www.dropbox.com/s/2js9wtc0r7w5bvu/Sony%20Playstation.xml?dl=0

**Comment by mmatyas** [comment]
Ok, I've just added support for additional apps, give it a try :)

**Comment by PlayingKarrde** [comment]
I forgot to follow up on this. This works perfectly now thanks!
