### ISSUE TITLE
Can't launch emulators on Mac

### ISSUE THREAD

**Issue by ryanc919** [mmatyas/pegasus-frontend#510]
I can't seem to get Pegasus to successfully launch an emulator. If I'm trying to get to launch bsnes for my SNES games, no matter what I do I get an error message that the file can't be found or I don't have the permission to run it. What exactly should that line look like in the metadata file?

**Comment by mmatyas** [comment]
Hi, on Mac launching looks something like `open <programname> --args <arguments>`. For example:

```make
collection: Super Nintendo Entertainment System
shortname: snes
extensions: 7z, bin, smc, sfc, fig, swc, mgd, zip, bin
launch: open -a bsnes --args {file.path}
```

Does something like this work for you? I'm not a Mac expert unfortunately.

**Comment by ryanc919** [comment]
That worked! Is there a way to force these apps to stay full screen? If I have Pegasus open full screen and then have bsnes open, Pegasus goes down to a smaller window while bsnes does not open at full screen at all. If that isn't possible to do it's no deal breaker.

**Comment by mmatyas** [comment]
In theory, Pegasus should disappear when a program is launched, then reappear when it's finished, with the same window size orfullscreen. Not sure how well this is working on Mac (eg. whether `open` quits as soon as the requested app is launched).

As for bsnes, I wonder if there's some command line flags to control it's behavior? Pegasus itself has no control over what the launched applications do or look like, it can merely launch them with the parameters set in the files.

**Comment by mmatyas** [comment]
I guess the original question got resolved, so closing the issue.
