### ISSUE TITLE
LaunchBox Integration - Filter/Search Support

### ISSUE THREAD

**Issue by ecleese** [mmatyas/pegasus-frontend#511]
Keyboard "F" and Gamepad "Y" keys don't appear to do anything when using LaunchBox as the data source. Can filter and search support be added when integrating LaunchBox?

**Comment by ecleese** [comment]
Update: So I use the GameOS theme and it appears this theme doesn't currently support the filter/search function but the default Pegasus Grid theme works fine. I'm working on my own modifications to the GameOS theme so I may include this feature.

Any chance there's a way to add additional "browse by" filtering based on LaunchBox's categories? For example:

- Date Added
- Developer
- Favorites
- Publisher
- Rating
- Region
- Genre 
- Series
- Star Rating
- Status

**Comment by mmatyas** [comment]
Searching and filtering is also something that theme makers can customize: Pegasus itself provides the tools to do that, but doesn't enforce eg. creating search fields on the UI. It is actually possible to use all the fields listed above, except date added, region, series and status, but collections can also be used for grouping games by these properties.

**Comment by mmatyas** [comment]
Ah yes, as for the built-in theme, searching/filtering got a bit broken after one of the updates, hopefully I can update that too sometime.

**Comment by mmatyas** [comment]
The filtering got fixed since then in the main theme, so I guess this can be closed now.
