### ISSUE TITLE
LINUX Pegasus is crashing when Subsystem has another Exit Code == 0

### ISSUE THREAD

**Issue by Mernst1** [mmatyas/pegasus-frontend#523]
Linux
When for example I start Dreamcast (Redream) and I kill the process manually through kill -KILL *PID* in the Terminal, Pegasus will also crashing.

This is for all Emulators that doesnt give exit code 0.
I believe if some emulator is internaly crashing, the same behavor can be expectet.

Is it possible to ignore the exit codes from the other systems.
Same as Emulationstaton is doing it.

By the way great work so far.

**Comment by mmatyas** [comment]
This was a bug, thanks! Should work now in the latest version.

**Comment by Mernst1** [comment]
awesome work, you getting a donation.
