### ISSUE TITLE
LaunchBox Integration - Only specific platforms are imported

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#527]
Adding new platforms (for example Wii U or Windows) to LaunchBox, or modifying the name of one that works, will cause Pegasus to not recognize it. There is no information in the lastrun.log to suggest anything is broken.

**Comment by mmatyas** [comment]
Could you upload `Data/Emulators.xml` and the XML files under `Data/Platforms/`? I might need to improve the searching logic a bit.

**Comment by PlayingKarrde** [comment]
[Sure here you gol](https://www.dropbox.com/sh/tz94g5n4vu3377l/AABgBhZZymP5-FOCQDfvuKhPa?dl=0)

**Comment by mmatyas** [comment]
Thanks, yeah I see now, I naively assumed that platform names match the file names, but that doesn't seem to be the case. I wonder where are such renaming settings are stored, perhaps in `Data/Platforms.xml` or `Data/Parents.xml`? Could you upload these two as well? Or just zip the whole `Data` directory to be sure.

**Comment by PlayingKarrde** [comment]
[Data.7z](https://www.dropbox.com/s/o8pcs4mzog300xt/Data.7z?dl=0)

**Comment by mmatyas** [comment]
Well I ended up rewriting pretty much the whole LB support, but it should be accurate now. Couldn't test it properly yet, but here's my current build which may or may not work: [pegasus-fe_alpha13-8-g5b8d114_win-mingw-static.zip](https://github.com/mmatyas/pegasus-frontend/files/3736223/pegasus-fe_alpha13-8-g5b8d114_win-mingw-static.zip). I'd be interested in the full log if you try it out.

**Comment by PlayingKarrde** [comment]
Oh wow thanks for doing all that. I just tested it and it seems (in the few minutes I spent) to work perfectly (at least in terms of loading games into the frontend).

[Here's the pastebin](https://pastebin.com/FwiKxSiT). The type errors are obviously on me (btw if there's an obvious thing I'm missing when doing checks for data to avoid these errors please let me know :) )

**Comment by mmatyas** [comment]
Phew, okay then, things seem to look fine, I think I can finish this about tomorrow. The `game refers to a missing or invalid emulator platform` are my fault, other than that I see missing games and CDs, and a few missing asset; are these warnings correct? Also does/did the loading always take 11 seconds?

**Comment by PlayingKarrde** [comment]
Oh I was more referring to the `TypeError: Type error` errors. 

I would say loading usually takes between 15-20 seconds. Sometimes longer. Does that seem long or short to you?

**Comment by mmatyas** [comment]
Yeah I just mean that the emulator platform warnings are also unrelated :)

Well, I've parsed the whole Data.7z above in 658ms with an unoptimized build... though I admit the game files didn't exist for me on Linux, which might affect things slightly.

**Comment by PlayingKarrde** [comment]
Running on systems other than Windows performance in general is just much better. Including loading.

**Comment by PlayingKarrde** [comment]
This may require a separate issue but when I try and run the newly created Windows games (which are essentially just shortcut links I get this error:

> 2019-10-16T16:05:53 [i] Executing command: [`H:\GOG.com\Return of the Obra Dinn\Launch Return of the Obra Dinn.lnk`]
> 2019-10-16T16:05:53 [i] Working directory: `G:/Dropbox/GOG.com/Return of the Obra Dinn`
> 2019-10-16T16:05:53 [w] Could not launch `H:/GOG.com/Return of the Obra Dinn/Launch Return of the Obra Dinn.lnk`. Either the program is missing, or you don't have the permission to run it.

Copy and pasting that link into the run command makes it run fine. Running it from launchbox also runs fine. Pegasus also shuts down at this point with no goodbye message.

**Comment by mmatyas** [comment]
Shortcuts seem to be a bit special, will need to be looked into more. #471 also mentions a similar issue.

**Comment by PlayingKarrde** [comment]
K thanks, I won't clog up this thread with something unrelated then :)
