### ISSUE TITLE
keyboard doesn't work in terminal after exiting pegasus rpi 4

### ISSUE THREAD

**Issue by HerbFargus** [mmatyas/pegasus-frontend#528]
Just posting an official ticket to log our previous discussion. 

Using build https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1/rpi4teszt2.tar.gz

Launching and exiting pegasus is fine, but if you launch a game and exit pegasus the keyboard stops working in the terminal. However if you launch via an SSH session it works fine. 

On launch it gives the warning 

```
Setting framebuffer size is only available with DRM atomic API
```

I used the `export QT_QPA_EGLFS_KMS_ATOMIC=1` which turned the error into 

```
Framebuffer size format is invalid.
```
 
This is likely a pi 4 specific driver issue

**Comment by mmatyas** [comment]
Made a new test build, keyboard should now work even after leaving Pegasus: https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1/pegasus-fe_alpha12-108-gee13ab8_rpi4-static__test.zip

**Comment by HerbFargus** [comment]
Can confirm this is resolved, thanks!
