### ISSUE TITLE
Central Directory for metadata

### ISSUE THREAD

**Issue by Sixdd6** [mmatyas/pegasus-frontend#529]
So I'm thinking it's a bit odd to have to link metadata files from locations scattered across different directories. My thought is that it would be more convenient to use for example: nes.meta, genesis.meta, etc..  in a centrally located directory, maybe under the user directory and have Pegasus autoload whatever .meta files are in there rather than having to add each file individually. I'm no programmer so I don't know if that's a pain to do but I think it'd be nicer this way. Just a suggestion.

**Comment by mmatyas** [comment]
Actually there's support for that too, check the "Global config files" part at https://pegasus-frontend.org/docs/user-guide/meta-files/ (green box). You can place any files with `.metadata.txt` extension under `~/.config/pegasus-frontend/metadata`.
