### ISSUE TITLE
Help with Metadata

### ISSUE THREAD

**Issue by Sixdd6** [mmatyas/pegasus-frontend#530]
So I'm not sure what I did wrong but this was generated with the metadata editor and it doesn't populate anything.

```
collection: Nintendo NES
shortname: NES
directory: /home/samm/Storage/Emulation/Games/Nintendo - Nintendo Entertainment System/
extension: .nes
launch: retroarch -L "bnes.so" {file.path}
```
I've put it in the directory that the roms are in and verified the extension and folder structure but it just doesn't want to work. Also I made another metadata with the editor for a different console and that one works fine.

**Comment by mmatyas** [comment]
Hm could you try removing the dot from `.nes` at `extension`? If that doesn't help, I'd be interested if you see anything from the log (`~/.config/pegasus-frontend/lastrun.log`), or a list of games under.

**Comment by Sixdd6** [comment]
Oh of course! I can't believe I missed that. I'll try that now

**Comment by Sixdd6** [comment]
Works a dream now, thanks for the help :smile:
