### ISSUE TITLE
Launchbox Support

### ISSUE THREAD

**Issue by Sixdd6** [mmatyas/pegasus-frontend#533]
I've just recently moved from Windows to Linux (and love my newfound freedom) but I have a fairly large collection of games in a Launchbox setup. I'd like to know if there is some automated way to import the xml from launchbox into Pegasus. I'm asking here because I've seen the other issues mentioning Launchbox.

**Comment by mmatyas** [comment]
Someone wrote an export plugin (https://github.com/spektor56/PegasusExportPlugin), though personally I haven't tried it yet.

**Comment by Sixdd6** [comment]
Only problem with that is it requires you to actually be able to run the plugin from within Launchbox, which I obviously can't do since it is windows only.

**Comment by mmatyas** [comment]
I also cannot add built-in support on Linux for a program that is Windows only :) Perhaps a standalone program/script could be written.

**Comment by Sixdd6** [comment]
What I'm looking for really is something that will read the xml of the launchbox data folder and then convert that to something that Pegasus can understand. It wouldn't need to be a perfect conversion since there is a lot in the launchbox xml that could be thrown out Scummvm stuff and dosbox information and such.

**Comment by murlakatamenka** [comment]
Use a virtual machine with Windows to export the data you need. The fastest solution that's almost guaranteed to work.

**Comment by Sixdd6** [comment]
Hadn't thought of that, thanks I'll give it a try.

**Comment by Sixdd6** [comment]
I haven't actually had a chance to try yet due to some computer issues. I've just been doing things the manual way for any games I want to add.

**Comment by mmatyas** [comment]
Closing for now (I assume that worked), feel free to report if you run into any other issues.
