### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by LiamDawe** [mmatyas/pegasus-frontend#537]
Hey, is there an actual changelog anywhere?

**Comment by mmatyas** [comment]
Hi, there is, kind of, but it's a bit scattered at the moment; I usually post weekly updates in the [forum thread](https://retropie.org.uk/forum/topic/9598/announcing-pegasus-frontend/), but for the last few releases they weren't summarized. Actually I think I have some time, I'll go through them and reply as soon as I'm done.

**Comment by mmatyas** [comment]
Just updated some of the [last release's changelogs](https://github.com/mmatyas/pegasus-frontend/releases). I suppose you're mainly interested in the latest release, here it is:

### Alpha 13

- The Raspberry Pi 4 is now properly supported
- Added Korean translation
- Greatly improved gamepad support and compatibility across all platforms
- Greatly improved LaunchBox compatibility
- Added support for reloading the list of games, collection and enabled compatibility modules without restarting Pegasus
- Bugfixes and usability improvements

In addition, I'm also in the middle of making Pegasus available in Flatpak format on FlatHub, it should be online in a few hours (days?).

**Comment by LiamDawe** [comment]
Thanks :)
