### ISSUE TITLE
Setup Matrix room

### ISSUE THREAD

**Issue by PopeRigby** [mmatyas/pegasus-frontend#539]
I know this isn't a Pegasus issue, but I couldn't find another way to get into contact. I think it would be a great idea to setup a [Matrix](https://matrix.org/) room to chat about the project.

**Comment by mmatyas** [comment]
Actually there is a recently launched Discord channel here: https://discord.gg/KTtzP6y, I just haven't got around updating the home page yet.

**Comment by PopeRigby** [comment]
That's cool. I think it would be nice if you setup a bridge between the two with something like [this](https://t2bot.io/discord). Alternatively, you could self-host the [bridge](https://github.com/half-shot/matrix-appservice-discord). I can help you set it up.

**Comment by mmatyas** [comment]
I also like the idea behind Matrix, but on the other hand there have been also people asking especially for Discord. I don't wish to maintain two separate channels, but if you want to run one, I can mention that on the page.

**Comment by PopeRigby** [comment]
If we bridge them, the chats on either side will be mirrored. I can mod on the Matrix side. Do you think we can set up a bridge?

**Comment by mmatyas** [comment]
If I understand correctly, I only need to invite the `t2bot`, give it some permissions, and tell the channel URL on the Matrix side, right? Yes, this could be done.

**Comment by PopeRigby** [comment]
Yep. That's right. I'll join the Discord server so we can set this up.

**Comment by mmatyas** [comment]
Looks like it's working now.

**Comment by Xiretza** [comment]
Sorry to necro this, but is the bridge still running? What matrix room is it connected to?

**Comment by mmatyas** [comment]
Yes, the bridge is still running, and the room should be https://matrix.to/#/#pegasus-general:permaweb.io. No idea if that's still alive though.

**Comment by poperigby** [comment]
Unfortunately no, but nobody else was in there anyway. You or I could setup another one though.

**Comment by Xiretza** [comment]
Sure - I just created [#pegasus:matrix.org](https://matrix.to/#/#pegasus:matrix.org), I don't have discord to do that side of the bot setup though.

**Comment by poperigby** [comment]
If you want to bridge all of the Discord channels, you can make #pegasus:matrix.org a space, and put the other rooms under it. Then I can help you bridge the individual rooms.

**Comment by Xiretza** [comment]
Sounds good, I know https://openrtx.org/ does just that and it seems to work well. The problem is that Discord won't even let me look at the guild without giving them a phone number, so I don't know what channels even exist or what their IDs are :/
