### ISSUE TITLE
Add Lutris Support

### ISSUE THREAD

**Issue by Fuzen-py** [mmatyas/pegasus-frontend#540]
With lutris becoming a common way of installing games on Linux, it would be nice to see support added for this.

**Comment by mmatyas** [comment]
I agree, would like to add support for it eventually if possible.

**Comment by mmatyas** [comment]
Ok, initial support for Lutris is now available in the latest versions, should work out of the box. I don't have too many games set up like this, so feel free to report any issues you find!
