### ISSUE TITLE
LaunchBox Integration - Loading screen shows 0 games

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#543]
File this one under lowest priority possible, but just wanted to log it as it's a bug I've noticed.

When launchbox is activated, the number of games imported is shown as zero when loading Pegasus. If there are other games from other sources it will show this number but not take into account the number of launchbox games. The lastrun.log does, however, show them as being found.

> 2019-10-13T13:04:13 [i] LaunchBox: finished game searching in 971ms
> 2019-10-13T13:04:13 [w] No games found for collection 'Sega CD', ignored
> 2019-10-13T13:04:13 [i] Game list post-processing took 0ms
> 2019-10-13T13:04:13 [i] Metafiles: finished asset searching in 1ms
> 2019-10-13T13:04:13 [i] Games found in 972ms
> 2019-10-13T13:04:13 [i] Assets and metadata found in 1ms
> 2019-10-13T13:04:13 [i] 920 games found

**Comment by LondoJI** [comment]
What I can see is that Pegasus can read and show, while progress bar appears during startup, how many games are being detected/loaded. In the case of LaunchBox, it goes from "0" to "100%". 
In my case, I have LaunchBox as my only source, no games loaded from any other, or directly for Pegasus, then you could imagine that when Pegasus starts, progress bar is kept in "0" for so long time until it loads everything from LaunchBox. In that moment progressbar jumps to 100% and in just a second, grid appears. I have to admit that at the beginning I thought that Pegasus wasn't working and was frozen. So, yes... could be an "ugly" kind of bug. :P

**Comment by mmatyas** [comment]
I had a little time and improved this a bit, should be fairly accurate now.

**Comment by mmatyas** [comment]
The loading bar should actually work now in the recent releases. I think this can be closed then.

**Comment by HVR88** [comment]
Bar works for me in Windows. It doesn't display a game count while loading however - is it supposed to?

**Comment by mmatyas** [comment]
> It doesn't display a game count while loading however - is it supposed to?

Yes, the loading bar used to show a game count back in 2019, but it didn't work that well so it only shows the provider name at the moment.
