### ISSUE TITLE
Add ability to theme loading screen

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#544]
Again, not a super high priority but would be great to be able to theme the loading screen also.

**Comment by mmatyas** [comment]
The problem with this is it makes too easy to re-brand Pegasus, which I'd like to avoid.

**Comment by PlayingKarrde** [comment]
Hmm yes you're right here. Will have to think on this some more.

**Comment by mmatyas** [comment]
I think I'll close this for now until further progress.
