### ISSUE TITLE
Updated Android command post RetroArch rename

### ISSUE THREAD

**Issue by prototypeshogun** [mmatyas/pegasus-frontend#548]
I have not been able to use Pegasus on android to launch games with newer versions of RetroArch. I noticed they renamed their app to RetroArch_1.7.9_ra32.apk and RetroArch_1.7.9_aarch64.apk depending on the architecture you choose.

I attempted just replacing all com.retroarch with com.retroarch.ra32 in a config file but it still did not work.

I do not have a rooted android device and was wondering if you could update the documentation for commands given these new names.

**Comment by mmatyas** [comment]
Yes, I've been told there are a few new versions around now. Just checked them this morning, will update the docs with some info soon.

**Comment by mmatyas** [comment]
Ok, documentation updated, you can find it here: https://pegasus-frontend.org/docs/user-guide/platform-android/#retroarch
