### ISSUE TITLE
Sync settings to cloud provider

### ISSUE THREAD

**Issue by PopeRigby** [mmatyas/pegasus-frontend#560]
Having the option to back up your Pegasus settings to something like Nextcloud or Dropbox would be cool.

**Comment by mmatyas** [comment]
I'd prefer to avoid adding cloud provider-specific code, but I could imagine something like an "Open config directory" button. The only problem is that also wouldn't work on certain platforms...

**Comment by PlayingKarrde** [comment]
Why not just run pegasus from your cloud service folder and use the -portable option? That's what I do for this reason.

**Comment by PopeRigby** [comment]
That would take up more space than needed. You only want to sync config files.

**Comment by PlayingKarrde** [comment]
Sure but pegasus is still very small. It's not a huge deal.

**Comment by PopeRigby** [comment]
> Sure but pegasus is still very small. It's not a huge deal.
It could pose a problem as Pegasus grows.

**Comment by mmatyas** [comment]
I think I'll close this for now, as there are no plans at the moment for adding such functionality, and there are possible workarounds for it.
