### ISSUE TITLE
Suppress libpng warnings

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#572]
Would there be a problem in suppressing the libpng warnings? I don't think these warnings cause any problems do they? It's quite annoying having to dig through all the warnings looking for the errors while developing themes. 

If there's a good reason to keep them then no problem, but I don't personally see any visual issues with the images that shout warnings out.

**Comment by mmatyas** [comment]
Well the intention of them is to indicate that your files don't follow the standards properly, which would be useful if you're the one creating the images, but I agree it's not too meaningful for us in the case of scraped assets. I can patch the message out, but that requires rebuilding Qt for all platforms, so I think I'll schedule to do it the next time I try updating it.

**Comment by PlayingKarrde** [comment]
Sounds good no rush, thanks a lot.

**Comment by mmatyas** [comment]
Ok, fixed in the latest release!
