### ISSUE TITLE
Support multiple backgrounds (accessible in themes)

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-frontend#573]
> Pegasus doesn't currently support multiple backgrounds (it only supports multiple screenshots and videos).

See https://github.com/PlayingKarrde/gameOS/issues/91 and https://github.com/mmatyas/pegasus-theme-grid/issues/2

**Comment by mmatyas** [comment]
Well I was thinking about it some more, but I'm not sure I can imagine how this would fit into the UI flow. Like, if I navigate a list of items in a menu (ie. games), then I'd expect it to look the same every time I select the same item. I can imagine there could be use cases in themes where multiple backgrounds could be used (which leads to questions like "why not add multiple value support for every asset", of "which ones should have multiple values and which ones should be single files"), but I'm not sure I want to expect every theme to deal with this.

Even with added support, I'm not sure I'd be comfortable with them changing randomly. Especially in the case of backgrounds, as they are intended to cover a large surface/whole screen, so changing them can be something very visible. Or let's say the image is animated to slide with the game's logo on navigation (kind of like the platform selection screen in EmulationStation). If the background would randomly change in the middle of the animation to something entirely different, that'd be kind of jarring.

If the intention is to show various screenshots of the game in full screen behind the text, that can be done already by just setting the size of the displayed image. I'm also planning to add proper support for accessing the `extra` fields of the metadata files from themes, which could be used for specifying a set of images for this purpose. So at the moment I'm not really sold to the idea of adding multiple entry support to `background`, but I'd be interested in other opinions.

**Comment by iwubcode** [comment]
Thank you again @mmatyas !  Here's just some more thoughts:

* Multiple backgrounds is something I really liked from Launchbox.
* You can say "I'm not sure I want to expect every theme to deal with this" but it's completely optional by the theme developer.  It's not going to fit every theme like you said.  I personally just wanted _one_ theme to have it, since I think it's visually neat.
* Backgrounds are different than screenshots.  My theme might have multiple backgrounds that are say tiled together if they aren't big enough to fill the screen and then visibly show all the screenshots in say a slideshow like fashion when I bring up the game.  So having multiple screenshots is not a good replacement feature.  Screenshot also implies a certain type of image (screenshot of the game) which is not necessarily what a background is (I personally like official wallpapers which is often art)
* `extra` would work but imo feels odd when you already have a field reserved for this purpose.

That being said, thank you again for considering it.  I do see your point about "why not add multiple value support for every asset".  I don't have a good answer.  Personally, I think `videos`, `screenshots`, and `backgrounds` are the more visual impacting assets for a theme, and so it makes sense to support multiples of those (instead of say a box-art).  However, that's just my opinion.  I too am curious how others will feel!

**Comment by mmatyas** [comment]
Ok, this is now supported in the latest version! It's easier to handle when all fields act the same ways so I've made *all* asset fields capable of storing multiple values -- whether there's any meaning in that, I'll leave it to the theme makers. (See also the updates to [the reference docs](https://pegasus-frontend.org/docs/themes/api/#assets).)

**Comment by iwubcode** [comment]
Oh my gosh, thank you so much @mmatyas !  Hopefully it wasn't too much of a pain.  But I'm very excited to try this
