### ISSUE TITLE
Build Error on ArchLinux

### ISSUE THREAD

**Issue by severinkaderli** [mmatyas/pegasus-frontend#576]
I get the following build error when trying to build it on ArchLinux.

```
g++ -c -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -std=gnu++11 -Wall -W -fno-exceptions -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050900 -DQT_NO_CAST_TO_ASCII -DQT_NO_PROCESS_COMBINED_ARGUMENT_START -DGIT_REVISION=\"alpha13-26-g1baa4e5\" -DGIT_DATE=\"2019-10-23\" -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GAMEPAD_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_TESTLIB_LIB -DQT_SQL_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/severin/dev/projects/PKGBUILDS/pegasus-frontend-git/src/pegasus-frontend/build/tests/backend/providers/favorites"' -I/home/severin/dev/projects/PKGBUILDS/pegasus-frontend-git/src/pegasus-frontend/tests/backend/providers/favorites -I. -I/home/severin/dev/projects/PKGBUILDS/pegasus-frontend-git/src/pegasus-frontend/src/backend -I/home/severin/dev/projects/PKGBUILDS/pegasus-frontend-git/src/pegasus-frontend/thirdparty -isystem /usr/include/qt -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtMultimedia -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGamepad -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtTest -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o test_FavoriteDB.o /home/severin/dev/projects/PKGBUILDS/pegasus-frontend-git/src/pegasus-frontend/tests/backend/providers/favorites/test_FavoriteDB.cpp
make[4]: Leaving directory '/home/severin/dev/projects/PKGBUILDS/pegasus-frontend-git/src/pegasus-frontend/build/tests/backend/providers/pegasus'
/usr/bin/ld: test_Collection.o:(.data.rel.ro._ZTI19QQmlObjectListModelIN5model4GameEE[_ZTI19QQmlObjectListModelIN5model4GameEE]+0x10): undefined reference to `typeinfo for QQmlObjectListModelBase'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:70: test_Collection] Error 1
make[4]: Leaving directory '/home/severin/dev/projects/PKGBUILDS/pegasus-frontend-git/src/pegasus-frontend/build/tests/backend/model/collection'
make[3]: *** [Makefile:54: sub-collection-make_first] Error 2
make[3]: *** Waiting for unfinished jobs....
```

**Comment by mmatyas** [comment]
Hm I compared the command to what's run on the CI, but there doesn't seem to be fundamental differences. Perhaps the error is related to something happening earlier in the build process? Have you tried contacting the Arch package maintainer?

**Comment by severinkaderli** [comment]
Actually I am the Arch package maintainer :p. It's strange that it started to throw that error lately. Are there any new dependencies that need to be installed. For reference I use the following commands for building:
```bash
mkdir -p ./build && cd build
qmake .. \
    INSTALL_BINDIR=/usr/bin \
    INSTALL_ICONDIR=/usr/share/pixmaps \
    INSTALL_DESKTOPDIR=/usr/share/applications
make
```

**Comment by mmatyas** [comment]
Ah sorry, should have checked the username :) Based on the snippet this seems like a compilation related issue, something like a new GCC release could produce it I guess?

There are no new requirements, but as an optional dependency [SDL2 (2.0.4 or later) can be used too](https://pegasus-frontend.org/docs/dev/build/#sdl-gamepad-support). There have been also some new installable documentation files (AppStream, License). The full configuration can now look like this:

```
qmake path/to/sources \
    USE_SDL_GAMEPAD=1 \
    INSTALL_BINDIR=/usr/bin \
    INSTALL_DOCDIR=/usr/share/doc/pegasus-frontend \
    INSTALL_ICONDIR=/usr/share/pixmaps \
    INSTALL_DESKTOPDIR=/app/share/applications \
    INSTALL_APPSTREAMDIR=/app/share/metainfo
```

**Comment by kage52124** [comment]
I was having a similar problem. Full system upgrade would lead to Pegasus not loading the GUI. After downgrading the QT5 packages, the GUI loaded again. I also could not re-build with the newer QT5 packages either, resulting in an error that clued me into it being a QT5 problem.

**Comment by jediafr** [comment]
On my Manjaro i also have an error at build : 

/usr/bin/ld: test_Collection.o:(.data.rel.ro._ZTI19QQmlObjectListModelIN5model4GameEE[_ZTI19QQmlObjectListModelIN5model4GameEE]+0x10): undefined reference to `typeinfo for QQmlObjectListModelBase'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:70: test_Collection] Error 1
make: *** [Makefile:73: sub-tests-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by mmatyas** [comment]
I've just pushed an update which should fix the issue (also tested in an Arch Docker image).

**Comment by severinkaderli** [comment]
> I've just pushed an update which should fix the issue (also tested in an Arch Docker image).

Works for me again. Thanks for your effort!

**Comment by kage52124** [comment]
Fixed here as well. Many thanks!

**Comment by jediafr** [comment]
Fixed on my manjaro as well !
Thanks !

**Comment by mmatyas** [comment]
Ok, closing then.
