### ISSUE TITLE
Change video volume

### ISSUE THREAD

**Issue by TiZ-EX1** [mmatyas/pegasus-frontend#577]
Hi there. I'd like to be able to change the volume at which videos play. Personally I want them to be silent but I can see how others might want them to just be quieter.

**Comment by mmatyas** [comment]
Hi, the video volume and mutedness is something that can be customized in themes, so there's no global volume setting for it (by default it should match the system's volume setting). As a workaround, you could either set the per-application volume of Pegasus or you could edit the theme; in the case of the default theme, you can download it from [here](https://github.com/mmatyas/pegasus-theme-grid/tree/master/layer_grid) (see Installation) and [at this line](https://github.com/mmatyas/pegasus-theme-grid/blob/6a9da952e580e7bc809f2f6d26be71eee76c09ae/layer_gameinfo/PanelRight.qml#L155) add either `muted: true` (to fully mute it) or `volume: 0.5` (to reduce its volume).

**Comment by mmatyas** [comment]
I guess this can be closed.
