### ISSUE TITLE
Bug when downloading steam metadata

### ISSUE THREAD

**Issue by rutantan** [mmatyas/pegasus-frontend#582]
I noticed that Pegasus (in Windows) only downloads steam media when connected to the internet by cable connection, if you use wifi, it'll return an error in the log saying it cannot connect to steam.

**Comment by mmatyas** [comment]
Yes, unfortunately this seems to be a Windows specific networking bug in Qt ([QTBUG-68613](https://bugreports.qt.io/browse/QTBUG-68613)). I'll see if it can be fixed with some workarounds.

**Comment by mmatyas** [comment]
The Qt issue got fixed recently and this should be now working in the latest version of Pegasus. Could you check, just to make sure?

**Comment by rutantan** [comment]
Yes, I can confirm it's now working perfectly and it's very fast. Nice build btw.
