### ISSUE TITLE
LaunchBox Integration - Doesn't shows LB's old style media

### ISSUE THREAD

**Issue by GatoSoft-Software** [mmatyas/pegasus-frontend#585]
Hi!  😀
When using LaunchBox integration I found out that Pegasus only shows media using the "new" filename system (ie: "Castlevania-01.jpg"). That means that the old legacy filename system (ie: "Castlevania.jpg") is not detected by Pegasus despite it's still being detected by LaunchBox.
This problem is relatively easy to fix. Just edit the affected game's name changing to a temporary one and then change it back to it's correct name (ie: from "Castlevania" to "1Castlevania" and "Castlevania" once again), forcing LaunchBox to update the filename system of all the game's related media.
That can be a easy fix if your collection only have a couple games. But, just like happens to me, I have _A LOT_ of games with this problem since the beginning of LaunchBox development.
Can it be fixed soon, please?
Thanks in advance.  😊
Greetings from Argentina.  😄

**Comment by mmatyas** [comment]
I see, sure, will take a look if I can add support for it!

**Comment by GatoSoft-Software** [comment]
Thanks you so much for your fast answer and for all your effort.
I'll be watching for this update.  ^_^

**Comment by mmatyas** [comment]
A bit late, but this should now work in the latest version!

**Comment by JDunn82** [comment]
sorry to pop in on old thread but I use launchbox but have the asset media pulled from old hyperspin so my media asset name matches the rom name so none of the asset info is pulling over.
