### ISSUE TITLE
RPI4 Rasbian

### ISSUE THREAD

**Issue by ravensm** [mmatyas/pegasus-frontend#587]
heres the read out

Setting framebuffer size is only available with DRM atomic API
Failed to move cursor on screen HDMI1: -13
Could not set cursor on screen HDMI1: -13
[i] Program settings loaded
[i] Pegasus alpha13-35-g5aa5521-dirty (2019-12-16)
[i] Running on Raspbian GNU/Linux 10 (buster) (arm, eglfs)
[i] Found locale `de`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ko`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Locale set to `en`
[i] Found theme 'Pegasus Grid' (`:/themes/pegasus-theme-grid/`)
[i] Theme set to 'Pegasus Grid' (`:/themes/pegasus-theme-grid/`)
[e] Could not set DRM mode for screen HDMI1 (Permission denied)
[e] Could not queue DRM page flip on screen HDMI1 (Permission denied)
[i] Metafiles:finished game searching in 0ms
[w] EmulationStation: system config file not found
[i] EmulationStation: finished game searching in 0ms
[i] Game list post-processing took 0ms
[i] Metafiles: finished asset searching in 0ms
[i] EmulationStation: finished asset searching in 0ms
[i] Skraper Assets: 0 assets found
[i] Skraper Assets: finished asset searching in 0ms
[e] Could not queue DRM page flip on screen HDMI1 (Permission denied)
[i] Games found in 0ms
[i] Assets and metadata found in 0ms
[i] 0 games found
[e] Could not queue DRM page flip on screen HDMI1 (Permission denied)
[e] Could not queue DRM page flip on screen HDMI1 (Permission denied)
[e] Could not queue DRM page flip on screen HDMI1 (Permission)

Then it will just continue the last lines till i exit it

i went through and made sure i hade all of the requirements, including the optional ones.

**Comment by mmatyas** [comment]
Hi, try running Pegasus with the following env vars set:

```
export QT_QPA_EGLFS_FORCE888=1
export QT_QPA_EGLFS_KMS_ATOMIC=1
```
