### ISSUE TITLE
Cann't add a games directory on the External SDCard

### ISSUE THREAD

**Issue by MephistoSatanDevil** [mmatyas/pegasus-frontend#596]
The open file selector only allows browsing files on the Internal storage.
![Screenshot_2020-02-07-05-39-29](https://user-images.githubusercontent.com/1319061/73982790-eb885780-496f-11ea-888f-e819fd236685.png)

I put lots of game in the External SDCard like this:
![Screenshot_2020-02-07-05-37-59](https://user-images.githubusercontent.com/1319061/73982901-22f70400-4970-11ea-9759-98ac8e8c2618.png)

and have no problem to add these in RetroArch, 
![Screenshot_2020-02-07-05-59-38](https://user-images.githubusercontent.com/1319061/73982975-4cb02b00-4970-11ea-8dbf-2463331c77ab.png)

Would it be possible to add directory on External storage?

**Comment by mmatyas** [comment]
Hm I did add support for that some time ago (#433), which version of Pegasus are you using exactly, and on what kind of device?

**Comment by MephistoSatanDevil** [comment]
> Hm I did add support for that some time ago (#433), which version of Pegasus are you using exactly, and on what kind of device?

Pegasus : version alpha13-44-gdef3e5a (2020-01-28)
device : Onda v919 Air CH Android 5.1
             &
             Honor vision TV
both

**Comment by brunnels** [comment]
I am seeing the same thing with Retroid Pocket 2.

Pegasus alpha14
Log says `Running on Android Marshmallow (6.0) (arm,android)`

Any workaround by manually editing settings.txt maybe?

**Comment by mmatyas** [comment]
This should be now fixed in the latest release, but I've also heard some devices still have issues due to other kind of permission problems (eg. on Retroid). @MephistoSatanDevil could you check if the latest version works for you?

**Comment by MephistoSatanDevil** [comment]
> This should be now fixed in the latest release, but I've also heard some devices still have issues due to other kind of permission problems (eg. on Retroid). @MephistoSatanDevil could you check if the latest version works for you?

Tested.
It works, bug fixed. Both of my TV set & Android pad.
Pegasus : version alphaalpha14-21-g9412daff (2020-09-28)

Thanks.

**Comment by mmatyas** [comment]
Great! @brunnels the situation on the Retroid is slightly different, apparently the secondary storage is not registered as a volume from the point of Android, so it can't be queried automatically either. However, the very latest version should allow you to access the whole filesystem, as long as you have (filesystem level) permission to access the directories. If that doesn't help, you can set manually the directories Pegasus checks -- there's a Retroid-oriented guide for that [here](https://basvroegop.nl/pegasus). Hope this helps!
