### ISSUE TITLE
FR: Arguments for external scripts

### ISSUE THREAD

**Issue by JeffersonBledsoe** [mmatyas/pegasus-frontend#597]
My use case is being able to pass on the game that was launched to a `game-start` event, however I can envision other arguments being useful and for other events

PR: #598

**Comment by mmatyas** [comment]
That sounds good, yes, I think that could be added to even `game-end` . Other than that, I wonder if launch command itself should be passed too, in case it's used somehow. Then there was an issue (or message?) somewhere that env vars could be used too to pass values.

Anyway, the path is clearly the main interest here, so I think that can be just passed as directly. Will look into it.

**Comment by mmatyas** [comment]
(fixed by #598, continued in #599)
