### ISSUE TITLE
Add Playnite Support

### ISSUE THREAD

**Issue by creepertron95** [mmatyas/pegasus-frontend#600]
Hi, I use Playnite at the moment and I wanted to switch to the Pegasus FE to test it out. It would be nice to have support for Playnite in the Pegasus Frontend so I don't have to reconfigure everything.

https://playnite.link/

**Comment by mmatyas** [comment]
Good idea! Will check if it can be done.

**Comment by mmatyas** [comment]
Support is now available in the latest version, have fun!
