### ISSUE TITLE
Add support for Screenshot Title

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#601]
Currently all screenshots are lumped together in the gamedata.assets.screenshots[] array. It would be nice to be able to support the title screenshot also (this can be scraped and also in LaunchBox is called Screenshot - Game Title). This way theme makers can use this asset in their themes (or include the option to display it).

**Comment by mmatyas** [comment]
I agree, the only issue is how should this be stored in the metadata file. Right now one can write

`assets.boxFront: path/to/something.jpg`

and the whole value is a path. Additional parameters could be defined in the same line like this:

`assets.boxFront: "path/to/something.jpg" title="some title" asd="fgh"`

but that'd mean requiring very specific syntax for particular combination of parameters in the file (though the need for something like this appears elsewhere too). The other alternative would be defining them as a separate block:

```
assets.boxFront: path/to/something.jpg

# later...

screenshot: path/to/something.jpg
title: some title
```

which would be more in line with the format, but horribly verbose in my opinion.

So yeah, I'm also thinking about how this could be added in a nice way.

**Comment by PlayingKarrde** [comment]
Actually what I meant by title screenshot is actually it is a different screenshot, but of the title screen. [For example](https://assets.primagames.com/media/files/smb1-in-article-image1.jpg/PRIMA/resize/618x0).

**Comment by mmatyas** [comment]
Ah I see, yeah that could be added with way less problems :)

**Comment by mmatyas** [comment]
Ok, this is now supported in the latest version! The asset is called `titlescreen`.
