### ISSUE TITLE
Cemu games not launching from LaunchBox setup

### ISSUE THREAD

**Issue by JakedUp** [mmatyas/pegasus-frontend#606]
Have several WiiU games setup in LaunchBox, which is configured to use Cemu with default launch parameters

- When launching the game from LaunchBox, it launches Cemu and loads the game
- When launching from Pegasus, it loads Cemu and does not load the game

**Comment by mmatyas** [comment]
Hi, there should be a `Data/Emulators.xml` file in LaunchBox's directory, could you attach it?

@PlayingKarrde does this happen for you too?

**Comment by PlayingKarrde** [comment]
Seems to work ok for me.

**Comment by JakedUp** [comment]
<?xml version="1.0" standalone="yes"?>
<LaunchBox>
  <EmulatorPlatform>
    <Emulator>14bba302-605c-4a44-a7fd-c3b7873eb954</Emulator>
    <Platform>Nintendo GameCube</Platform>
    <CommandLine />
    <Default>true</Default>
    <M3uDiscLoadEnabled>false</M3uDiscLoadEnabled>
  </EmulatorPlatform>
  <EmulatorPlatform>
    <Emulator>14bba302-605c-4a44-a7fd-c3b7873eb954</Emulator>
    <Platform>Nintendo Wii</Platform>
    <CommandLine />
    <Default>true</Default>
    <M3uDiscLoadEnabled>false</M3uDiscLoadEnabled>
  </EmulatorPlatform>
  <EmulatorPlatform>
    <Emulator>197b6f83-7ccc-4e0e-9779-f925de40667d</Emulator>
    <Platform>Nintendo Wii U</Platform>
    <CommandLine />
    <Default>true</Default>
    <M3uDiscLoadEnabled>false</M3uDiscLoadEnabled>
  </EmulatorPlatform>
  <Emulator>
    <ApplicationPath>C:\Users\Jake\Applications\Dolphin\Dolphin.exe</ApplicationPath>
    <CommandLine>-b -e</CommandLine>
    <DefaultPlatform />
    <ID>14bba302-605c-4a44-a7fd-c3b7873eb954</ID>
    <Title>Dolphin</Title>
    <NoQuotes>false</NoQuotes>
    <NoSpace>false</NoSpace>
    <HideConsole>false</HideConsole>
    <FileNameWithoutExtensionAndPath>false</FileNameWithoutExtensionAndPath>
    <AutoHotkeyScript />
    <AutoExtract>false</AutoExtract>
    <UseStartupScreen>true</UseStartupScreen>
    <HideAllNonExclusiveFullscreenWindows>false</HideAllNonExclusiveFullscreenWindows>
    <StartupLoadDelay>5000</StartupLoadDelay>
    <HideMouseCursorInGame>true</HideMouseCursorInGame>
    <DisableShutdownScreen>false</DisableShutdownScreen>
    <AggressiveWindowHiding>false</AggressiveWindowHiding>
    <UsePauseScreen>true</UsePauseScreen>
    <PauseAutoHotkeyScript>; No script is required for pausing Dolphin
</PauseAutoHotkeyScript>
    <ResumeAutoHotkeyScript>; No script is required for resuming Dolphin
</ResumeAutoHotkeyScript>
    <DefaultPauseSettingsPushed>true</DefaultPauseSettingsPushed>
    <SuspendProcessOnPause>true</SuspendProcessOnPause>
    <ForcefulPauseScreenActivation>true</ForcefulPauseScreenActivation>
    <LoadStateAutoHotkeyScript>; Dolphin loads state with F1 key by default
Send {F1 down}
Sleep 50
Send {F1 up}
</LoadStateAutoHotkeyScript>
    <SaveStateAutoHotkeyScript>; Dolphin saves state with Shift+F1 keys by default
Send {Shift down}
Sleep 50
Send {F1 down}
Sleep 50
Send {F1 up}
Sleep 50
Send {Shift up}
</SaveStateAutoHotkeyScript>
    <ResetAutoHotkeyScript>; PLEASE READ: Dolphin does not have a reset key bound by default!
; You must go to Options &gt; Hotkey Settings in Dolphin.
; Bind the R key to the Reset option in order for this to work!
Send {r down}
Sleep 50
Send {r up}
</ResetAutoHotkeyScript>
    <SwapDiscsAutoHotkeyScript />
    <ExitAutoHotkeyScript>; No custom exit script is necessary for Dolphin
; since it already uses the Escape key by default
</ExitAutoHotkeyScript>
  </Emulator>
  <Emulator>
    <ApplicationPath>C:\Users\Jake\Applications\Cemu\Cemu.exe</ApplicationPath>
    <CommandLine>-f -g</CommandLine>
    <DefaultPlatform />
    <ID>197b6f83-7ccc-4e0e-9779-f925de40667d</ID>
    <Title>Cemu</Title>
    <NoQuotes>false</NoQuotes>
    <NoSpace>false</NoSpace>
    <HideConsole>false</HideConsole>
    <FileNameWithoutExtensionAndPath>false</FileNameWithoutExtensionAndPath>
    <AutoHotkeyScript />
    <AutoExtract>false</AutoExtract>
    <UseStartupScreen>true</UseStartupScreen>
    <HideAllNonExclusiveFullscreenWindows>false</HideAllNonExclusiveFullscreenWindows>
    <StartupLoadDelay>5000</StartupLoadDelay>
    <HideMouseCursorInGame>true</HideMouseCursorInGame>
    <DisableShutdownScreen>false</DisableShutdownScreen>
    <AggressiveWindowHiding>false</AggressiveWindowHiding>
    <UsePauseScreen>true</UsePauseScreen>
    <PauseAutoHotkeyScript />
    <ResumeAutoHotkeyScript />
    <DefaultPauseSettingsPushed>true</DefaultPauseSettingsPushed>
    <SuspendProcessOnPause>true</SuspendProcessOnPause>
    <ForcefulPauseScreenActivation>true</ForcefulPauseScreenActivation>
    <LoadStateAutoHotkeyScript />
    <SaveStateAutoHotkeyScript />
    <ResetAutoHotkeyScript />
    <SwapDiscsAutoHotkeyScript />
    <ExitAutoHotkeyScript />
  </Emulator>
</LaunchBox>

**Comment by JakedUp** [comment]
Please let me know if you need any other details on this issue

**Comment by JakedUp** [comment]
I also must mention that Nintendo Wii, GameCube, and Switch ROMs from LaunchBox do not have this issue when launching through Pegasus. For some reason it only seems isolated to Wii U / Cemu. When Pegasus launches Cemu it doesn't have an error message or anything. It literally just launches Cemu and that is it.

**Comment by JakedUp** [comment]
Hello -- any update to this? No idea why Pegasus fails to launch Wii U titles, but Launchbox does just fine...

**Comment by mmatyas** [comment]
Ok, this is now fixed in the latest version!
