### ISSUE TITLE
Read Media by "ROM"name in type folder

### ISSUE THREAD

**Issue by thatman84** [mmatyas/pegasus-frontend#608]
The ability to recognise media named after the "gamename" would IMO be extremly beneficial.

Many other frontends (Hyperspin/RetroFE/AttractMode/LaunchBox etc) read media assets by matching rom and file name.
This means like myself there is a big group of emulation enthusiast that have large curated collections of media (Logos,Box,Cart,Video etc) all named the same as our gamenames, making it fairly difficult to convert into Pegasus format folder structure or updating the metadata.txt files withe the code required to assign asset files.

The frontend looks pretty awesome, being able to have a PC/Android setup with minimal duplication is awesome and also most Android frontends are not as pleasing as Pegasus looks to be.

Having it easy to use existing assests would likely allow more users to test the frontend without mass conversions of files

**Comment by mmatyas** [comment]
Hi, at the moment Pegasus supports two asset directory styles:

- files grouped by game name, eg.:

```
NES/
├─ metadata.pegasus.txt
├─ Contra (U).zip
└─ media/
   └─ Contra (U)/
      ├─ boxFront.jpg
      ├─ logo.jpg
      └─ video.mp4
```

- files grouped by asset type ("Skraper style"):

```
NES/
├─ metadata.pegasus.txt
├─ Contra (U).zip
└─ media/
   ├─ box2dfront/
   │  └─ Contra (U).png
   └─ videos/
      └─ Contra (U).mp4
```

There's also support for loading the assets referenced in EmulationStation's and LaunchBox's files, with possibly others in the future. Other than those, would you like to see support for some additional asset naming style?

**Comment by thatman84** [comment]
It’s possible this is exactly what I was asking for

NES/
├─ metadata.pegasus.txt
├─ Contra (U).zip
└─ media/
   ├─ box2dfront/
   │  └─ Contra (U).png
   └─ videos/
      └─ Contra (U).mp4

Maybe I miss read the documentation. I thought this had to be specified in the metadata.txt file on a per game basis.

Is the above format automatically recognised?

I will test tomorrow and close if needed

**Comment by thatman84** [comment]
Is there a folder support list for skraper?

I have box3d (not working)
support (not working)
videos (working)
wheel (works)

Maybe its the theme, I will try

**Comment by mmatyas** [comment]
Yeah, the Skraper support could indeed see a bit more documentation -- I'll add this info to the docs. Both formats above are recognized (the second one when Skraper support is turned on in the Settings menu), so in many cases it's not necessary to manually define game assets. Also here's the list of the currently supported directories:

- box2dback
- box2dfront
- box2dside
- boxtexture
- fanart
- screenmarquee
- screenmarqueesmall
- screenshot
- screenshottitle
- steamgrid
- support
- supporttexture
- videos
- wheel
- wheelcarbon
- wheelsteel

(These are the directories where Pegasus *finds* the assets, but as for what is displayed on screen, that entirely depends on the theme.)
