### ISSUE TITLE
Duplicate Games showing up in collection

### ISSUE THREAD

**Issue by msheehan79** [mmatyas/pegasus-frontend#631]
I just downloaded pegasus-fe_alpha13-89-g75ab136_win-mingw-static and noticed that I am seeing some duplicate games, it looks like based on the name being the same. 

Case in point I have a collection for the 19XX series, 1942 was ported to several systems and you can see the NES version shows up twice.

This did not occur on build pegasus-fe_alpha13-55-gb984bad_win-mingw-static.

![image](https://user-images.githubusercontent.com/1565622/81461956-50c13400-917d-11ea-8be5-975b98f90a0d.png)

Attaching the metadata file I am using for above example, if it helps.

[custom-19xx.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/4602514/custom-19xx.metadata.txt)

**Comment by mmatyas** [comment]
Found the issue; just to make sure, there supposed to be 22 games, right?

**Comment by msheehan79** [comment]
Correct - should be 22 in this collection.

**Comment by mmatyas** [comment]
Ok, this should be fixed now in the latest release, could you check it?

**Comment by msheehan79** [comment]
Confirmed, no more duplicates. Thanks!
