### ISSUE TITLE
Crashes when trying to switch collections on default theme

### ISSUE THREAD

**Issue by msheehan79** [mmatyas/pegasus-frontend#632]
With build pegasus-fe_alpha13-89-g75ab136_win-mingw-static Pegasus is crashing when switching collections on the default grid theme. I only tested using the 'Q' and 'E' keyboard commands.

- Windows 10 x64, using metadata files in the pegasus/config/metafiles folder
- Portable mode
- Didn't seem to happen when I only loaded about 5 collections, but happened when I loaded around 15 metadata files.
- I wiped all my prior configs to ensure nothing from an older config was impacting it

Error on the log is:
2020-05-09T07:15:40 [e] QQmlEngine: Illegal attempt to connect to model::Game(0x134a6550) that is in a different thread than the QML engine QQmlApplicationEngine(0x4a22928.

Attached the full logfile if needed.
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/4603347/lastrun.log)

**Comment by mmatyas** [comment]
Could you upload the metadata files? In case it turns out to be related to some specific game entry.

**Comment by mmatyas** [comment]
Actually I think I just managed to reproduce it; I was testing #631 and this just happened to me too. It might be related to missing files actually, will look into it. Never hurts to test it with your metadata files too though.

**Comment by msheehan79** [comment]
I can confirm this crash does appear to be related to missing game files. I had a few files missing on the metadata file, when I fixed or removed those missing entries from the metadata file it no longer crashes.

**Comment by mmatyas** [comment]
This and probably #633 too should now work in the latest version, could you double check it?

**Comment by msheehan79** [comment]
@mmatyas Confirmed - it now works and doesn't crash no matter how many metadata files I throw at it. Thanks!
