### ISSUE TITLE
Add "box3d" to SkraperAssetsProvider

### ISSUE THREAD

**Issue by pswift** [mmatyas/pegasus-frontend#643]
For Pegasus to find my 3D box art I have to rename the folder from "box3d" to "box2dfront or "supporttexture". Can you please add "box3d" to the list of supported Skraper assets. Many thanks.

**Comment by mmatyas** [comment]
Sure, this seems to be possible. Will look into it.

**Comment by pswift** [comment]
Thank you

**Comment by mmatyas** [comment]
Ok, this should be working in the latest version.

**Comment by pswift** [comment]
Thanks you, it works a treat
