### ISSUE TITLE
Add screen rotation option

### ISSUE THREAD

**Issue by valadaa48** [mmatyas/pegasus-frontend#649]
The odroidgo2 advance requires screen rotation of 90 degrees. Would it be possible to add screen rotation support to pegasus?

**Comment by mmatyas** [comment]
Hi, the rotation and shape of the programs should be decided by the display/video driver, or the window manager, if there's any. Setting that up might be more beneficial than modifying every application one by one to get rotated.

**Comment by valadaa48** [comment]
Thanks for your reply and I agree. Unfortunately for our device we need to rotate manually in userspace. Our sdl2 lib is patched to do this for us but I understand your app is using Qt. Do you know if at least Qt supports rotation internally perhaps?

**Comment by mmatyas** [comment]
Hm that's too bad. I'm not aware of built-in rotation support for Qt, but it possible to rotate the GUI elements and so it may also be possible to rotate the whole interface by code. If you wish to work on that here's a diff I've just experimented with: https://pastebin.com/1h78GBNB. The scaling is off but otherwise the rotation seems to be working.

**Comment by valadaa48** [comment]
Hi @mmatyas your patch appears to be working. I initial got an error that no games were found but quickly figured out about game_dirs.txt, now I'm up against a theme failed to load error: 
```[w] qrc:/themes/pegasus-theme-grid/theme.qml:64:5: Type BackgroundImage unavailable
[w] qrc:/themes/pegasus-theme-grid/layer_grid/BackgroundImage.qml:19:1: module "QtGraphicalEffects" is not installed```

```[i] Found theme `Pegasus Grid` at `:/themes/pegasus-theme-grid/`
[i] Found theme `9999999-in-1` at `/home/odroid/.config/pegasus-frontend/themes/pegasus-theme-grid/`
[i] Theme set to `Pegasus Grid` (`:/themes/pegasus-theme-grid/`)```

I'll keep digging and thanks for the patch.

**Comment by valadaa48** [comment]
OK those were just missing dependencies from the PKGBUILD file. I've added them happy to say that it's working. Indeed it appears that many UI components will need to be scaled correctly.

I will try to get this going. Thanks

**Comment by mmatyas** [comment]
I guess this can be closed until further developments.
