### ISSUE TITLE
No Keyboard-input in Retropie-Setup

### ISSUE THREAD

**Issue by xFJSx** [mmatyas/pegasus-frontend#655]
While in the Pegasus Menu the input from a USB Keyboard is working fine, but after starting Retropie-Setup or File-Manager the keyboard input isn't recognized. Returning to Pegasus and the keyboard is recocnized normaly.

After starting the Pixel-Desktop from pegasus (the aditional installed desktop within a normal retropie-installation) and returning to Pegasus and reentering the Retropie-Setup, the keyboard-input is working again. 

I checked the funktionality by booting into emulationstation and entering Retropie-Setup, where it is working fine.

I also quitet pegasus and the keyboard-input is working fine the terminal, restarting pegasus through terminal and the input at Retropie-Setup isn't working.   

By switching to an older Pegasus-release alpha13-55(2020-04-28) the keyboard-input works fine in the Retropie-Setup right after booting Pegasus

**Comment by mmatyas** [comment]
Ok, this should be fixed now in the latest release!
