### ISSUE TITLE
Building latest releases for Raspbian stretch

### ISSUE THREAD

**Issue by chrisbevan** [mmatyas/pegasus-frontend#659]
Hi,

I'm really keen to try the latest Pegasus versions on my (Stretch) Retropie setup but see that these new builds are for Debian Buster only. Before I go through the process of upgrading Retropie, is it feasible to compile for Stretch on a Pi3? Sorry if this comes across as rather noob!

**Comment by mmatyas** [comment]
Hi, yes, it still should be possible! Due to various system library incompatibilities I can't create one release that would run on all distros, but when you're building for yourself you don't have to deal with such issues. For now the build should still work on Strecth.

**Comment by chrisbevan** [comment]
Great - thanks!
