### ISSUE TITLE
Modifier keys aren't detected while seting up controls in Pegasus

### ISSUE THREAD

**Issue by gcarvalho** [mmatyas/pegasus-frontend#660]
When running an arcade cabinet using a keyboard encoder such as an[ I-PAC 2](https://www.arcadeworlduk.com/products/I-PAC-2-FS32-Keyboard-Encoder.html), frequently some of the keyswitches are set to modifier keys such as Shift, Alt or Ctrl. 
These are not detected in the Pegasus configurations, making it a pain to migrate existing instalations from emulationstation and similar.

**Comment by mmatyas** [comment]
Hi, this sounds like the duplicate of #481.

**Comment by gcarvalho** [comment]
You're right, deeply sorry. I did search, but clearly poorly. I'll close it.
