### ISSUE TITLE
Pegasus' build in release => Issue : Pictures doesn't display, while videos work

### ISSUE THREAD

**Issue by Bi-noon** [mmatyas/pegasus-frontend#663]
Hi Fluffy ! I compiled your Github's build and I find an issue where in the Steam collection, Steam games' picture doesn't display, while videos work.
We just have the loading icon which is displayed indefinitely. When I swap my build with your official build the pictures is displayed. 
is It a building's issue or a bug?

**Comment by mmatyas** [comment]
Hi! Well it's hard to tell, do you see anything in the log? Maybe a difference in the Qt version?

**Comment by Bi-noon** [comment]
I got this error in the log : "qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed".
It is maybe because of the difference between the Qt versions. I keep you updated.

**Comment by Bi-noon** [comment]
Hi Fluffy ! I just find the cause of this issue. It is because I don't have OpenSSL installed in my computer. Qt is really tricky.

**Comment by mmatyas** [comment]
Interesting! I'm surprised Qt didn't tell that this is the issue, but I guess it works now.

**Comment by Bi-noon** [comment]
Yes ! Apparently the files "libcrypto-1_1-x64.dll" and "libssl-1_1-x64.dll" was needed.
