### ISSUE TITLE
Only Alpha 7 works

### ISSUE THREAD

**Issue by silvinator** [mmatyas/pegasus-frontend#664]
Hello everyone.

I recently grabbed my old PC and put on a new version of Win 7. This was after they ended the support. The Problem that now occurs is, that I'm only able to start Alpha 7 on it. This also occurred on my Laptop, which I recently put on Win 7 too. The only Win 7 PC that works is the old one which had it already installed before the support ended. Anyone has a solution to it? Do I need to install some dependencies for it?

**Comment by mmatyas** [comment]
I've tried the latest version in an emulated Windows 7 SP1, right after installing from a disc, but worked out of the box for me. I believe it was probably something driver- or media codec related for you, but I'm not 100% sure. It seems all Windows 7 versions are officially unsupported now, and others didn't find a solution either, so I'm closing this for now, sorry. But in case there's some new detail that you've found, feel free to share it!
