### ISSUE TITLE
Collection 'directory' setting not being used when picking up games files on pegasus-fe startup

### ISSUE THREAD

**Issue by smoothquark** [mmatyas/pegasus-frontend#665]
I am not sure if this is a bug or by design. I have enclosed my metadata file that I have been testing with. 

I am running Debian Buster. Games are stored in an NFS share and mounted accordingly. To keep the Games folders "clean" I am having my metadata in ~/.config/pegasus-frontend/metafiles. I am using the "directory" setting in "collection" to point to the folder where the games are stored. Testing with two games - the first (Wii Chess) has the game "file" set relative to the "directory" and in the second (Wii Sports), it has its full path. As this is just the testing phase, I have not entered in the images. Both games launch absolutely fine, but there is no metadata shown for Game 1 (Wii Chess). Warning entry on startup...

[w] Metafiles: `~/.config/pegasus-frontend/metafiles/nintendo_wii.metadata.txt`, line 10: missing file `Wii Chess/Wii Chess.wbfs`

Does this mean that the "file" setting requires the full path to be specified? It would be nice if it could use the "directory" setting as it does when launching. Perhaps this is by design?

[nintendo_wii.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/4938911/nintendo_wii.metadata.txt)

**Comment by mmatyas** [comment]
Hi, yes, game paths are relative to the metadata file they are in. A metadata file can store more than one collection, so it's also possible to have games with exactly the same relative paths matching files in multiple directories. So yeah, in global metadata files you likely want to use full paths to the games.

**Comment by smoothquark** [comment]
Thanks. OK, will use full paths. Thanks.
