### ISSUE TITLE
Unable to Launch Pegasus in Sway

### ISSUE THREAD

**Issue by jackgriffith03** [mmatyas/pegasus-frontend#666]
I'm trying to launch Pegasus from a terminal inside of Sway but get an error.

```
emu@xeon1265:~$ pegasus-fe
QFactoryLoader::QFactoryLoader() ignoring "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3" since plugins are disabled in static builds
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

If I change the environmental variable, QT_QPA_PLATFORM, I get a slightly different error.

```
emu@xeon1265:~$ export QT_QPA_PLATFORM=wayland
emu@xeon1265:~$ pegasus-fe
QFactoryLoader::QFactoryLoader() ignoring "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3" since plugins are disabled in static builds
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

I'm not a software dev, just a normal person. So I don't know if I'm including enough information or the right information. Thanks for reading.

**Comment by mmatyas** [comment]
Hi, the official binaries lack Wayland support -- I'm not familiar with Sway, but if there's a way to run X11 apps on it, you might try launching Pegasus like that. Alternatively, you can also build it from source to match your setup, in which case [this page](https://pegasus-frontend.org/docs/dev/build/) might help.

**Comment by mmatyas** [comment]
Other than building from source, Pegasus is also available [using Flatpak](https://flathub.org/apps/details/org.pegasus_frontend.Pegasus), which I think should also solve the issue.
