### ISSUE TITLE
[bug][windows] Reset custom control

### ISSUE THREAD

**Issue by valsou** [mmatyas/pegasus-frontend#680]
Each time i quit/launch Pegasus on Windows (alpha13-121) my custom constrol is lost.
So far it is just the case for the "previous page" control.

![bugcontrols](https://user-images.githubusercontent.com/2614514/90337257-dcb3e900-e013-11ea-93cc-0686354955a3.jpg)

Edit: my settings.txt looks like that :

> keys.prev-page: Q,A,GamepadL1,,

It might be an issue with the comma not escaped.

**Comment by mmatyas** [comment]
Hm so using the comma key produces a `,` in the config file? Interesting, will look into it, thanks!

**Comment by mmatyas** [comment]
Ok, should be now fixed in the latest release!
