### ISSUE TITLE
Pegasus crashes, when selecting other Steam games !

### ISSUE THREAD

**Issue by Bi-noon** [mmatyas/pegasus-frontend#683]
Hi Fluffy! When I select another Steam Games, the front-end crashes. I tested Pegasus with my laptop and my desktop both in Windows 10 and I still have the crash (the first time, I thought it was the release that I compiled from your project, which was the cause of this issue, so I tested your official release, same result). When I remove the video display in my QML file, the front-end doesn't crash.
So I suppose that it is the network transfer, which may affect the playback, as you mention it in the issue #386 .

Do you know how to prevent or resolve this issue?

**Comment by mmatyas** [comment]
Hi, could you try the release from [this package](https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1/pegasus_qt515-test.zip)? It's an experimental build with some related networking changes. If it doesn't work, could you attach a log file?

**Comment by Bi-noon** [comment]
Hi again Fluffy, thank you for your fast answer! I just tested this release "pegasus-fe_alpha13-132-g2981ac9b_win-mingw-static.zip", It works perfectly and It is so much more stable. I saw that this version fix another issue about steam's video loops, where, when a video restart after the end of the previous loop, just the audio restarts and the display freezes. Do you plan to push this version in the master branch?

**Comment by Bi-noon** [comment]
Sorry, the Steam's video loop issue occurs only with the release that I compiled. It works correctly with the official release.

**Comment by mmatyas** [comment]
Yup, that's going to be #673.

**Comment by mmatyas** [comment]
Ok, this should be now working with the latest release!

**Comment by Bi-noon** [comment]
Thank you Fluffy for giving your valuable time to help us !
