### ISSUE TITLE
(PI4) Pegasus ignores any video setting specified in config.txt 

### ISSUE THREAD

**Issue by darksaviorx** [mmatyas/pegasus-frontend#684]
Pegasus will only use a monitor/tv's maximum resolution. When using a vizio 4k tv, if I specify in the config.txt to boot in 1080p, the boot process will be in 1080p, but Pegasus will be in 4k. If I exit Pegasus to the command-line, the resolution then goes back to 1080p. There are no scaling issues. 

A workaround is to use the setting hdmi_ignore_edid=0xa5000080 which forces Pegasus to use 1080p. 

It happens with every version of Pegasus I've tried including the latest one (aug 2020).

**Comment by mmatyas** [comment]
Sorry for the late reply! Looking into the underlying code, it seems Qt sets the app's size to match what the TV reports via EDID. I haven't found a way to dynamically turn this off, but in theory you can override its setting. Have you tried [this workaround](https://retropie.org.uk/forum/post/208037)? What was the result?

**Comment by darksaviorx** [comment]
I never figured out how to try that workaround. I typed the commands in the terminal to point to the json file I created but it doesn't work.

**Comment by mmatyas** [comment]
To set environmental variables for a program, you can launch it either like this:

```
SOMEVARIABLE=somevalue  ANOTHERVARIABLE=anothervalue  program
```

or like this, in the same terminal:

```
export SOMEVARIABLE=somevalue 
export ANOTHERVARIABLE=anothervalue 
program
```

In this case, to tell Pegasus to use the file, launch it like this:

```
QT_QPA_EGLFS_KMS_CONFIG=/home/pi/egl.json  pegasus-fe
```

You can also turn on verbose low level logging like this:

```
QT_LOGGING_RULES="qt.qpa.*=true"  QT_QPA_EGLFS_KMS_CONFIG=/home/pi/egl.json  pegasus-fe
```

With the logging turned on, you should now see some messages related to the JSON file or to the values in it (and hopefully the issue getting fixed!).

**Comment by darksaviorx** [comment]
Thank you for the clear instructions. That works! This also fixes the black screen with the full kms driver. 
Here's the log: https://pastebin.com/VvMGePcS

**Comment by mmatyas** [comment]
Just added some notes about this in the documentation: https://pegasus-frontend.org/docs/user-guide/platform-linux/#gpu-driver-notes
