### ISSUE TITLE
"Method Return Time" Console Message on Reboot

### ISSUE THREAD

**Issue by idemiq** [mmatyas/pegasus-frontend#690]
### The issue

The following message is displayed in the console after selecting "Reboot" from the UI, regardless of Theme. The system then continues to Reboot as expected - but the message is undesirable.

"method return time=1598974934.594465 sender=:1.1 -> destination=:1.14 serial=42 reply_serial=2"

### System info

Official Retropie 4.6 image (md5: 9154d998cba5219ddf23de46d8845f6c) on Raspberry Pi 4 (clean installation).

### Pegasus version

Installed from Retropie experimental package options: alpha13-149-g00678172-dirty (2020-08-25)

### Pegasus log

Attached (but of limited use). [lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5157447/lastrun.log)

**Comment by mmatyas** [comment]
Ok, this should be now fixed in the latest version! Could you try if it still occurs?

**Comment by idemiq** [comment]
Updated via RetroPie_Setup package list and messages have disappeared. Great stuff!
