### ISSUE TITLE
[Win10] Crash after successul loading UI - DirectShowPlayerService::doRender

### ISSUE THREAD

**Issue by fzzr-** [mmatyas/pegasus-frontend#714]
| Version      | alpha14-24-g4e601083 | 
| ------------- |:------------------------:|
| OS             | Win 10 (ltsb)                  |

### Steps to reproduce:

1. execute `pegasus-fe.exe`
1. _wait... UI loaded... Progress bar completed... Tiles of games showed._
1. BOOM :( with `DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()`

[crashlog: lastrun.log](https://github.com/mmatyas/pegasus-metadata-editor/files/5294996/lastrun.log)

Possibly related issue: [#464](https://github.com/mmatyas/pegasus-frontend/issues/464#issuecomment-691932799)

- - -

Reproduced on versions:

Last working version is [Alpha 10](https://github.com/mmatyas/pegasus-frontend/releases/tag/alpha10). There's same error too but without crashes. [lastrun-ver.alpha10.log](https://github.com/mmatyas/pegasus-metadata-editor/files/5295087/lastrun-v.a10.log)

All versions newest then alpha-10 are crashing with:
| Version | Error |
| ------------- | ------------------------ |
| 10, 12, 13 | __alive, not crashing!__ but same err in log: `DirectShowPlayerService::doRender`, but crashing if GoG enabled |
| 11 | `[w] ES2: system config file not found` |
| 14 | `DirectShowPlayerService::doRender` __always crashing__ |

**Comment by mmatyas** [comment]
Hi, could you try disabling the external game sources, either from the settings menu, if you can access that, or manually like [in this comment](https://github.com/mmatyas/pegasus-frontend/issues/661#issuecomment-688474106)? I have a feeling this might be related to Steam videos; do you have any [codec packs installed](https://pegasus-frontend.org/docs/user-guide/platform-windows/#multimedia-support)?

**Comment by mmatyas** [comment]
I've also just run into this issue with LaunchBox videos, but installing K-Lite fixed the crash.

**Comment by fzzr-** [comment]
@mmatyas,
> Hi, could you try disabling the external game sources, either from the settings menu, if you can access that, or manually like [in this comment](https://github.com/mmatyas/pegasus-frontend/issues/661#issuecomment-688474106)? I have a feeling this might be related to Steam videos...

Without `providers` (all `providers.` options are disabled) it works. I see the "Games not found" screen and also menu working well.

But if Steam or GoG providers enabled - crash.
I should say I have no launchers on PC other then Steam & GoG.
So, crash is happening when any game found.

- [Steam enabled lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5308130/lastrun.log)
- lastrun.log is empty If GoG enabled

Version: alpha14-28-g5e97ad5a_win-mingw-static

> do you have any codec packs installed?

No, it's just a PC for games.

> I've also just run into this issue with LaunchBox videos

I have no LaunchBox installed.

**Comment by fzzr-** [comment]
Just installed K-Lite 15.7.5 Basic and nothing changed in Pegasus behavior.

**Comment by fzzr-** [comment]
Also I have just added a game manually. Works fine ❤️ , but I have found new warning in the log:

`[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/my windows games.svg`

**Comment by mrcrowley666** [comment]
Crashing for me too. Unless I disable Steam and GOG. This is literally the first time I've downloaded and run it too.

**Comment by fzzr-** [comment]
I have just tested latest build pegasus-fe_alpha14-30-g7a795db5_win-mingw-static with enabled Steam & GoG providers.

Because I have added custom game by hand, it listed in first tab in the UI ("My windows games"). So, program loads correctly and I can interact with UI. Also all games from steam-provider loaded successfully.

When I'm activating Steam/GoG-tab program crashing with the [(same error lastrun.log)](https://github.com/mmatyas/pegasus-frontend/files/5322219/lastrun.log).

**Comment by fzzr-** [comment]
The latest build `alpha14-35-g1207934b_win-mingw-static`:
- with Gog enabled crashing with empty lastrun.log. I suspect there is segfault or uncatched something.
- with Steam enabled crashing with same error but __not immediately__, so from `23:50:41` to `23:50:59` I was playing with navigation in menu and titles (game-tiles). See the [lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5374113/lastrun.log).

**Comment by mmatyas** [comment]
So I've just heard that apparently some codecs might be missing from certain K-Lite versions. Could you try installing `opencodecs_0.85.17777.exe` from https://xiph.org/dshow/ ?

**Comment by fzzr-** [comment]
@mmatyas, thanks! It works now!

**Comment by syrusgreycloak** [comment]
Apologies for the necro posting, but I just found out about pegasus and ran into this same issue with Steam integration while getting it setup.  I was able to resolve by installing the k-lite mega pack from scoop.

scoop install nonportable/k-lite-codec-pack-mega-np
