### ISSUE TITLE
ROMS and SAVES cloud

### ISSUE THREAD

**Issue by XargonWan** [mmatyas/pegasus-frontend#726]
I wish to have the ability to connect pegasus to a cloud (ie Google Drive, Dropbox) and load the roms list present on the server so I can choose to download a specific rom from my own cloud.

Moreover I wish to have the ability to backup and restore my saves trough said cloud.

Can it be an interesting function for the future?

**Comment by mmatyas** [comment]
Actually I think someone is working on a similar setup on Discord, you might wish to check it out (look for NeoID). As saves are highly emulator-specific, unfortunately I can't promise a manager for them *inside* Pegasus, but if someone does make such helper app I'd be happy to add them to a list of tools somewhere on the page.

**Comment by mmatyas** [comment]
I guess this can be closed.
