### ISSUE TITLE
Cache imported games to speed up start up

### ISSUE THREAD

**Issue by juanma-cvega** [mmatyas/pegasus-frontend#731]
Would there be any way to cache imported games so start up is faster? The reason for asking is because there may be thousands of games when importing a full set of games for a platform (i.e. MAME). In those cases it takes more than a minute just to start up when it also loads all the media assets.

**Comment by mmatyas** [comment]
Hi, yes, there are plans for adding some level of caching in the future, hopefully soon!

**Comment by mmatyas** [comment]
Continued in #839.
