### ISSUE TITLE
Pegasus Frontend is completely broken on Android 11 phone

### ISSUE THREAD

**Issue by turboboy215** [mmatyas/pegasus-frontend#734]
Hi, and thanks for reporting errors! You can help us locating the bug even more by providing detailed information in the sections below:

### The issue

I just installed this excellent-looking frontend on my phone. However, having updated to Android 11, it seems to render this app completely unusable. Every time I try to open the app, it just opens and then immediately closes before anything comes on the screen. If I use an older APK of version 14 stable, it will run, but none of the emulators or other apps work, probably due to the whole "scoped storage" issue.

### System info

I am using a Pixel 3 phone updated to the most recent version of Android 11. I imagine that this problem is due to the recent changes in the "scoped storage" in this Android version.

### Pegasus version

I have tried using both the latest alpha build 14-6 and the latest stable build 14-3 as well as the older 14-36, but none of these run.

### Pegasus log

I cannot post a log since it closes before I can do anything.

**Comment by mmatyas** [comment]
An Android bug just got fixed in the latest version, could you check if it works for you?

**Comment by turboboy215** [comment]
Still completely broken, crashing on app load. I wish I knew how to downgrade my phone, but it looks so complicated... Why does Google have to ruin everything?

**Comment by mmatyas** [comment]
Ok, this should now work in the latest version! Could you give it a try?

**Comment by turboboy215** [comment]
It works, but none of the apps will work. There is another issue that describes the problem.

**Comment by mmatyas** [comment]
Thanks for testing, I'll then close this issue in favor of #766.
