### ISSUE TITLE
Crashes with latest build (alpha14-62-g74f285fe) (Win 10 / portable)

### ISSUE THREAD

**Issue by msheehan79** [mmatyas/pegasus-frontend#736]
Hi, and thanks for reporting errors! You can help us locating the bug even more by providing detailed information in the sections below:

### The issue
With build alpha14-62-g74f285fe and a Windows 10 x64 setup configured in portable mode, I have found that some specific game metadata entries are triggering a crash. Am including an example metadata file that consistently will crash Pegasus. 

### System info
Windows 10 x64

### Pegasus version
Pegasus build alpha14-62-g74f285fe, using in Portable mode

### Pegasus log
Nothing useful appeared in the log file but including anyway.
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5574804/lastrun.log)
[saturn.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/5574805/saturn.metadata.txt)

**Comment by msheehan79** [comment]
Upon further testing, it seems like it is related to the extension. I noticed that my collection tag was set for "extensions: chd, cue" and the game that triggers the crash uses .m3u playlist so it seems the unrecognized extension is causing a problem. With prior builds I am guessing it just silently ignored these perhaps? I will need to roll back and see what the old behavior was.

**Comment by mmatyas** [comment]
This might be fixed in the latest version, like #737, could you check if it works?

**Comment by msheehan79** [comment]
@mmatyas I can confirm with the latest builds today, I am no longer able to reproduce the crash here. Thanks!
