### ISSUE TITLE
Game metadata entry cannot be shared across collections

### ISSUE THREAD

**Issue by msheehan79** [mmatyas/pegasus-frontend#737]
With the recent provider update, I have noticed a change in how game metadata is parsed. In prior builds, the game metadata could be entered once and used in multiple collections. With the recent updates, if a game is included in more than one collection it now has no metadata associated to it unless the metadata is declared again in each collection file.

I have several games that are included in multiple collections, so what I had previously found worked well was to consolidate all of my game metadata into one single file, and set up the collection file(s) to just list the individual files, instead of duplicating the game metadata into each file. For a larger collection, this cut down the size of the metadata files from around 300MB to about 30MB, and the Pegasus load times dropped significantly as well not having to parse the same game metadata several times.

I am attaching a basic sample of the structure I have been using with metadata populated for a few sample games. 

With the attached example, games 1942 and 1943 are shared across 2 collections. On older builds, the game metadata renders just fine for the game whichever collection you are viewing it on.
![image](https://user-images.githubusercontent.com/1565622/99869304-d8a9e100-2b97-11eb-8966-64cc7e318f58.png)

With the most recent changes, now the only games that render properly are games that are only included in one collection, so in this example "005" works fine but 1942 and 1943 do not render their metadata as the same game is referenced in two collections.
![image](https://user-images.githubusercontent.com/1565622/99869263-9f717100-2b97-11eb-9709-b56d6df5c010.png)

I've attached the 3 metadata files I used for this example if it helps.
[custom-19xx.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/5577109/custom-19xx.metadata.txt)
[games.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/5577110/games.metadata.txt)
[system-arcade-mame.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/5577111/system-arcade-mame.metadata.txt)

**Comment by mmatyas** [comment]
Ok, I think this should be fixed now in the very latest release, could you check it?

**Comment by msheehan79** [comment]
Confirmed, everything is back to working as it was previously and I can see the correct metadata for games across multiple collections. Thanks for the quick updates!
