### ISSUE TITLE
Inability to directly launch Dreamcast games using Reicast and the associated launch command found in the documentation

### ISSUE THREAD

**Issue by mikerealohs** [mmatyas/pegasus-frontend#748]
### The issue

Trying to launch DC Roms directly in Reicast (from the Google Play Store) using Pegasus and the documented launch command generated by the Pegasus config generator (as listed below):

collection: Sega Dreamcast
extensions: gdi
launch: am start --user 0
  -a android.intent.action.VIEW
  -n com.reicast.emulator/.MainActivity
  -d "file://{file.path}"

Every time I click on a Dreamcast title in Pegasus frontend (through the associated art I've scraped that's in the same main folder as the Roms and their GDI components) it opens Reicast in the systems bios/home screen configuration instead of directly opening the game in Reicast (which via the developer it defaults to if it can't find the associated file)...

### System info

Retroid Pocket 2 - running Android version 6.0 and Build version 202010212012
Reicast - version r20.04, from the Google Play Store

### Pegasus version

Pegasus - alpha14-73-g0c109791 (2020-11-28)

### Pegasus log

Attached below (including my DC metadata txt file and Android system logcat files recording me attempting to _**unsuccessfully**_ launch "Street Fighter III - 3rd Impact" in Reicast via Pegasus using the documented launch command, and another showing me _**successfully**_ using Arc Browser frontend to then launch the same game (using the same SD card, file name/type, file path and command) in Reicast, just in case it helps...

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5624879/lastrun.log)
[metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/5624880/metadata.txt)
[Retroid_ADB_log_unsuccessfully_launching_DC_ROM_using_Pegasus.txt](https://github.com/mmatyas/pegasus-frontend/files/5624881/Retroid_ADB_log_unsuccessfully_launching_DC_ROM_using_Pegasus.txt)
[Retroid_ADB_log_successfully_launching_DC_ROM_using_Arc_Browser.txt](https://github.com/mmatyas/pegasus-frontend/files/5624882/Retroid_ADB_log_successfully_launching_DC_ROM_using_Arc_Browser.txt)

**Comment by mmatyas** [comment]
Hm, I see you have `MainActivity` here in the issue and `NativeGLActivity` in the metadata file, have you tried both and none worked?

**Comment by mikerealohs** [comment]
I have indeed tried both intents/launch commands with Pegasus, and neither works (both open the Dreamcast in it's home screen menu/bios).

With that said I grabbed the NativeGLActivity intent/launch command from the logcat running Arc Browser (which uses that command, and successfully opens every ROM I throw at it every single time)... I'm totally lost on how to fix this...

FYI, at this point I'm unsure if the issue lies with Pegasus, Reicast or is a user (me) issue; but the Reicast dev (skmp) is going to run a repro this weekend to see if the issue lies with his code. At this point I'm inclined to think it lies with Pegasus, as all of my other emulators run ok, and Arc Browser will launch these exact same games using the above flagged intent. I don't know tho for 100%...

**Comment by mikerealohs** [comment]
You know what, while looking at the Arc Browser configurations in app I noticed that the dev has Reicast setup to load the games use the following Uri "%rom_uri%" under the "emulator extras category", I'm not sure what any of this means or how it affects games autoloading, but could this be the source of my issue?

Is this a different data parameter for the -d portion of the launch command that I should be using in lieu of say "file://{file.path}"? Sorry, but I'm by no means a dev...

**Comment by mmatyas** [comment]
Hm, in theory both `MainActivity` and `NativeGLActivity` should work and `"file://{file.path}"` seems to be handled in Reicast's code. Looking into the log, it seems Arc launches the games without the `file://` prefix (which is also handled in Reicast). Could you try removing that too? (ie. `-d "{file.path}"`) Another issue I could think of is spaces in the filename, I wonder if launching a game with only letters and numbers in its (and all its parent directories') name might fix it?

**Comment by mikerealohs** [comment]
Yeah,  both MainActivity and NativeGLActivity + the documented "file://{file.path}" net the same result when used in conjunction with Pegasus (sending me to the DC's system menu/bios screen instead of the intended game, hey at least it opens Reicast!).

I tried removing the data parameter as you suggested (the -d portion of the launch command) and starting a game in Pegasus, but it caused Reicast to freak out (as an FYI, whenever you auto launch a game from either front end in Reicast an Android system toast message pops up asking me to "Allow reicast to access photos, media, and files on your device", I always click "allow", and to my knowledge there's no option to set this as a default (necessitating I select everytime I launch a game in Reicast through a frontend)... Per your request, in the Pegasus metadata.txt file, I removed the -d command, which caused it to freak out and totally kill the action (with this removed it refused to even open Reicast in the System menu/bios screen), eventually going back to Pegasus where it promptly reloaded the frontend... 

I'll next try a game with out spaces in both the rom folder directory, and on the actual Roms and in the metadata.txt file to see if that works, however I'm doubtful as the same files auto launch correctly in Reicast when opened through Arc Browser, and after our last set of messages with the other "issue" I flagged to make sure the file names matched with the metadata.txt file. 🤷‍♂️

**Comment by mikerealohs** [comment]
Ok, tried the file names and metadata.txt file with no spaces, and it netted the same result as before (sending me to the DC system menu/bios in Reicast).

**Comment by mikerealohs** [comment]
I just recorded a video of it all, and will share it here with you once it finishes loading up to Google Photos, thanks!

**Comment by mikerealohs** [comment]
Here's the aforementioned video I recorded.
https://photos.google.com/share/AF1QipPta47jjO7v2zP8KKQHTwJDmfosCSZTAPE8gIuFALfyCE-m0HKRglGsF0kNTb1Pcw/photo/AF1QipNY4jVhuIJQsFYO5UsEcKXAhMlvOk7OPMTUPhiB?key=R1pJZlhBMjJmOHVsSFY1cy1YSUlUQnhyZGM5QnVn

**Comment by mmatyas** [comment]
Ah, don't fully remove the `-d` line: that's the part that tells Reicast *what* to open (`-a` tells what should an app do, and `-n` tells which app component should handle this). The collection should look like this:

```
collection: Sega Dreamcast
description: Information from ScreenScraper.fr database
extension: gdi
launch: am start --user 0
  -a android.intent.action.VIEW
  -n com.reicast.emulator/.NativeGLActivity
  -d "{file.path}"
```

At least, that's my guess -- according to the log, that's the call Arc uses:

> 11-30 20:07:48.182   748  1680 I ActivityManager: START u0 {**act=android.intent.action.VIEW** dat=**/mnt/media_rw/1234567890/Roms/DC/Street Fighter III - 3rd Strike.gdi** flg=0x10000000 cmp=**com.reicast.emulator/.NativeGLActivity**} from uid 10064 from pid 21950 on display 0

Here it doesn't prefix the path `file://`, like most programs require, which is why I suspect that might be a solution.

As for the space suggestion, I was wondering if Reicast has prolems resolving the file path it receives. Technically when opening files, apps expect the path to be in a format similar to like site URLs, but instead of `https://` they start with `file://`. Spaces should be handled fine, but like with URLs, when you type in spaces or special characters, they tend to get converted to things like `%20` and such. I was wondering if somewhere Reicast silently replaces spaces with something weird (turning the path to `file:///mnt/media_rw/1234567890/Roms/DC/Street%20Fighter%20III%20-%203rd%20Strike.gdi`), but that's less likely to be the problem. Testing this however requires the `-d` part to be the original `-d "file://{file.path}"`.

Also thank you very much for the video, it's super helpful!

**Comment by valsou** [comment]
```
launch: am start --user 0
  -a android.intent.action.VIEW
  -n com.reicast.emulator/.NativeGLActivity
  -d "{file.path}"
```

It works for me with or without spaces and special characters. (Reicast 20.04, Android 10)

crazytaxi.chd = OK
Dead or Alive 2 v1.100 (2000)(Tecmo)(US)[!].chd = ok

**Comment by mikerealohs** [comment]
Hey! So, the -d portion of the intent/launch command from your support documents (auto launch code generator) vs the code you used in your repro is different. With that said, after trying the variation of the intent you used above (without the "file://" portion of the -d intent, and a device restart) Reicast now autolaunches all DC ROMs from Pegasus as named in the folder (with spaces), thank you! You may want to update your documents to reflect this... 😉😁
