### ISSUE TITLE
Games showing in duplicated in new version

### ISSUE THREAD

**Issue by rutantan** [mmatyas/pegasus-frontend#755]
### The issue

Since last version alpha14-36-g49dd98b3 the games are showing duplicated and sometimes triplicated. The list shows correctly in Alpha 14 (september version)

### System info

Windows 10 , 8GB ram, I3-6006

### Pegasus version

alpha14-36-g49dd98b3 

### Pegasus log

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5653085/lastrun.log)

![image](https://user-images.githubusercontent.com/22244900/101359622-4da93600-387b-11eb-97af-03a802675cde.png)

**Comment by mmatyas** [comment]
Does this also happen with the latest version (`alpha14-77-g67a80cf`)?

**Comment by rutantan** [comment]
I can confirm the problem still persists in newest
version alpha14-36-g49dd98b3
[image: image.png]

Em ter., 8 de dez. de 2020 às 11:04, Mátyás Mustoha <
notifications@github.com> escreveu:

**Comment by mmatyas** [comment]
Hm, isn't that the same version as in the first post? Could you try the latest version, released on (or after) 2020-12-12, called `alpha14-85-g6f801fbb`, available [here](https://github.com/mmatyas/pegasus-frontend/releases/download/continuous/pegasus-fe_alpha14-85-g6f801fbb_win-mingw-static.zip)?

If it still doesn't work, could you try disabling any additional data sources in the settings menu?
If that doesn't help, could you attach the metadata files/DAT files?

**Comment by rutantan** [comment]
I tested the version given in the link and it works fine.

Em qui., 17 de dez. de 2020 às 09:15, Mátyás Mustoha <
notifications@github.com> escreveu:
