### ISSUE TITLE
Issue with portable mode: Theme path is absolute.

### ISSUE THREAD

**Issue by hbCyber** [mmatyas/pegasus-frontend#763]
### The issue

When selecting a theme using NON-portable Pegasus, the `settings` file includes a relative path to the theme files. But when selecting a theme using PORTABLE Pegasus (`--portable`), the `settings` file includes an absolute path to the theme. In my opinion, it should remain a relative path (relative to the `pegasus-fe` executable). If you were to place all Pegasus files on a USB drive, if the theme's path is absolute, it preserves the drive letter which might change when you place the USB drive in another computer.

### System info

Using Windows 10 latest on a desktop computer.

### Pegasus version

alpha14-85-g6f801fbb

**Comment by mmatyas** [comment]
Hm, I tried reproducing this on both Windows 10 and Linux, but it seems to be working fine for me, and the theme path is relative as expected. I wonder if it's related to the USB drive? Does this still happen if you run Pegasus from the hard drives?

**Comment by hbCyber** [comment]
I am running it from a hard drive -- see the steps below I used to reproduce with Pegasus alpha14-85-g6f801fbb.

1. In the folder where **pegasus-fe.exe** resides, I make sure that the theme is stored within the **themes/** subfolder. In my case, I have **themes/gameOS-master/**.
2. Then, I execute Pegasus in portable mode: **pegasus-fe.exe --portable --disable-menu-reboot --disable-menu-shutdown**.
When I do that, a **config/** subfolder is created within the **pegasus-fe.exe** parent folder.
3. Within Pegasus, I access the settings UI to switch to the theme I have stored in **themes/**. For the sake of testing, I disable all data sources and add a single game folder which contains a **metadata.pegasus.txt file**.
4. After that, I check the **config/settings.txt** file, and this is where the absolute path of the theme is encoded. I strongly believe it should be a relative path.
![image](https://user-images.githubusercontent.com/7698618/107119560-69ed4180-68c3-11eb-959b-898daf0b3748.png)

**Comment by mmatyas** [comment]
I was trying to reproduce the issue, and everything worked fine, but then I noticed the difference! You've placed the themes in Pegasus/themes/, but they should be in Pegasus/**config**/themes/. This should fix the problem.
