### ISSUE TITLE
Genesis/Megadrive game descriptions not showing (all other metadata/assets working)

### ISSUE THREAD

**Issue by Deadfo0ls** [mmatyas/pegasus-frontend#764]
Hi, and thanks for reporting errors! You can help us locating the bug even more by providing detailed information in the sections below:

### The issue

The game descriptions for Megadrive aren't showing, all other metadata and assets including descriptions are showing correctly for psx and n64. I've compared the metadata.pegasus files for psx and megadrive and can see no differences that would be causing the issue.

### System info

Retropie on Rpi4 using game-os theme (issue on both game-os and pegasus main theme)

### Pegasus version

alpha14-87-g45353b0c

**Comment by Deadfo0ls** [comment]
Apologies this was down to user error

**Comment by Wilmatron** [comment]
What was the user error and how did you fix it? I appear to have the same problem with one of my collections... Cheers.

**Comment by Deadfo0ls** [comment]
> What was the user error and how did you fix it? I appear to have the same problem with one of my collections... Cheers.

It seemed to require the original gamelist.xml being present in the console folder along with the converted metadata.Pegasus.txt file it seemed like it was deciding to pull game descriptions from the gamelist file for some reason. I only had this issue with my Megadrive collection.
