### ISSUE TITLE
[Request] Add support for APNG

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#765]
Would be great if you were able to integrate this qt plugin: https://github.com/Skycoder42/QtApng

We could then implement support for images such as https://cdn.steamgriddb.com/hero/01c8a64a2b3c66c05c2dbf9df27510eb.png into themes.

**Comment by PlayingKarrde** [comment]
Also, on this note, having support for webp (https://www.programmersought.com/article/65711358710/) would also be fantastic.

**Comment by mmatyas** [comment]
Ok, both should be working now in the latest version! Two important notes however:

1. To make them animated in themes, you have to use the [`AnimatedImage` QML type](https://doc.qt.io/qt-5/qml-qtquick-animatedimage.html)
2. As mentioned at the linked repo, animated PNGs require the extension `.apng`

Have fun!

**Comment by PlayingKarrde** [comment]
Thanks!
