### ISSUE TITLE
Apps don't run on Pixel phones on android 11

### ISSUE THREAD

**Issue by rArcangel84** [mmatyas/pegasus-frontend#766]
Hi, and thanks for reporting errors! You can help us locating the bug even more by providing detailed information in the sections below:

I am using Pixel 3 XL to run Pegasus, the program loads, I am able to add, games metadata, and they populate, but when I hit play, they don't start. I tried running native android apps from inside the front end and it is the same, they don't start up. This also happens on my Pixel 4 XL, and 3a XL. 

Describe here what you've tried to do, what you've expected to see and what actually happens. If necessary, describe step-by-step the way to reproduce the problem.

I tried, installing stable version, but the same bug occurred, I factory reset my phone, thinking it was some type of setting, but no luck, I unlock my boot loader and install a custom rom, thinking it was some pixel rom issue, but same bug occurred, because when I run pegasus on my Galaxy Tab S6 the pegasus loads apps from within the program as intended. But I don't know if it due to the tablet running Android 10. 

Pegasus is available for many platforms, so please describe here where exactly you're using it, eg. "Windows 10 build 1234" or "Ubuntu 12.34". If it's not a desktop computer, or you see graphical glitches, please mention your hardware too, eg. "Debian Buster on a Raspberry Pi 4 with 2GB RAM", "Android 10 on SomePhone XY7", etc.

Android 11, December 5 security update, Pixel XL 3, 3a, 4

When you open the main menu of Pegasus you can see it in the bottom left corner of the screen. Also, have you tried the latest version? It might already have a fix for the problem!

Pegasus version alpha14-87 12/17/2020
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5756555/lastrun.log)

You can find a log file with detailed information about the launch of Pegasus under the following locations:

- Windows: `C:\Users\[username]\AppData\Local\pegasus-frontend\lastrun.log`
- Linux: `~/.config/pegasus-frontend/lastrun.log`
- macOS: `~/Library/Preferences/pegasus-frontend/lastrun.log`
- Android: `<storage>/pegasus-frontend/lastrun.log`
- portable mode: `<directory of the program>/config/lastrun.log`

If possible, please attach the file to this bug report.

**Comment by rArcangel84** [comment]
I tried downgrading to android 10 lastest, and now the apps do launch from within pegasus but when i try to new paths to ad games pegasus does not see files on SD card (internal or external)

**Comment by turboboy215** [comment]
I have the same problem. Will there ever be a solution?

**Comment by rArcangel84** [comment]
I forgot to write this, but I managed to make it work on my Pixel device. The only downside is that, I had to downgrade to Android 9, which is somewhat easy with google online tools. But still no luck with android 10 nor 11

**Comment by mmatyas** [comment]
Confirmed the bug on Android 11, it seems the apps no longer have permission to access the Activity Manager (`am`), and the shell in general, by launching it as a process. The Android log says:

`ActivityTaskManager: Permission Denial: package=com.android.shell does not belong to uid=[Pegasus UID]`

It seems this is a restriction of the system, and not the apps, so Pegasus can't ask the Android system for permission either. Unfortunately I haven't found a workaround yet; will keep the issue open until then.

**Comment by kmk709** [comment]
android is getting closed now

**Comment by rArcangel84** [comment]
> android is getting closed now

What do you mean by this?

**Comment by Keltron3030** [comment]
Glad I found this issue so I know I'm not the only one.  Confirmed the same problem with Android 11 on a Samsung S20.  Hopefully a fix will be possible.

**Comment by null-von-sushi** [comment]
If this is something that can be done using ADB permissions, you could use [Shizuku](https://github.com/RikkaApps/Shizuku) maybe? This only requires adb and a wifi network to be available on Android 11 when the device boots up. After that any apps can use this as a framework to access ADB functionality. It does not necessarily require a PC to use for end user.

**Comment by mmatyas** [comment]
I think it might be possible to resolve this on Pegasus' side; in general it'd be nice to not require root permission, but in the worst case that project could be indeed useful.

**Comment by nuitezero** [comment]
Amy new for this? I have same probleme with my samsung on android 11

**Comment by mmatyas** [comment]
Not yet, but will update this thread when there are possible improvements.

**Comment by wearetop34** [comment]
I love this frontend so much and no app can replace this.
I use android 11 phone (Poco X3 Pro) and not work as well. Do you have another method to start emulator?

**Comment by mmatyas** [comment]
Hi, as far as I know, no, because the whole app launching itself works differently on Android 11. But don't worry, this issue wasn't forgotten!

**Comment by fokhei** [comment]
I have the same problem with my Samsung Note 10+ on Android 11.

I also really like the frontend with fully customizable configuration that no other app can replace.

Since this problem has been going on for 7 months, I implore you to fix it as much as possible, please please please please !!!!. 😭

**Comment by wearetop34** [comment]
Is this issue solve?

**Comment by mmatyas** [comment]
No, not yet;, I'm working on it. If everything goes well there might be some results next week.

**Comment by mmatyas** [comment]
Ok, I've rewrote the app launching in the latest version (alpha15-26-gfce59744), give it try!

**Comment by Ghostpayne1** [comment]
Got an error when attempting to launch a game 
Samsung Galaxy Tab S7 on Android 11
![Screenshot_20210810-000235](https://user-images.githubusercontent.com/88706143/128823270-5aca9e00-8766-4ca8-ad2f-4214430067a2.jpg)

**Comment by mmatyas** [comment]
Oh my, not even the file paths are safe anymore.

Could you try adding the `--grant-read-uri-permission --grant-write-uri-permission` parameters to the launch command?

**Comment by Ghostpayne1** [comment]
Got it, please let me know if I did something incorrectly.
![Screenshot_20210810-002044_FX](https://user-images.githubusercontent.com/88706143/128825213-70b2e836-f703-47ae-b68a-36ade2971c3f.jpg)
![Screenshot_20210810-002101](https://user-images.githubusercontent.com/88706143/128825235-968f29de-e7f0-4d40-8448-8bb24c53936d.jpg)

**Comment by mmatyas** [comment]
Yes, the command looks fine; I guess some more work is necessary for paths then.

**Comment by mmatyas** [comment]
Hm, could you try removing the `file://` part from the path? If that doesn't work, could you replace it with `content://`?

**Comment by Ghostpayne1** [comment]
Awesome, removing file:// worked!

**Comment by wearetop34** [comment]
It's worked now. Thank you very much.
I don't use command "--grant-read-uri-permission --grant-write-uri-permission" 

MIUI 12.5 on Poco X3 Pro

**Comment by rArcangel84** [comment]
Great! I am glad to hear the problem was solved. What would be the final command to use? Thank you

**Comment by wearetop34** [comment]
I use command for retroarch emulator generated on https://pegasus-frontend.org/tools/metagen-android/

**Comment by mmatyas** [comment]
I think this can be closed then. Pegasus uses the standard Android communication method, so as long as the target app supports launching in some form, things should continue to work.
