### ISSUE TITLE
Libgstapp-1.0 missing on Raspberry OS 64-bit

### ISSUE THREAD

**Issue by elliot-sawyer** [mmatyas/pegasus-frontend#769]
### The issue

The program immediately fails to load on a 64-bit OS: `./pegasus-fe: error while loading shared libraries: libgstapp-1.0.so.0: cannot open shared object file: No such file or directory`

### System info

I'm running the beta 64-bit Raspberry OS with RetroPie on a Pi4. I tried installing via RetroPie setup and the latest stable release (alpha14-85-g6f801fbb (2020-12-17)). I'm not sure what version RetroPie-Setup installed.

### Pegasus log

The program fails to execute, there are no logs.

**Comment by mmatyas** [comment]
Hm, in theory the RetroPie setup should have installed the dependencies for you, but you can also install them manually like this:
```
sudo apt-get install fontconfig gstreamer1.0-alsa gstreamer1.0-libav gstreamer1.0-plugins-good libsdl2-dev policykit-1
```

**Comment by mmatyas** [comment]
Confirmed on the 2020-08-24 version of the 64-bit Raspberry Pi OS. As the official binary releases of Pegasus target the official 32-bit Raspbians, it can most likely only link to the 32-bit libraries, which are not available for the 64-bit OS. The solution is either compiling Pegasus for the 64-bit Raspberry OS, like with all custom platforms, or using the regular 32-bit system image on the Pi.
