### ISSUE TITLE
[Launchbox] Steam media integration

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#770]
Launchbox has the ability to download steam media (images, posters, logos, videos etc) but it classifies them as Steam specific (ie it has Box Front but also Steam Poster, or Screenshots - Gameplay but also Steam Screenshots). 

Ideally Pegasus LB integration should grab those specific assets and add them to the list of images for that title (for example add Steam Screenshots to the assets.screenshots model so they don't need to be retagged within Launchbox).

**Comment by mmatyas** [comment]
Could you attach the Data directory of LaunchBox, and any relevant directories that contain Steam-related assets, as an example config?

**Comment by mmatyas** [comment]
Ok, this should now work in the latest version!

**Comment by PlayingKarrde** [comment]
Oh thanks! Sorry I forgot to respond to your request!
