### ISSUE TITLE
Multiple errors trying to build with QT Creator

### ISSUE THREAD

**Issue by nechrobyte** [mmatyas/pegasus-frontend#772]
### The issue

Hi, hope im not breaking any rule by posting this here.

The issue is that i´ve been trying to build Pegasus Frontend for Android, read the documentation and installed all the requirements, then cloned the source recursively, configured Android SDK, JAVA JDK, OpenSSL and finally load and click "RUN" the project with QT Creator, i've alredy tried QT 5.14, 5.9 and 5.15.2. 

The result is always the next compiling error:

qmlimportscanner: No such file or directory: "home/nechrobyte/pegasus-frontend/src/app/qmake_qmake_qm_files_qrc"
Invalid json output from qmlimportscanner
The process "/home/nechrobyte/Qt/5.14.0/android/bin/androiddeployqt" exited with code 4.
Error while building/deploying project pegasus (kit: Android Qt 5.14.0 Clang Multi-abi)
When executing step "Build Android APK"

### System info

Tried with two different Desktop Systems, Windows 10 64-bit and Linux Mint 64-bit

**Comment by mmatyas** [comment]
Hm could you take a look on the build settings (Projects -> [Your Android kit] -> Build)? It should look like this:

![image](https://user-images.githubusercontent.com/4354863/104289586-9a56e100-54b9-11eb-9b68-b03a512083ba.png)

Also make sure *Build .aab* is turned off under *Build Android APK* too.

**Comment by nechrobyte** [comment]
Thanks for replying :) 

I'm checking it right now, build Android aab is unchecked but under "Efective qmake call i have a single difference, instead of "qmldebug" i have "qtquickcompiler"

Maybe it's something related to this, thanks again :)

**Comment by mmatyas** [comment]
Have you had any luck with the compilation since then?

**Comment by mmatyas** [comment]
Feel free to comment if there are still build issues.
