### ISSUE TITLE
Lutris Assets and Metadata

### ISSUE THREAD

**Issue by peppy6582** [mmatyas/pegasus-frontend#778]
### I know support for this was added, but where do you put the files?  Thanks

**Comment by mmatyas** [comment]
Hi, Lutris games are handled by the Lutris client, which should automatically download images for them. Other than that you can't define additional assets and metadata in metafiles *yet*, but I'd like to add support for that too.

**Comment by peppy6582** [comment]
Thanks!  Great software by the way.

**Comment by mmatyas** [comment]
I think this should work now; you can reference Lutris games in metadata files with the filename format `lutris:your-game-slug-here`.
