### ISSUE TITLE
Xbox Series controller double inputs on Windows version

### ISSUE THREAD

**Issue by onylith** [mmatyas/pegasus-frontend#783]
### The issue

Pegasus sees two inputs (except when using the dpad) when connecting the new Xbox Series X/S (XSX/S) controller via Bluetooth on Windows 10. Two controllers show up in the controller configuration menu: XInput controller and Bluetooth LE Xinput compatible device.

**Steps to reproduce:**

1. Connect XSX/S controller to Windows 10 PC through Bluetooth
2. Open Pegasus
3. Press buttons on the controller
4. Observe double inputs

### System info

Windows 10 build 1909

### Pegasus version

alpha14-107-gea74090b

### Log file

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5907764/lastrun.log)

**Comment by onylith** [comment]
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5907757/lastrun.log)

**Comment by mmatyas** [comment]
Hi, does Windows itself also see two separate gamepads? Do other programs also see two gamepads?

**Comment by onylith** [comment]
No. Doesn't happen in Steam Big Picture or games, just Pegasus.

**Comment by onylith** [comment]
As of the weekly update released today, the controller is recognized as a different device named "Xbox Series controller", but the double input issue still persists (there is still another input device called "XInput device" while I only have one controller connected).

**Comment by mmatyas** [comment]
I've just updated the gamepad support in the latest release. Could you check if it improves the gamepad detection for you?

**Comment by mmatyas** [comment]
Closing in favor of #799.
