### ISSUE TITLE
Pegasus-frontend versioning scheme

### ISSUE THREAD

**Issue by SupervisedThinking** [mmatyas/pegasus-frontend#785]
Well could you start to use versions like `Major.Minor.Patch` for your releases?

**Comment by mmatyas** [comment]
Hi, no, there are no plans for that at the moment. If you need to have a version in that format, like for packaging, you can convert the `alpha12-345` format to `0.12.345` if necessary.

**Comment by Korb** [comment]
> Well could you start to use versions like Major.Minor.Patch for your releases?

+1

> SupervisedThinking closed this as completed on Feb 2, 2021

Probably, in this case, it was necessary to choose "not planned"?
