### ISSUE TITLE
Add command to launch Android DuckStation PSX emulator

### ISSUE THREAD

**Issue by turboboy215** [mmatyas/pegasus-frontend#788]
Hi, I noticed this emulator is missing from the Android configuration generator, and I have tried to launch it using special commands. However, I have been unsuccessful to actually get the emulator to start. No matter what I try, it either just goes back to the Pegasus frontend or launches the app, but doesn't start a game.
https://github.com/stenzek/duckstation/issues/1579
The above page lists several parameters to start up the emulator with a game, but I am unable to find out how these exactly equate to Pegasus frontend commands; everything I tried results in no success.
I apologize if this is in the wrong section, but I couldn't find anything about missing emulator configurations.

**Comment by valsou** [comment]
Hi,

here is the lauch command :

```
launch: am start --user 0
  -n com.github.stenzek.duckstation/.EmulationActivity
  -e bootPath "{file.path}"
  --ez resumeState 0
```

`-e key string_value` for bootPath extra parameter.
`--ez key boolean_value` for resumeState extra parameter; set `1` if you want to boot at your last save state, `0` otherwise.

**Comment by turboboy215** [comment]
Thank you! This should now be added to the config editor.
