### ISSUE TITLE
Support for multiple commands at metadata.txt

### ISSUE THREAD

**Issue by ludg1e** [mmatyas/pegasus-frontend#789]
Add the posibility to run more than 1 command at metadata.txt please.

**Comment by mmatyas** [comment]
Sorry for the late reply! If you'd like to run multiple commands you can always just put them into a single script and launch that. With multiple launch commands properties like execution order and exception handling also have to be dealt with, so using proper scripts or the system's interpreter usually provides a more versatile solution.

**Comment by ludg1e** [comment]
I understand, thanks for the reply!
