### ISSUE TITLE
Add system status placeholders

### ISSUE THREAD

**Issue by ludg1e** [mmatyas/pegasus-frontend#791]
Add system status placeholders like in RetroArch.
![image](https://user-images.githubusercontent.com/77110723/107151521-509bd200-6963-11eb-8c68-b9939945de9a.png)

**Comment by mmatyas** [comment]
If I see it correctly, you'd like to have

- the current date and time
- the current battery level

usable in themes, right? The first one is already possible, we're only missing the battery at the moment.

**Comment by ludg1e** [comment]
Yes, it could be cool if it's customizable with themes, that would give more information of the system without needing to quit Pegasus.

**Comment by mmatyas** [comment]
Ok, this should now work in the latest version! See the [API documentation](https://pegasus-frontend.org/docs/themes/api/#device) for more info.
