### ISSUE TITLE
Video Snaps Play Green

### ISSUE THREAD

**Issue by convolutionbbs** [mmatyas/pegasus-frontend#793]
### The issue

When I run Pegasus the videos start to play but they are all green.  The audio does play properly.  I can watch the mp4 videos (from screenscraper.fr) using VLC ok.  Example codec is H264-MPEG-4 AVC (part 10)(avc1).

### System info

POP OS 20.10, 64 bits.  Pegasus 0.14.110 installed from the apt repository as described on the installation page.  I also followed all the linux ubuntu prerequisite installs as described here: https://pegasus-frontend.org/docs/user-guide/platform-linux/.

### Pegasus version

Pegasus alpha14-110-g89e3693b (2021-02-04)

### Pegasus log

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/5978418/lastrun.log)

**Comment by mmatyas** [comment]
Hi, could you share an example video that fails to play? Have you tried installing additional sets of gstreamer plugins (`-ugly`, `-bad`)?

**Comment by mmatyas** [comment]
Closing until further activity.
