### ISSUE TITLE
mp4 videos with MPEG-2 Layer 3 format audio won't play

### ISSUE THREAD

**Issue by Bonk-Choy** [mmatyas/pegasus-frontend#797]
Hi,

### The issue
mp4 video files with MPEG-2 Layer 3 format audio won't play in Pegasus as game previews. I tried to remove the audio track, and it worked. But if I remove the video track and leave only the audio track in the mp4 file, it won't play. The same videos (mostly less than 5MB) can play in VLC and Kodi without any issues.

### System info
Nvidia Shield TV Pro 2019

### Pegasus version
Android alpha14-110-g89e3693b

### Pegasus log
The only warning or error messages:
2021-02-16T23:01:28 [w] qt.gui.icc: fromIccProfile: failed minimal tag size sanity
2021-02-16T23:01:28 [w] qt.gui.icc: fromIccProfile: failed minimal tag size sanity

Thanks

**Comment by mmatyas** [comment]
Hi, does the video work well in Android's default video viewer, eg. Gallery? Also some devices don't support certain MPEG formats, due to licensing or incomplete codec implementation; would it be possible for the Shield to have such issues?

**Comment by Bonk-Choy** [comment]
> Hi, does the video work well in Android's default video viewer, eg. Gallery? Also some devices don't support certain MPEG formats, due to licensing or incomplete codec implementation; would it be possible for the Shield to have such issues?

Thanks for the comment! Yes, the gallery app has the same issue. Does Pegasus call the gallery app to play videos?

**Comment by mmatyas** [comment]
Both the Gallery app and Pegasus use Android's built-in support for playing videos, so in this case it seems the system on the Shield doesn't come with support for this particular format.

**Comment by mmatyas** [comment]
I guess this can be closed, in favor of eg. #347.
