### ISSUE TITLE
[Regression] Launchbox game images without numerical suffix aren't loaded

### ISSUE THREAD

**Issue by HVR88** [mmatyas/pegasus-frontend#802]
### The issue

Image files without numerical suffix, such as "-01" aren't being loaded by Pegasus.

LB typically marks all images starting with "-01", however other tools, such as Skraper will save images without such a suffix. Launchbox itself seems to pull up and use these images, but the same images will not appear in Pegasus.

I see this was previously mentioned as fixed in Alpha 14 from September 2020.

### System info

Windows 10, Launchbox 11.9, Pegasus build Feb 19 2021, running gameOS theme 1.10

**Comment by HVR88** [comment]
Additional info:

While Launchbox will also convert all filesystem-illegal characters and apostrophe to an underscore in all the media it downloads from its own server and EMUMovies, it will happily load media that follows a No-Intro style naming convention.

Example:
An image for "Title: Subtitle's Curse" named "Title - Subtitle's Curse.jpg" instead of "Title_ Subtitle_s Curse-01.jpg"

Characters within parenthesis are also ignored, so LB will pick up a file even if it has something like "(USA)" or "(v1.1 Europe)" in the filename.

**Comment by mmatyas** [comment]
Ok, this should be now fixed in the latest version!
