### ISSUE TITLE
Launchbox Platform Sort titles not being used

### ISSUE THREAD

**Issue by HVR88** [mmatyas/pegasus-frontend#803]
In Alpha 14 from Sept 2020, "Sort order" is mentioned as addressed, but not specifically what was changed.
 >    Fixed sort title not being set in some cases

### The issue

Sort order for platforms set in Launchbox not being reflected/honored in Pegasus.

For example, all Nintendo platforms (collections) are coming up in Alphabetical order for me instead of the custom order according to their sort tags. This means "Nintendo 64" shows up first.

In Launchbox, I have each platform with a custom sort order like this: "Nintendo ####" where "####" is the release year of the console.  In LB this has the effect of creating the following order:

Nintendo Entertainment System
Super Nintendo
Nintendo 64
Nintendo GameCube
etc...

### System info

Windows 10, Launchbox 11.9, Pegasus build Feb 19 2021, running gameOS theme 1.10

**Comment by mmatyas** [comment]
Sorry for the late reply! Yes, the fixed sort order was actually about the metadata files; at the moment LB's sort names are indeed not used, but I think I can add support for that.

**Comment by HVR88** [comment]
That would be great and much appreciated. 

To be honest, I'm using the Launchbox integration for a few reasons, but if you suggest otherwise (if it's better or faster to use the native xml files), I'll move to a different method.  First is that I have already been using Launchbox to manage my collection for over a year. Second is that it's simple/convenient to have a GUI to make some changes to metadata or even emulator launch string, and then see them reflected automatically in Pegasus.

**Comment by mmatyas** [comment]
Ok, this should work now in the latest version!
