### ISSUE TITLE
Get Mupen64plus working on Linux

### ISSUE THREAD

**Issue by retrowaldo** [mmatyas/pegasus-frontend#804]
I use an Ubuntu based Linux operating system and have not been able to configure the Mupen64plus (Nintendo 64) to start Using the Pegasus Fronted. Can you tell me what configuration I should use for the Mupen64plus Emulator to work.
Put the following in the metadata and it doesn't work:

collection: Nintendo 64
shortname: n64
summary:
  N64 It is a Nintendo 64 Games emulator
extensions: bin, n64, u1, v64, z64, zip
launch: mupen64plus "{file.path}"

Could you give me any suggestions. Thanks a lot...

**Comment by mmatyas** [comment]
Hi, are you using `mupen64plus-ui-console`? According to the help page, the launch command seems to be correct; does it work if you run a game like that from the command line? If it does, could you post the log file of Pegasus? You can find it at `~/.config/pegasus-frontend/lastrun.log`.

**Comment by mmatyas** [comment]
I think this got resolved on Discord, right? Will close the issue then.
