### ISSUE TITLE
Menu bar on mac remains hidden when fullscreen is disabled

### ISSUE THREAD

**Issue by JeffersonBledsoe** [mmatyas/pegasus-frontend#805]
Hi, and thanks for reporting errors! You can help us locating the bug even more by providing detailed information in the sections below:

### The issue

When disabling fullscreen mode on mac, the menu bar remains hidden, whereas the behaviour with most apps is for the menu bar to return (whether the app use the menu bar or not). The attached video shows that as long as pegasus is the focused window, the menu bar is hidden, whether fullscreen is enabled or not. Changing between the `Finder` app and pegasus shows the menubar hiding when pegasus is focused and return once it loses focus.

https://user-images.githubusercontent.com/30210785/109699650-ba855100-7b88-11eb-80dd-ed189e3af5b4.mov

### System info

macOS 10.15.7 & macOS 11.x

### Pegasus version

pegasus-fe_alpha14-113-g9abf0653

**Comment by mmatyas** [comment]
Thanks for the video! Could you try if this version works as expected, in both full screen and windowed mode?

[pegasus-fe_issue805.zip](https://github.com/mmatyas/pegasus-frontend/files/6092365/pegasus-fe_issue805.zip)

**Comment by JeffersonBledsoe** [comment]
@mmatyas Works great! Still appears on-hover when in fullscreen, but stays on-screen when in windowed mode.

**Comment by mmatyas** [comment]
Good to hear! Does it work as expected from a Mac app? Like, does the menu bar appear on hover in say, full screen games too?

**Comment by mmatyas** [comment]
Pushed the changes anyway, this should be fixed now in the latest version.

**Comment by JeffersonBledsoe** [comment]
@mmatyas Sorry for the radio silence on this. Everything all seems to behave correctly :) Thanks for the quick fix!
