### ISSUE TITLE
Crashes when moving mouse

### ISSUE THREAD

**Issue by JIntenzo** [mmatyas/pegasus-frontend#807]
so i JUST downloaded the most recent stable version of Pegasus and while its open it either crashes instantly or crashes when i move/click my mouse.

**Comment by mmatyas** [comment]
Hi, could you give some more details about your setup? [Here are some guidelines for bug reports.](https://github.com/mmatyas/pegasus-frontend/blob/master/.github/ISSUE_TEMPLATE/bug.md)

**Comment by JIntenzo** [comment]
Im using Windows 10 Build 19041
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/6095781/lastrun.log)

**Comment by mmatyas** [comment]
Thanks! The `DirectShow` error at the bottom indicates that might be related to the videos. Have you installed any codecs or codec packs? Take a look at this for more info: https://pegasus-frontend.org/docs/user-guide/platform-windows/#multimedia-support

**Comment by JIntenzo** [comment]
same thing heres the log incase something changed
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/6096111/lastrun.log)

**Comment by mmatyas** [comment]
Hm, according to the log you still have codec issues:

`2021-03-06T15:13:52 [w] DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()`

The 0x80040218 part means missing DirectShow filters. Try installing K-Lite Basic, or, if that doesn't help, `opencodecs_0.85.17777.exe` from here: https://www.xiph.org/dshow/.

**Comment by JIntenzo** [comment]
Sorry about the late reply, but this seems to have fixed it, thanks!
