### ISSUE TITLE
A Few Features

### ISSUE THREAD

**Issue by JIntenzo** [mmatyas/pegasus-frontend#812]
So I've been trying to look for a frontend that will fit my needs and pegasus looked great but is missing a couple of things I would love,
1. The ability to add your own exe files to pegasus
2. The ability to create your own categories and put your own games/exe files into them
3. The ability to toggle whether videos auto-play or not

**Comment by JIntenzo** [comment]
also to add custom artwork and videos to games (like steam does)

**Comment by mmatyas** [comment]
Hi, these are all possible, take a look at this example: https://pegasus-frontend.org/docs/user-guide/platform-windows/#launching-desktop-games

The *ability to toggle whether videos auto-play or not* depends on the theme, the default one doesn't have this yet, but I think gameOS, for example, does support it.

**Comment by JIntenzo** [comment]
i think im in love with pegasus now, thank you

**Comment by JIntenzo** [comment]
but I would also like it to be easier to add exe files, I have no idea what I'm doing

**Comment by mmatyas** [comment]
EXE files are treated just like any other file type. For metadata files you can find the documentation here: https://pegasus-frontend.org/docs/user-guide/meta-files/

**Comment by HVR88** [comment]
> but I would also like it to be easier to add exe files, I have no idea what I'm doing

The easiest way to provide Pegasus with all the data it needs is to use a different management front end to sort your games and media assets, plus set up your emulators and their launch parameters, then allow Pegasus to use that front end's data.

And the best of the bunch is LaunchBox. That will get you up and running quickly and make it easy to continually modify your collection without having to remake or manually edit any xml files.  

Later if you'd like to remove the dependency on LB, you can look into generating the xml files and sorting media assets for Pegasus yourself.

**Comment by JIntenzo** [comment]
thanks but the guide gave me everything i need
