### ISSUE TITLE
Expose custom metadata using the `x-` syntax to themes

### ISSUE THREAD

**Issue by JeffersonBledsoe** [mmatyas/pegasus-frontend#815]
Metadata files allow for custom metadata to be read by pegasus by prepending `x-` to the metadata key, as mentioned in the [metadata documentation](https://pegasus-frontend.org/docs/user-guide/meta-files/#metadata). However, these keys are not currently exposed to themes through the pegasus theme API. Exposing these keys through the theme API would allow developers to expose functionality through the end-users metadata file.

**Comment by JeffersonBledsoe** [comment]
@mmatyas Would the API for this essentially be having any `x-` metadata be available to the games and collections returned by `api.collections` and `api.allGames`?

**Comment by mmatyas** [comment]
Yes, all games and collections would have an `extra` field, a JS object where each metadata key would be a property (without the `x-`), and the values would be arrays of strings for each line of the metadata field.

**Comment by mmatyas** [comment]
I've just ended up adding this feature, should work now in the latest version! (Though it's not heavily tested yet.)

**Comment by msheehan79** [comment]
@mmatyas Sorry to post on an old issue, but I didn't want to open a new issue for what is more of a development question.

Is there any "efficient" way to sort/filter on values in the `extra` field via the SortFilterProxyModel?  

During my testing, the only way I was able to access values stored in the extra Object was to use an ExpressionRole or ExpressionFilter, but the performance hit was significant as the collection size grew (maybe an extreme example but I had about 17k entries and adding the ExpressionFilter increased load time by ~10 seconds).

Just wanted to run this by you in case you were aware of a way to access these attributes for filtering or if the ExpressionFilter is really the only option to get to these child values.

**Comment by mmatyas** [comment]
Hm that's a good question. As far as I know ExpressionRole evaluates a JS expression for each row, which is what makes it slow; if possible, perhaps a selectively enabled ValueFilter, or a chain of them would work better? SortFilterProxyModel wasn't made by me, so I'm not exactly sure where are the performance bottlenecks, I'll see if I can try it with a large data set.
