### ISSUE TITLE
Games defined in metadata but file not present in folder are showing up

### ISSUE THREAD

**Issue by msheehan79** [mmatyas/pegasus-frontend#818]
I have been running build 89e3693bce7aea445df68bec04a74c583e557d9e (2/4) without issues, upgraded to today's new build to check out the new support for extra metadata files. 

When I upgraded, I noticed that game entries that I have defined in the metadata.txt file but that the game file is not located still show up in the theme. With prior builds this was not the case, those files would not show up in the list.

So in the example below, on my PC I only have 4 game files in the folder, but I do have metadata entries defined for many more. The expected behavior is I should only see those 4 games and it has worked that way previously. With the new change I see all entries in the folder but only the filename - no assets or metadata is shown for the missing games, only those entries where a game file actually exists show up normally.

**Current build:**
![image](https://user-images.githubusercontent.com/1565622/111400234-4a54f000-869d-11eb-9d0f-729393dc1670.png)

**Previous build - no changes to the metadata or files:**
![image](https://user-images.githubusercontent.com/1565622/111400271-5e005680-869d-11eb-93be-c6998ebe79c4.png)

This is on Windows 10 x64. 

### Pegasus version
Error noticed with build b8f8a4310cb8bb137dd3c311236e5361336c126c

Pegasus is configured in portable mode with all metadata files stored in the /config/metafiles folder.
All game metadata is stored in a single file (games.metadata.txt) and I have several collection files that only store the files. Since its a rather large file I'll include a snippet of the metadata format I am using, and the collection file format:

Metadata example
-----
game: 007: Quantum of Solace
file: ..\..\..\roms\wii\007 Quantum of Solace [RJ2E52].rvz
sort-title: 007: Quantum of Solace
release: 2008
developer: Beenox Studios
publisher: Activision
genre: Action
players: 4
x-system: wii
rating: 
description: James Bond is back to settle the score in the Quantum of Solace? game. Introducing a more lethal and cunningly efficient Bond, the game blends intense first-person action with a unique third-person cover combat system that allows players to truly feel what it is like to be the ultimate secret agent as they use their stealth, precision shooting and lethal combat skills to progress through missions.
launch: "..\..\..\launch\Dolphin.cmd" "{file.path}" "dolphin" "wii\btpass" "" "" "{file.basename}"
x-controller: Wiimote + Nunchuk
x-emucontroller: Wiimote + Nunchuk
assets.boxFront: ..\..\..\artwork\wii\media\box2dfront\007 Quantum of Solace [RJ2E52].jpg
assets.logo: ..\..\..\artwork\wii\media\wheel\007 Quantum of Solace [RJ2E52].png
assets.screenshot: ..\..\..\artwork\wii\media\screenshot\007 Quantum of Solace [RJ2E52].jpg
x-gameid: 19631
tag: CustomSort:007:190

game: A Boy and his Blob
file: ..\..\..\roms\wii\A Boy and His Blob [SBLE5G].rvz
sort-title: A Boy and his Blob
release: 2009
developer: Wayforward Technologies
publisher: Majesco
genre: Platform
players: 1
x-system: wii
rating: 
description: The far-off kingdom of Blobolonia is threatened by an evil emperor.  An alien blob escapes from Blobolonia, searching for help, and he crash lands on planet Earth.  There he finds a young boy.  Help the pair save Blobolonia from the Emperor's tyrannical reign!
  .
  .
  A Boy and his Blob is based on David Crane's Nintendo game of the same name.  As the nameless Boy, you have control over an alien blob who can transform into different objects when you feed him different flavored jellybeans.  The transformations are usually based on puns (for example, punch is a hole, apple is a jack and licorice is a ladder) or similar sounding names (such as tangerine trampoline and pear parachute).  Using the different tools that Blob can transform into, it's up to the player to reach the exit door at the end of each level.
  .
  .
  Each level also has three hidden treasure chests in it.  If all three are found, a bonus level is unlocked.  The bonus levels are Challenge Levels, which are more difficult, and often based around using a specific skill or jellybean flavor.  Completing these levels unlocks special rewards such as concept art, videos and new game modes.
launch: "..\..\..\launch\Dolphin.cmd" "{file.path}" "dolphin" "wii\btpass" "" "" "{file.basename}"
x-controller: Wiimote + Nunchuk / Classic Controller
x-emucontroller: Wiimote + Nunchuk / Classic Controller
assets.boxFront: ..\..\..\artwork\wii\media\box2dfront\A Boy and His Blob [SBLE5G].jpg
assets.logo: ..\..\..\artwork\wii\media\wheel\A Boy and His Blob [SBLE5G].png
assets.screenshot: ..\..\..\artwork\wii\media\screenshot\A Boy and His Blob [SBLE5G].jpg
x-gameid: 19632

Collection File Example
----

collection: Nintendo Wii
shortname: wii
summary: System
extensions: wbfs, rvz
launch: "..\..\..\launch\Dolphin.cmd" "{file.path}" "dolphin" "" "" ""
x-shortname: wii
sort-by: 1 - Nintendo Wii

file: ..\..\..\roms\wii\007 Quantum of Solace [RJ2E52].rvz
file: ..\..\..\roms\wii\A Boy and His Blob [SBLE5G].rvz
file: ..\..\..\roms\wii\Action Girlz Racing [RGYE5Z].rvz
file: ..\..\..\roms\wii\Aladdin Magic Racer [SARE4Z].rvz
file: ..\..\..\roms\wii\Alice in Wonderland [SALE4Q].rvz

**Comment by mmatyas** [comment]
Hi, just to make sure, the following files do not exist, right?

file: ..\..\..\roms\wii\007 Quantum of Solace [RJ2E52].rvz
file: ..\..\..\roms\wii\A Boy and His Blob [SBLE5G].rvz
file: ..\..\..\roms\wii\Action Girlz Racing [RGYE5Z].rvz

What happens when you try to launch them? Could you attach the log file?

**Comment by msheehan79** [comment]
Right, those files are not present. I have a "master" metadata file basically and add/remove files from the rom folder, much easier than trying to make sure the metadata file matches the contents of each folder exactly.

I will try and launch and send you the log info this evening.

    On Thursday, March 18, 2021, 3:25:25 PM EDT, Mátyás Mustoha ***@***.***> wrote:  
 
 


Hi, just to make sure, the following files do not exist, right?

file: ......\roms\wii\007 Quantum of Solace [RJ2E52].rvz
file: ......\roms\wii\A Boy and His Blob [SBLE5G].rvz
file: ......\roms\wii\Action Girlz Racing [RGYE5Z].rvz

What happens when you try to launch them? Could you attach the log file?

**Comment by msheehan79** [comment]
When I launch, the logfile looks normal and exits cleanly, but I get this popup.

I've attached a logfile for reference (I truncated it for [size).]

![image](https://user-images.githubusercontent.com/1565622/111689911-f49a5800-8802-11eb-9841-1f50a6358838.png)

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/6166911/lastrun.log)

**Comment by mmatyas** [comment]
Ok, this should work now in the latest version, could you try it out?

**Comment by msheehan79** [comment]
Just tried the latest build and things are back to working as they were before - thanks for the quick fix for this!
