### ISSUE TITLE
Option to allow files that don't exist

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#825]
When adding games, Pegasus understandably ignores games it doesn't find. This, however, has the knock on effect of not allowing games that are run via url (for example steam://rungameid/588650 or xbox://Innersloth.AmongUs_fw5x688tam7rm) meaning unnecessary extra steps are required to work around this (ie making batch files containing these links instead). 

If the user had the option to allow missing games it would allow for more power user options.

**Comment by mmatyas** [comment]
Yes, this is actually somewhat related to #814 too; I'm working on adding support for such URLs from all the sources.

**Comment by HVR88** [comment]
Does Pegasus currently verify the existence of the ROM/Data at startup when parsing LB's metadata?  That can't be good for performance.

I keep all my disc-based games on the LAN and Pegasus currently takes a very long time to start up when using LB's metadata. If not checking the ROMs can improve that speed, I'd really prefer that option. If I have the metadata, then I would really expect to see the title displayed, even if I'd later get the emulator complaining about file not found trying to launch something that's missing.

**Comment by mmatyas** [comment]
Yes, for non-Steam LB games the paths are checked too, though that may or may not be the reason for a slowdown. If someone shares a huge LB setup, I'm happy to measure loading times with more detail.

**Comment by HVR88** [comment]
I'll make some time by the end of the weekend to put up a full metadata archive for you.

**Comment by HVR88** [comment]
@mmatyas here's my whole LB Data folder as I've been using to test Pegasus.

http://salumba.com/launchbox_data.7z

**Comment by HVR88** [comment]
Can you let me know if you've checked the files attached? If you need more information or would like me to profile anything on this end, I'm happy to offer whatever assistance I can.

As I'm cleaning up my collection, it's up to just over 16000 files at the moment - I'm keeping all ROM images stored on my NAS. This has the effect of over 2 minutes startup time for Pegasus. I will eventually move to using metadata.xml files without Launchbox integration to compare speed.

**Comment by PlayingKarrde** [comment]
That's interesting as my LB startup is super small compared to when I use Pegasus metadata files (exported from LB using Pegasus Exporter). My files are also on my NAS. I'll have to retest though as this was a while ago (I also don't have even close 16000 files but the difference in speed was extremely noticeable).

**Comment by mmatyas** [comment]
Sorry, I haven't had the time recently to work on this (or the rest of the issues). I do have the file saved, just haven't got around to measure the performance.

**Comment by HVR88** [comment]
> That's interesting as my LB startup is super small compared to when I use Pegasus metadata files (exported from LB using Pegasus Exporter). My files are also on my NAS. 

My NAS can do upwards of 100MB/s transfers on large files, but like all filesystem access on any platform, performance goes to crap on small seeks. My thought right now is that checking the ROMs is what's causing this issue, just by the sheer number of files/paths to check, and an option to not check, and read only the xml, would make the startup process almost instant.

When I first mentioned this I was at around 6-9k ROM files. I expect my total will be above 25K pretty soon as I bring systems like C64 into this new setup.

My desire to move away from using LB's metadata is two-fold. First I suspected it was causing performance issues - you may have ruled that out. But second, and most important, is that it's really terrible at managing media assets and that's been the bane of my emulation setup for over a year.

Interestingly on a side note, last night I just found a media asset downloading/managing tool that supports Pegasus xml files. It's runner-up for the ugliest application I've ever seen, but I can't deny its extreme usefulness - and surprisingly, despite its horrid UI, it's quite easy to use (so far).  ARRM (Another Gamelist, Roms manager, and Scraper for Recalbox, Batocera, Retropie, Retrobat, EmulationStation) https://www.facebook.com/ARRMbyNexusone13/posts/279035783595329

**Comment by HVR88** [comment]
> That's interesting as my LB startup is super small compared to when I use Pegasus metadata files (exported from LB using Pegasus Exporter). My files are also on my NAS.

I just had a thought...  When using exported data, have you relocated the media assets to the NAS?

Media folders located inside ROM paths is one of the downsides to the "standard" way of setting everything up.

**Comment by PlayingKarrde** [comment]
Yes all my media sits with my roms. There is the option to have them as absolute links though so it isn't necessary, but if I'm wanting to only manage the one place for roms (hence them being on the NAS) then I don't see why I wouldn't do this. 

I will note that I don't have slow speeds when using my Shield (which currently is the only device that uses these assets - but I don't really use this anymore since I built a living room PC).

**Comment by HVR88** [comment]
It makes complete sense to have everything together for a client-server approach, but the performance of the client UI is going to really dependent on the caching of the assets. I was speculating whether media assets on server versus local was cause for the difference in startup you saw between LB-native support and exported metadata.

**Comment by HVR88** [comment]
The subject of startup time and suggestion to eliminate checking ROM file paths has its own dedicated issue here: https://github.com/mmatyas/pegasus-frontend/issues/839

**Comment by mmatyas** [comment]
I've just added an option to the Settings menu for skipping the file checks; could you give it a try and see if it helps?

**Comment by PlayingKarrde** [comment]
So I've only been able to do a cursory test so far but it has worked with the links I had set up initially for testing. I will try and do a more thorough test tomorrow or the weekend to make sure but it's looking good so far!

**Comment by HVR88** [comment]
I can also confirm that there are no errors for missing files with the scan option turned off.

**Comment by mmatyas** [comment]
Well this should be working now so closing the issue.
