### ISSUE TITLE
Support non-game applications

### ISSUE THREAD

**Issue by j8r** [mmatyas/pegasus-frontend#827]
~It is stated in the [docs](https://pegasus-frontend.org/docs/user-guide/meta-files/) that we can put multiple metadata files in in the `metafiles` directory in the configuration path. However, using the latest version (`alpha14-134-gc0273204`), if we create two metadata files, only one will be taken into account (I suspect the frist one alphabetically).~

~Example files:~

~`~/.config/pegasus-frontend/metafiles/firsr.metadata.pegasus.txt`~
```
collection: Test
game: First
file: .
```
~`~/.config/pegasus-frontend/metafiles/second..metadata.pegasus.txt`~
```
collection: Test
game: Second
file: .
```

~Create the above files, then run the frontend. Only `First` will be shown in the `Test` collection.~

Edit: The use case was to have application shortcuts, like opening Retroarch, Steam Big Picture, etc. However, a file is needed, even though it does not make sense in this context.
A work around is just putting a random existing file.

**Comment by j8r** [comment]
I propose to have a `application: ` key, which does not require a `file:` one. Of course having both `game:` and `application:` is an error.

**Comment by mmatyas** [comment]
In the recent versions, there is also support for URIs (eg. `steam:12345`), which can be pretty much anything and there is no physical file checking for them. I guess this can be closed then.
