### ISSUE TITLE
Specify which monitor to use in multi-monitor setups - linux

### ISSUE THREAD

**Issue by Sixdd6** [mmatyas/pegasus-frontend#831]
Would love to have a setting in the config to specify which monitor to use. As it is now, when I open the launcher it just jumps to the left-most monitor, I think. If I run it windowed and then maximize it on the monitor I want it to be on it stays till a game launch then resets when the launcher reopens after the game is closed, it also does not persist through restarts and returns to the left-most monitor.

**Comment by j8r** [comment]
Very few applications have this feature. It won't be trivial to implement, it varies depending on the OS and I suspect the window manager. Does even Retroarch has it?

Alternatively, select the monitor you want as a primary screen.

**Comment by mmatyas** [comment]
The best place for this would be indeed your window manager, but turns out Qt-based applications, like Pegasus, also have a `--geometry` flag you can use for this:

```
 --geometry <geometry>         Window geometry for the main window, using the X11-syntax,
                               like 100x100+50+50.
```

This answer also looked useful: https://stackoverflow.com/a/18363772
Hope this helps!
