### ISSUE TITLE
Is assets.titlescreen supposed to work?

### ISSUE THREAD

**Issue by j8r** [mmatyas/pegasus-frontend#835]
I defined in my metafile `assets.titlescreen` and got `... Unknown asset type `titlescreen`, entry ignored`. From the [API reference](https://pegasus-frontend.org/docs/themes/api/), it is supposed to be a valid asset type.
For their parts, `assets.box_front`, `assets.background` and `assets.screenshot` worked.

Having a `media/My Game Name/titlescreen.png` seems to work - at least, no errors.

**Comment by mmatyas** [comment]
Hi, this feature is available only in the latest version at the moment (sorry for the late reply!)

**Comment by j8r** [comment]
I'll wait for a release then, I hope to have one soon :slightly_smiling_face: . I'm using the Flatpak.
