### ISSUE TITLE
Disable completely any Mouse events.

### ISSUE THREAD

**Issue by fastpop72** [mmatyas/pegasus-frontend#838]
With the included option you can hide mouse cursor but the mouse is still working behind...

If you Click& Drag or Scroll the wheel you can move the theme anyway.

In bartop set with a trackball device could be annoying...

Thanks.

**Comment by fastpop72** [comment]
@mmatyas Sorry but i'm not a QT programmer and i don't know how to do it. I suppose something related to the QMouseEvent class so i tried to add some lines of code but nothing...

**Comment by mmatyas** [comment]
Yes, in a theme one could cover the whole region with a [MouseArea](https://doc.qt.io/qt-5/qml-qtquick-mousearea.html), and disable accepting mouse events there.
I noticed you've reported the issue to the gameOS theme shortly after, so probably this one can be closed now, I think.
