### ISSUE TITLE
Add sleep option to the Quit menu

### ISSUE THREAD

**Issue by j8r** [mmatyas/pegasus-frontend#840]
Sleep is quite commonly used to turn the system to a low-power state, and then quickly go back to the same state.
It will be especially useful for slower systems, which can have startup times up to several minutes (https://github.com/mmatyas/pegasus-frontend/issues/839).

**Comment by mmatyas** [comment]
I think this sounds similar to #720.

**Comment by j8r** [comment]
Yes! Sorry I didn't see it.
