### ISSUE TITLE
Removing gamepad USB connection crashes Pegasus

### ISSUE THREAD

**Issue by tompacyk** [mmatyas/pegasus-frontend#844]
Can repro this with a few controllers now, but if I have a controller connected and disconnect the USB cable I find Pegasus crashes with nothing logged in the lastrun.log.

Connecting a controller while Pegasus is running seems fine, but the disconnect kills the process on macOS.

**Comment by mmatyas** [comment]
I've just updated Pegasus with a more recent SDL version. Could you check if this still happens with the latest release?

**Comment by tompacyk** [comment]
Working now. Thanks!
