### ISSUE TITLE
Possibility to use launch command variables -- {file.basename} -- for assets, too....

### ISSUE THREAD

**Issue by fastpop72** [mmatyas/pegasus-frontend#852]
Would be interesting to use the same variables for launch command to use in assets strings... 

Example:

file: .\10yard.zip
assets.boxfront: .\media\flyers\{file.basename}.png
assets.video: .\media\videos\{file.basename}.mp4
assets.logo: .\media\logos\{file.basename}.png
assets.screenshot: .\media\screenshots\{file.basename}-01.png
assets.screenshot: .\media\screenshots\{file.basename}-02.png

instead of

file: .\10yard.zip
assets.boxfront: .\media\flyers\10yard.png
assets.video: .\media\videos\10yard.mp4
assets.logo: .\media\logos\10yard.png
assets.screenshot: .\media\screenshots\10yard-01.png
assets.screenshot: .\media\screenshots\10yard-02.png

Thanks.

**Comment by mmatyas** [comment]
The goal of the `assets.something` lines is to allow you set assets manually if you're not comfortable with the default locations. It seems you're using a Skraper style directory setup: this is automatically recognized, so if you're fine with that, you don't need any `assets` line at all.

**Comment by fastpop72** [comment]
I'd have to rename a lot of assets to make it recognize automatically, i prefer to stay on manual assets, thanks.
