### ISSUE TITLE
Please streamline the build process

### ISSUE THREAD

**Issue by cmpunches** [mmatyas/pegasus-frontend#864]
Hello,

Please consider dropping qmake for cmake or similar and bundling environment discovery to about the following:

./configure | cmake . # optional
make
make install

**Comment by mmatyas** [comment]
Hi, yes, I'm planning to use CMake in the future. Other than that, the build process already looks like what you described. In case you've run into build issues, feel free to open an issue for them.

**Comment by mmatyas** [comment]
Ok, it is now possible to build using CMake; see the [documentation](https://pegasus-frontend.org/docs/dev/build/) for more details!
