### ISSUE TITLE
No video playback (mp4) in MacOS 11

### ISSUE THREAD

**Issue by HVR88** [mmatyas/pegasus-frontend#865]
Game videos as well as the header video for the GameOS theme will not play in MacOS 11 - blank/black shows up instead. 

For the GameOS Theme, the header just looks like the video is missing.

For default theme or GameOS theme, game videos show up as solid black.

### System info

MacOS 11.5 running on M1 Macbook Air

Testing with a simple setup of one system and 290 games - pegasus metadata file converted from Skraper's Logiqx dat, all ROMs local with media in the ROM folder under Skraper folder.

### Pegasus version

Alpha 15-14 from 2021-07-15

### Pegasus log

No errors in log.

**Comment by mmatyas** [comment]
Can you play the videos using the default, built-in media player of MacOS, without any tweaks? Could you upload an example file?

**Comment by HVR88** [comment]
Yes, the videos play with the default QuickTime Player, also with the QuickView extension in finder, and with all the third-party video players I have.

Here's one: http://salumba.com/A.E.%20(World).mp4

And here's GameOS' header video: https://github.com/PlayingKarrde/gameOS/blob/master/assets/video/ftue.mp4

**Comment by HVR88** [comment]
Could be related... thought I can file a separate issue if needed.

I've also been doing some testing on a brand new/current RetroPie setup using Rpi4/4GB set up to read the Emulation Station data.  The gameOS header video also won't play. And even with the default grid theme, selecting a game tile which would normally play its video doesn't show the video and will eventually completely lock up the UI - could happen on the first or fifth/tenth tile selected - the Rpi continues to function in the background (SMB shares continue to work and I can access via SSH). Nothing shows up in the log related to a hang. 

When starting Pegasus with the default grid theme, the RetroPie category is selected by default and the tiles in that category/system don't have videos - they can be scrolled and selected all day without issue. The hang only seems to happen when a video is supposed to play.

**Comment by polson** [comment]
Tested this on my mac.  The GameOS header plays fine, but Steam game videos do not.   QuickTime can't play the steam videos either.  They are WebM with Vorbis audio 👀 

FWIW this is essentially the same issue that occurs on Windows when the proper codecs aren't installed.  I don't think there is such an easy fix on MacOS.

Probably another good reason to bundle ffmpeg or libVLC with Pegasus so it just works out of the box.

**Comment by mmatyas** [comment]
The Pi issue is related to GStreamer, the video playback backend used there. I assume some of the codecs might have issues, considering all the driver differences there. Make sure your kernel is up to date, gstreamer1.0-alsa, gstreamer1.0-libav, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, and (optionally) gstreamer-omx are installed and up to date. If that doesn't fix it, feel free to open a new issue for it; it's a different multimedia backend so it's likely not related to the Mac issue.

As polson mentioned, implementing a custom backend (#347) would be indeed a solution for this in the future.

**Comment by HVR88** [comment]
@polson can you outline what version of macOS you're running?  I'm only testing in 11.5 (GM).

**Comment by polson** [comment]
I'm on 11.4

**Comment by polson** [comment]
Intel

**Comment by HVR88** [comment]
OK, that's a significant difference. Pegasus on my M1 machine is going through Rosetta2 translation - might be something there that's causing the issue.

**Comment by HVR88** [comment]
Confirmed same issue exists in Mac OS 12 (21A5522h)

**Comment by HomeStarRunnerTron** [comment]
[Now all video playback works, just like I showed off in my demonstration video](https://github.com/mmatyas/pegasus-frontend/issues/1067#issuecomment-1691393776)! :  ) I'm using macOS 12, so I think this problem should be fixed for all the neighbouring macOS versions. Thank you so much for all your hard work.

**Comment by mmatyas** [comment]
I think this can be closed then, but feel free to report if the issue still occurs!
