### ISSUE TITLE
SVG logo files saved from Inkscape and Affinity Designer appear black

### ISSUE THREAD

**Issue by HVR88** [mmatyas/pegasus-frontend#870]
Single color SVG files saved with Inkscape or Affinity Designer will appear as black on transparent background instead of white.

**Details:**
System tested: MacOS 11.5 on M1 Macbook Air

Testing has been performed on a copy of the default Pegasus Grid theme and a modified GameOS theme (made to load svg files).

SVG files can be made to render correctly if exported from Inkscape as "Optimized" and the option "Convert CSS attributes to XML attributes" is enabled.

I have not been able to reproduce this behavior in other software that opens/renders SVG.  Firefox, Safari, Inkscape, Affinity Designer, Gapplin, etc. I will try to make some time to test the behavior on Windows 10.

Here are many SVG files exported from Affinity Designer that can be tested: https://github.com/HVR88/Monochrome-Gaming-Logos/tree/main/svg

**Comment by HVR88** [comment]
Here is an export of my Coleco Adam logo that works:

<?xml version="1.0" encoding="UTF-8"?>
<svg id="svg40" clip-rule="evenodd" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" version="1.1" viewBox="0 0 600 218" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><g id="colecovision" fill="#ffffff"><g id="g19"><path id="path9" d="m428.88 213.22.718 1.648c-0 .445-.131.859-.359 1.203.391.606 1.073 1.004 1.851 1.004h31.383c1.223 0 2.207-.984 2.207-2.207v-87.232c0-.835.955-1.491 1.76-1.491l-.028.029c.833 0 1.579.627 1.849 1.462l28.968 87.828c.298.925 1.282 1.611 2.267 1.611h30.609c.985 0 1.968-.686 2.267-1.611l28.252-87.828c.268-.835 1.014-1.462 1.85-1.462l-.031-.029c.806 0 1.76.656 1.76 1.491v87.232c0 1.223.986 2.207 2.209 2.207h31.383c1.223 0 2.207-.984 2.207-2.207v-122.38h-62.083l-23.476 70.765-23.479-70.765h-66.349c-1.492-0-2.626.925-3.312 2.388l-12.141 26.46c-.657 1.492-.359 2.656 1.133 2.656h10.59c5.044 0 7.936 2.923 7.936 7.936l.059 81.288z"/><path id="path11" d="m428.88 213.22-52.626-120.73h-66.913c-1.493-0-2.627.925-3.313 2.388l-12.142 26.46c-.655 1.492-.358 2.656 1.134 2.656h8.444c5.04 0 7.935 2.923 7.935 7.936l-36.457 82.936c0 1.223.985 2.207 2.209 2.207h34.308l8.591-20.048h64.44l8.591 20.048h34.308c.778 0 1.46-.398 1.85-1.004-.228-.344-.358-.758-.358-1.203l-.001-1.648zm-78.758-86.301c.268-.833 1.014-1.46 1.85-1.46l.297-.031.299.031c.836 0 1.582.627 1.849 1.46l16.289 38.009c.537 1.253.12 2.027-1.132 2.027h-34.608c-1.252-0-1.669-.774-1.132-2.027l16.288-38.009z"/><path id="path13" d="m428.88 213.22.001 1.648c-0 .445.13.859.358 1.203.228-.344.359-.758.359-1.203l-.718-1.648z"/><path id="path15" d="m257.37 217.08c13.991 0 24.014-10.024 24.014-24.016v-76.551c0-13.991-10.023-24.016-24.014-24.016h-106.21c-1.492-0-2.625.925-3.313 2.388l-12.141 26.46c-.656 1.492-.358 2.656 1.133 2.656h10.592c5.011 0 7.935 2.923 7.935 7.936v82.936c-0 1.223.984 2.207 2.207 2.207h99.793zm-63.993-32.936c-1.223-0-2.209-.984-2.209-2.207v-55.728c0-1.223.986-2.208 2.209-2.208h45.704c5.012 0 7.936 2.923 7.936 7.936v44.272c-0 5.013-2.924 7.935-7.936 7.935h-45.704z"/><path id="path17" d="m2.206 217.08h34.309l8.592-20.048h64.439l8.592 20.048h34.308c1.223 0 2.208-.984 2.208-2.207l-53.341-122.38h-66.916c-1.492-0-2.625.925-3.312 2.388l-12.143 26.46c-.655 1.492-.357 2.656 1.136 2.656h8.441c5.043 0 7.936 2.923 7.936 7.936l-36.455 82.936c-0 1.223.983 2.207 2.206 2.207zm72.971-90.156c.271-.833 1.017-1.46 1.851-1.46l.298-.031.3.031c.834 0 1.58.627 1.848 1.46l16.289 38.009c.537 1.253.119 2.027-1.134 2.027h-34.606c-1.254-0-1.671-.774-1.134-2.027l16.288-38.009z"/></g><g id="g37"><g id="g33" fill-rule="nonzero"><path id="path21" d="m18.539 40.365c-0 9.901 5.558 12.236 14.898 12.236h16.72c10.414-0 12.469-4.484 12.469-10.181v-3.176h-10.368c0 4.203-1.401 4.67-6.071 4.67h-11.069c-4.903 0-5.931-1.868-5.931-6.772v-3.642c0-4.204 1.028-6.772 6.492-6.772h11.302c3.082-0 4.857.7 4.857 3.129v.934h10.368c.093-9.574-1.821-12.75-16.579-12.75h-12.19c-9.34-0-14.898 2.335-14.898 12.236v10.088z"/><path id="path23" d="m64.799 40.365c0 9.901 5.558 12.236 14.898 12.236h16.627c9.34-0 14.898-2.335 14.898-12.236v-10.088c-0-9.901-5.558-12.236-14.898-12.236h-16.627c-9.34-0-14.898 2.335-14.898 12.236v10.088zm10.648-6.865c0-4.204 1.028-6.772 6.492-6.772h12.143c5.464-0 6.491 2.568 6.491 6.772v3.642c0 4.904-1.027 6.772-5.931 6.772h-13.263c-4.904 0-5.932-1.868-5.932-6.772v-3.642z"/><path id="path25" d="m113.38 52.227h33.673v-8.686h-23.305v-25.126h-10.368v33.812z"/><path id="path27" d="m149.25 52.227h37.595v-8.126h-27.227v-5.417h25.219v-7.006h-25.219v-5.417h26.62v-7.846h-36.988v33.812z"/><path id="path29" d="m188.79 40.365c-0 9.901 5.557 12.236 14.898 12.236h16.719c10.415-0 12.47-4.484 12.47-10.181v-3.176h-10.368c-0 4.203-1.401 4.67-6.071 4.67h-11.069c-4.904 0-5.931-1.868-5.931-6.772v-3.642c-0-4.204 1.027-6.772 6.491-6.772h11.302c3.083-0 4.858.7 4.858 3.129v.934h10.368c.093-9.574-1.822-12.75-16.58-12.75h-12.189c-9.341-0-14.898 2.335-14.898 12.236v10.088z"/><path id="path31" d="m235.04 40.365c-0 9.901 5.557 12.236 14.898 12.236h16.626c9.34-0 14.898-2.335 14.898-12.236v-10.088c0-9.901-5.558-12.236-14.898-12.236h-16.626c-9.341-0-14.898 2.335-14.898 12.236v10.088zm10.648-6.865c-0-4.204 1.027-6.772 6.491-6.772h12.143c5.464-0 6.492 2.568 6.492 6.772v3.642c-0 4.904-1.028 6.772-5.931 6.772h-13.264c-4.904 0-5.931-1.868-5.931-6.772v-3.642z"/></g><path id="path35" d="m-0 18.041v34.56c-0 9.538 6.533 17.28 16.138 17.28h267.72c9.605-0 16.138-7.742 16.138-17.28v-34.56c-0-9.537-6.533-17.28-16.138-17.28h-267.72c-9.605-0-16.138 7.743-16.138 17.28zm7.548 0c0-5.236 3.317-9.732 8.59-9.732h267.72c5.273 0 8.59 4.496 8.59 9.732v34.56c-0 5.236-3.317 9.731-8.59 9.731h-267.72c-5.273 0-8.59-4.495-8.59-9.731v-34.56z"/></g></g></svg>

**Comment by HVR88** [comment]
And here is a copy exported from Inkscape as "Plain SVG" that appears black:
```

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="100%"
   height="100%"
   viewBox="0 0 600 218"
   version="1.1"
   xml:space="preserve"
   style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"
   id="svg40"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg"><defs
     id="defs44" /><g
     id="colecovision"><g
       id="g19"><path
         d="M428.878,213.221l0.718,1.648c-0,0.445 -0.131,0.859 -0.359,1.203c0.391,0.606 1.073,1.004 1.851,1.004l31.383,0c1.223,0 2.207,-0.984 2.207,-2.207l0,-87.232c0,-0.835 0.955,-1.491 1.76,-1.491l-0.028,0.029c0.833,0 1.579,0.627 1.849,1.462l28.968,87.828c0.298,0.925 1.282,1.611 2.267,1.611l30.609,0c0.985,0 1.968,-0.686 2.267,-1.611l28.252,-87.828c0.268,-0.835 1.014,-1.462 1.85,-1.462l-0.031,-0.029c0.806,0 1.76,0.656 1.76,1.491l0,87.232c0,1.223 0.986,2.207 2.209,2.207l31.383,0c1.223,0 2.207,-0.984 2.207,-2.207l-0,-122.376l-62.083,-0l-23.476,70.765l-23.479,-70.765l-66.349,-0c-1.492,-0 -2.626,0.925 -3.312,2.388l-12.141,26.46c-0.657,1.492 -0.359,2.656 1.133,2.656l10.59,0c5.044,0 7.936,2.923 7.936,7.936l0.059,81.288Z"
         style="fill:#fff;"
         id="path9" /><path
         d="M428.878,213.221l-52.626,-120.728l-66.913,-0c-1.493,-0 -2.627,0.925 -3.313,2.388l-12.142,26.46c-0.655,1.492 -0.358,2.656 1.134,2.656l8.444,0c5.04,0 7.935,2.923 7.935,7.936l-36.457,82.936c0,1.223 0.985,2.207 2.209,2.207l34.308,0l8.591,-20.048l64.44,-0l8.591,20.048l34.308,0c0.778,0 1.46,-0.398 1.85,-1.004c-0.228,-0.344 -0.358,-0.758 -0.358,-1.203l-0.001,-1.648Zm-78.758,-86.301c0.268,-0.833 1.014,-1.46 1.85,-1.46l0.297,-0.031l0.299,0.031c0.836,0 1.582,0.627 1.849,1.46l16.289,38.009c0.537,1.253 0.12,2.027 -1.132,2.027l-34.608,-0c-1.252,-0 -1.669,-0.774 -1.132,-2.027l16.288,-38.009Z"
         style="fill:#fff;"
         id="path11" /><path
         d="M428.878,213.221l0.001,1.648c-0,0.445 0.13,0.859 0.358,1.203c0.228,-0.344 0.359,-0.758 0.359,-1.203l-0.718,-1.648Z"
         style="fill:#fff;"
         id="path13" /><path
         d="M257.37,217.076c13.991,0 24.014,-10.024 24.014,-24.016l0,-76.551c0,-13.991 -10.023,-24.016 -24.014,-24.016l-106.206,-0c-1.492,-0 -2.625,0.925 -3.313,2.388l-12.141,26.46c-0.656,1.492 -0.358,2.656 1.133,2.656l10.592,0c5.011,0 7.935,2.923 7.935,7.936l-0,82.936c-0,1.223 0.984,2.207 2.207,2.207l99.793,0Zm-63.993,-32.936c-1.223,-0 -2.209,-0.984 -2.209,-2.207l0,-55.728c0,-1.223 0.986,-2.208 2.209,-2.208l45.704,0c5.012,0 7.936,2.923 7.936,7.936l-0,44.272c-0,5.013 -2.924,7.935 -7.936,7.935l-45.704,-0Z"
         style="fill:#fff;"
         id="path15" /><path
         d="M2.206,217.076l34.309,0l8.592,-20.048l64.439,-0l8.592,20.048l34.308,0c1.223,0 2.208,-0.984 2.208,-2.207l-53.341,-122.376l-66.916,-0c-1.492,-0 -2.625,0.925 -3.312,2.388l-12.143,26.46c-0.655,1.492 -0.357,2.656 1.136,2.656l8.441,0c5.043,0 7.936,2.923 7.936,7.936l-36.455,82.936c-0,1.223 0.983,2.207 2.206,2.207Zm72.971,-90.156c0.271,-0.833 1.017,-1.46 1.851,-1.46l0.298,-0.031l0.3,0.031c0.834,0 1.58,0.627 1.848,1.46l16.289,38.009c0.537,1.253 0.119,2.027 -1.134,2.027l-34.606,-0c-1.254,-0 -1.671,-0.774 -1.134,-2.027l16.288,-38.009Z"
         style="fill:#fff;"
         id="path17" /></g><g
       id="g37"><g
         id="g33"><path
           d="M18.539,40.365c-0,9.901 5.558,12.236 14.898,12.236l16.72,-0c10.414,-0 12.469,-4.484 12.469,-10.181l0,-3.176l-10.368,-0c0,4.203 -1.401,4.67 -6.071,4.67l-11.069,0c-4.903,0 -5.931,-1.868 -5.931,-6.772l0,-3.642c0,-4.204 1.028,-6.772 6.492,-6.772l11.302,-0c3.082,-0 4.857,0.7 4.857,3.129l-0,0.934l10.368,-0c0.093,-9.574 -1.821,-12.75 -16.579,-12.75l-12.19,-0c-9.34,-0 -14.898,2.335 -14.898,12.236l-0,10.088Z"
           style="fill:#fff;fill-rule:nonzero;"
           id="path21" /><path
           d="M64.799,40.365c0,9.901 5.558,12.236 14.898,12.236l16.627,-0c9.34,-0 14.898,-2.335 14.898,-12.236l-0,-10.088c-0,-9.901 -5.558,-12.236 -14.898,-12.236l-16.627,-0c-9.34,-0 -14.898,2.335 -14.898,12.236l0,10.088Zm10.648,-6.865c0,-4.204 1.028,-6.772 6.492,-6.772l12.143,-0c5.464,-0 6.491,2.568 6.491,6.772l0,3.642c0,4.904 -1.027,6.772 -5.931,6.772l-13.263,0c-4.904,0 -5.932,-1.868 -5.932,-6.772l0,-3.642Z"
           style="fill:#fff;fill-rule:nonzero;"
           id="path23" /><path
           d="M113.382,52.227l33.673,0l-0,-8.686l-23.305,-0l0,-25.126l-10.368,-0l0,33.812Z"
           style="fill:#fff;fill-rule:nonzero;"
           id="path25" /><path
           d="M149.246,52.227l37.595,0l0,-8.126l-27.227,0l-0,-5.417l25.219,-0l0,-7.006l-25.219,0l-0,-5.417l26.62,-0l0,-7.846l-36.988,-0l-0,33.812Z"
           style="fill:#fff;fill-rule:nonzero;"
           id="path27" /><path
           d="M188.792,40.365c-0,9.901 5.557,12.236 14.898,12.236l16.719,-0c10.415,-0 12.47,-4.484 12.47,-10.181l-0,-3.176l-10.368,-0c-0,4.203 -1.401,4.67 -6.071,4.67l-11.069,0c-4.904,0 -5.931,-1.868 -5.931,-6.772l-0,-3.642c-0,-4.204 1.027,-6.772 6.491,-6.772l11.302,-0c3.083,-0 4.858,0.7 4.858,3.129l-0,0.934l10.368,-0c0.093,-9.574 -1.822,-12.75 -16.58,-12.75l-12.189,-0c-9.341,-0 -14.898,2.335 -14.898,12.236l-0,10.088Z"
           style="fill:#fff;fill-rule:nonzero;"
           id="path29" /><path
           d="M235.039,40.365c-0,9.901 5.557,12.236 14.898,12.236l16.626,-0c9.34,-0 14.898,-2.335 14.898,-12.236l0,-10.088c0,-9.901 -5.558,-12.236 -14.898,-12.236l-16.626,-0c-9.341,-0 -14.898,2.335 -14.898,12.236l-0,10.088Zm10.648,-6.865c-0,-4.204 1.027,-6.772 6.491,-6.772l12.143,-0c5.464,-0 6.492,2.568 6.492,6.772l-0,3.642c-0,4.904 -1.028,6.772 -5.931,6.772l-13.264,0c-4.904,0 -5.931,-1.868 -5.931,-6.772l-0,-3.642Z"
           style="fill:#fff;fill-rule:nonzero;"
           id="path31" /></g><path
         d="M-0,18.041l-0,34.56c-0,9.538 6.533,17.28 16.138,17.28l267.724,-0c9.605,-0 16.138,-7.742 16.138,-17.28l-0,-34.56c-0,-9.537 -6.533,-17.28 -16.138,-17.28l-267.724,-0c-9.605,-0 -16.138,7.743 -16.138,17.28Zm7.548,0c0,-5.236 3.317,-9.732 8.59,-9.732c-0,0 267.724,0 267.724,0c5.273,0 8.59,4.496 8.59,9.732c-0,0 -0,34.56 -0,34.56c-0,5.236 -3.317,9.731 -8.59,9.731l-267.724,0c-5.273,0 -8.59,-4.495 -8.59,-9.731c0,0 0,-34.56 0,-34.56Z"
         style="fill:#fff;"
         id="path35" /></g></g></svg>

```

**Comment by mmatyas** [comment]
Yes, Qt supports the features of [SVG Tiny 1.2](https://doc.qt.io/qt-5/svgrendering.html#rendering-svg-files). It does not support any features that require CSS parsing (eg. the `style` tags in the second example), DOM elements or running JavaScript code.

As you mentioned, Inkscape (and if I remember correctly, Illustrator too) has an export option for this format, and there are online minifiers as well.

**Comment by HVR88** [comment]
Thanks for the heads up.  I've now installed a small tool to post-process and clean all my SVG files before I commit them to the repo.

Unfortunately Designer doesn't have any options to make the files Tiny1.2 compliant and I was only using Inkscape for testing purposes.

Closing.
