### ISSUE TITLE
Playnite: Include game logo and video from third party extensions

### ISSUE THREAD

**Issue by polson** [mmatyas/pegasus-frontend#874]
Out of the box Playnite does not support clear logo and videos.  When importing from Playnite with these missing the user experience is less than ideal, especially if using a theme like GameOS.

It seems most people are using the [Extra Metadata Tools](https://playnite.link/forum/thread-575.html) plugin for their custom themes in Playnite, which allows for clear logo and video to be used.  This plugin works with the most popular Playnite themes.  We should by default import these media files in Pegasus so that users who have set up these themes can easily use Pegasus themes as well.

I can add this if you think it would be a good addition to the Playnite support.

Also, another option to make this work would be to handle the case where Skraper assets and Playnite are selected together as sources.  Currently Skraper assets won't load unless a metadata file is included.  But Playnite already has all the metadata we need to load Skraper assets.  It would be cool if Skraper assets would just override the Playnite assets without the need for adding a metadata file.  But if that's a good idea we can do it separately.

**Comment by mmatyas** [comment]
Sure, feel free to implement it if it can be used. I'm not familiar with how assets are stored with plugins, are they listed in the same files?

> Also, another option to make this work would be to handle the case where Skraper assets and Playnite are selected together as sources.

Skraper looks for the games based on the file name, it does not strictly depend on Pegasus' metafiles. If it finds an asset, it will always add it to the game.

**Comment by polson** [comment]
The Extra Metadata Tools plugin for Playnite just adds images to a new folder in the Playnite library directory.  It doesn't even mess with the xml files.  So it should be pretty easy to add.  We just check if those files exist and add them.

> Skraper looks for the games based on the file name, it does not strictly depend on Pegasus' metafiles. If it finds an asset, it will always add it to the game.

Currently Skraper assets doesn't work with Playnite or LaunchBox, I think because the game dirs have to be set, which requires a pegasus metadata file.  Unless I'm missing something

**Comment by HVR88** [comment]
Allowing skraper assets in addition to other base like launchbox would be an amazing feature. I'm using both already but launchbox is a total piece of crap with regards to how it treats assets, renaming everything and making it all a mess with thousands of duplicates. But... it's a handy visual Roms manager. That's all
- [ ] I use it for.

**Comment by polson** [comment]
Yeah, I would also like to be able to just have all of my assets in the rom folders so they can stay independent of LaunchBox or whatever.  

I actually think this is a really simple fix.  We just internally add the game dirs when we parse Playnite or LaunchBox.  Then the Skraper assets provider will be able to match up the media files.  I'm just not sure if doing that would have unintended consequences.

**Comment by HVR88** [comment]
The first issue is one I mentioned previously. Which asset has priority if both know and skraper are present. 

Next is something I've been meaning to look into and request if it's not already supported and straight forward. Specifying an alternate path for scraper assets and metadata file. I really want to keep that path outside my rims folder(s)

**Comment by polson** [comment]
I figure if you selected Skraper assets, then you want your Skraper assets to override.  Otherwise you would just turn it off.

As for selecting a media file location, that would be cool, but to allow changing it in the UI would require redoing a lot of the settings screen so you can set options per-provider.  Maybe it could be set as a command-line option or a small metafile change or something.  I'd leave it to @mmatyas to decide how best to handle that.

For now you could try working around it with symlinks though.  Not sure if Pegasus would pick that up correctly.

**Comment by mmatyas** [comment]
Here's how the Skraper provider works:

- Skraper always runs last (on the reason that it doesn't introduce new games)
- It runs for directories where Pegasus metafiles with Collections were found, and for their `directory` entries; this could be indeed improved a bit, to run in all added metadata dirs for example, and then you could just drop in an empty file or something. Will see if I can add this next week.
- For every asset, it will remove the `\skraper\<assettype>\` part from the path and look for the game with a file at the resulting location (eg. if you have `C:\mygames\skraper\box2dfront\Nintendo\Mario.jpg` then it will be added to the game `C:\mygames\Nintendo\Mario.rom`, if exists).

I'd also like to add provider settings eventually, there are places where it'd be useful. Yes, that would probably require redoing most of the settings menu :)
