### ISSUE TITLE
A Problem Caused the Program to Stop Working 

### ISSUE THREAD

**Issue by sofalzone** [mmatyas/pegasus-frontend#879]
I launched a Steam game through Pegasus (alpha15 (2021-05-04), Windows), and the computer crashed. I restarted. Now when I open Pegasus, it hangs every time, with an error message stating "A problem caused the program to stop working ...". I've tried reinstalling the program, deleting all the files in the AppData/Local folders (both folders - I copied them somewhere else). It still happens, and I see that it did not set up any files within the AppData/Local folders, just some of the directories it needs. I've tried this with multiple users on the computer - all the same.

It also does it with version: alpha15-26-gfce59744 (2021-08-09).

EDIT: Now it doesn't even give me the Windows error message, it crashes right away with both versions.

EDIT: Here are the relevant event logs:

**Error Log:**

Faulting application name: pegasus-fe.exe, version: 0.0.0.0, time stamp: 0x6091190f
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0x1d60
Faulting application start time: 0x01d795f29fd3b81d
Faulting application path: D:\Sam\Desktop\pegasus-fe_alpha13_win-mingw-static\pegasus-fe.exe
Faulting module path: unknown
Report Id: b43d37ca-de69-4726-880d-d80cb1a919f5
Faulting package full name: 
Faulting package-relative application ID: 

**Information Log:**
Fault bucket 2137487629849084974, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: pegasus-fe.exe
P2: 0.0.0.0
P3: 61114ae2
P4: StackHash_2beb
P5: 0.0.0.0
P6: 00000000
P7: c0000005
P8: PCH_29_FROM_ntdll+0x00072F6C
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER429B.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_pegasus-fe.exe_ff3e0f0648ab92ec58b3cd29f261324d44d90f1_d54004fc_44a875d4-da14-4b6c-ad00-506aa960bd19

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9bfa9851-e33d-4e70-ad80-5dd981060aa6
Report Status: 268435456
Hashed bucket: d0d7607dc4b713a09da9e1aca8f2442e
Cab Guid: 0

**Comment by mmatyas** [comment]
Hm, since the crashing started after playing a game, could it be that the graphics driver set some incorrect profile for Pegasus? Or maybe some Steam files got corrupted?

Also the log says `pegasus-fe_alpha13_win-mingw-static`, is this only the name of the directory?

**Comment by sofalzone** [comment]
Figured it out. When I opened the Raedon software, it said "no AMD graphics card installed", yet device manager still shows my 590x is installed and functional. Went through AMD's driver installation software, and it works now after a restart. Not sure why one random Steam game could cause all this trouble and why it would only take it out on Pegasus, but there it is.

Is there a problem calling the directory that? I've always called it this with no issues, including now after the graphics card issue.

**Comment by mmatyas** [comment]
Weird, but I guess the issue is solved then, right? May I ask what game was this, in case others run into the same issue?

> Is there a problem calling the directory that? I've always called it this with no issues, including now after the graphics card issue.

Nah, I was just asking to make sure it didn't got mixed up with some old version.

**Comment by sofalzone** [comment]
The game was Shio. I've played it a thousand times, launching through Pegasus, no problem. And it was up and running, fully functional when it crashed. Probably not a Pegasus issue.

**Comment by mmatyas** [comment]
Ok, thanks for the report!

**Comment by sofalzone** [comment]
So I found a lingering issue associated with this issue. Pegasus won't find my Steam games. It lists the following error in the log file:

2021-08-25T00:13:13 [w] The collection 'Steam' has no valid games, ignored

I did reinstall Steam while I was trying to figure out what was wrong, but I can confirm that Steam is working properly separate from Pegasus: all games are still installed, the default library folder is set correctly, etc.

How does Pegasus determine if there are games in the Steam folder? Does it just search for them within the library folder, or is there a file it relies on? Is there any way for me to figure out where Pegasus is looking, or to point it in the right directly?

FYI, GOG games are found normally by Pegasus.

**Comment by sofalzone** [comment]
I updated Steam again and it broke it again.

So it looks like Steam changed the libraryfolders.vbf files again. At least I am assuming its them and not me as I don't know what I would have done to change them like this.

See attached my libraryfolders files. "C libraryfolders.log" is the vbf file from "C:\Program Files (x86)\Steam" and "L libraryfolders.log" is from my preferred library location

[C libraryfolders.log](https://github.com/mmatyas/pegasus-frontend/files/7226616/C.libraryfolders.log)
[L libraryfolder.log](https://github.com/mmatyas/pegasus-frontend/files/7226617/L.libraryfolder.log)
.

**Comment by mmatyas** [comment]
Yeah, looks like the format has changed. Will update it in a second!
