### ISSUE TITLE
RPi4 RetroPie build, crash/hang playing video files (game 'snaps')

### ISSUE THREAD

**Issue by HVR88** [mmatyas/pegasus-frontend#880]
Videos also not working and cause UI hang on RPi4 RetroPie. 

I've also been doing some testing on a brand new/current RetroPie setup using Rpi4/4GB (USB SSD boot) set up to read the Emulation Station data. The gameOS header video also won't play. And even with the default grid theme, selecting a game tile which would normally play its video doesn't show the video and will eventually completely lock up the UI - could happen on the first or fifth/tenth tile selected - the Rpi continues to function in the background (SMB shares continue to work and I can access via SSH). Nothing shows up in the log related to a hang.

When starting Pegasus with the default grid theme, the RetroPie category is selected by default and the tiles in that category/system don't have videos (they aren't games) - they can be scrolled and selected all day without issue. The hang only seems to happen when a tile with video is selected.

Videos are MP4 and I'll grab some details on them shortly.

### System info

Raspberry Pi 4b 4GB
Running RetroPie build of Raspian

The gstreamer installed seems to be the current supported by Raspian - there exists newer versions if building from source - but that's not something most people installing Raspian will have done and definitely not something anyone installing RetroPie will have.

ii  gstreamer1.0-alsa:armhf                                     1.14.4-2                            armhf        GStreamer plugin for ALSA
ii  gstreamer1.0-libav:armhf                                    1.15.0.1+git20180723+db823502-2     armhf        libav plugin for GStreamer
ii  gstreamer1.0-omx                                            1.14.4-1+rpt1                       armhf        GStreamer OpenMAX plugins
ii  gstreamer1.0-omx-rpi                                        1.14.4-1+rpt1                       armhf        OpenMax plugins for GStreamer
ii  gstreamer1.0-omx-rpi-config                                 1.14.4-1+rpt1                       armhf        OpenMax plugins for GStreamer
ii  gstreamer1.0-plugins-bad:armhf                              1.14.4-1+b1                         armhf        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-base:armhf                             1.14.4-2                            armhf        GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-good:armhf                             1.14.4-1+rpt1                       armhf        GStreamer plugins from the "good" set
ii  gstreamer1.0-x:armhf                                        1.14.4-2                            armhf        GStreamer plugins for X11 and Pango
ii  libgstreamer-gl1.0-0:armhf                                  1.14.4-2                            armhf        GStreamer GL libraries
ii  libgstreamer-plugins-bad1.0-0:armhf                         1.14.4-1+b1                         armhf        GStreamer libraries from the "bad" set
ii  libgstreamer-plugins-base1.0-0:armhf                        1.14.4-2                            armhf        GStreamer libraries from the "base" set
ii  libgstreamer1.0-0:armhf                                     1.14.4-1                            armhf        Core GStreamer libraries and elements

### Pegasus version

Alpha 15-14 from 2021-07-1

### Pegasus log

Last items in log:
2021-07-23T15:19:34 [w] qt.gui.icc: fromIccProfile: failed minimal tag size sanity
2021-07-23T15:19:34 [w] QPngHandler: Failed to parse ICC profile
2021-07-23T15:19:35 [w] libpng warning: iCCP: cHRM chunk does not match sRGB

Every other part of the log is simply parsing Emulation Station game files and assets.

**Comment by mmatyas** [comment]
Could you try removing all the OMX plugins, in case it's related to hardware acceleration? If that doesn't help, try to launch Pegasus by SSH, perhaps there's some log message by some other system component. If nothing shows up, also do an `export GST_DEBUG=omx:4` before starting Pegasus; this should make GStreamer more verbose.

**Comment by HVR88** [comment]
If you can let me know the best/fastest way to remove those components, that would save me some time from searching. :)  I've been trying to figure out how to update all of gstreamer to a version that's newer than Raspian's and that's proving itself problematic - no one has posted a really clear and straight-forward method - at least not for a pre-built binary.

**Comment by mmatyas** [comment]
Oh, I think you can just `apt remove gstreamer-omx` (or similar) for the OMX packages, it they are installed on the system. Personally I had playback problems on all Pis with them around.

I'm afraid I'm not familiar with building GStreamer itself, unfortunately.

**Comment by HVR88** [comment]
Some testing...  Starring Pegasus from SSH without any changes to the system

`Bruno@M1Air-2 ~ % ssh pi@192.168.8.247
pi@192.168.8.247's password: 

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.


     .***.     Sunday, 29 August 2021, 10:39:14 PM
     *****     Linux 5.4.72-v7l+ armv7l GNU/Linux
     `***'     
      |*|      Filesystem      Size  Used Avail Use% Mounted on
      |*|      /dev/root       917G  841G   48G  95% /
    ..|*|..    Uptime.............: 0 days, 00h01m14s
  .*** * ***.  Memory.............: 2737828kB (Free) / 3671832kB (Total)
  *******@@**  Running Processes..: 148
  `*****@@**'  IP Address.........: 1000
   `*******'   Temperature........: CPU: 43?C/109?F GPU: 43?C/109?F
     `"""'     The RetroPie Project, https://retropie.org.uk
     `"""'     SUPREME ULTRA BY THE SUPREME TEAM

pi@retropie:~ $ /opt/retropie/supplementary/pegasus-fe/pegasus-fe
[i] Pegasus alpha15-14-gc63493c4-dirty (2021-07-15)
[i] Running on Raspbian GNU/Linux 10 (buster) (arm, eglfs)
[i] Qt version 5.15.2
[i] Program settings loaded (`/home/pi/.config/pegasus-frontend/settings.txt`)
[i] Found locale `ar`
[i] Found locale `bs`
[i] Found locale `de`
[i] Found locale `en-GB`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ko`
[i] Found locale `nl`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Found locale `zh-TW`
[i] Found locale `zh`
[i] Locale set to `en`
[i] Found theme `Pegasus Grid` at `:/themes/pegasus-theme-grid/`
[i] Found theme `gameOS` at `/home/pi/.config/pegasus-frontend/themes/gameOS/`
[w] Requested theme `:/themes/pegasus-theme-grid` not found, falling back to default
[i] Theme set to `Pegasus Grid` (`:/themes/pegasus-theme-grid/`)
[i] SDL version 2.0.14
[i] SDL2: layout for gamepad #0 set to ``
[i] Gamepad: Connected device 0x0 (XInput Controller)
[i] Metafiles: No metadata files found
[i] Metafiles: Finished searching in 0ms
[i] Media: Finished searching in 0ms
[i] EmulationStation: Found `/home/pi/.emulationstation/es_systems.cfg`
[i] EmulationStation: Found 115 systems
[i] EmulationStation: System `3DO Interactive Multiplayer` provided 62 games
[i] EmulationStation: System `OpenBOR` provided 0 games
[i] EmulationStation: System `Commodore Amiga` provided 1591 games
[i] EmulationStation: System `Commodore Amiga CD32` provided 94 games
[i] EmulationStation: System `Amstrad CPC` provided 753 games
[i] EmulationStation: System `Apple II` provided 327 games
[i] EmulationStation: System `Arcade` provided 2395 games
[i] EmulationStation: System `Arcadia` provided 0 games
[i] EmulationStation: System `Astrocade` provided 51 games
[i] EmulationStation: System `Atari 2600` provided 662 games
[i] EmulationStation: System `Atari 5200` provided 80 games
[i] EmulationStation: System `Atari 7800 ProSystem` provided 58 games
[i] EmulationStation: System `Atari 800` provided 647 games
[i] EmulationStation: System `Atari Jaguar` provided 28 games
[i] EmulationStation: System `Atari Lynx` provided 76 games
[i] EmulationStation: System `Atari ST` provided 509 games
[i] EmulationStation: System `Atari 800` provided 0 games
[i] EmulationStation: System `Atomiswave` provided 23 games
[i] EmulationStation: System `BBC Micro` provided 0 games
[i] EmulationStation: System `Commodore 128` provided 0 games
[i] EmulationStation: System `Commodore 64` provided 3056 games
[i] EmulationStation: System `Philips CD-i` provided 0 games
[i] EmulationStation: System `Channel F` provided 30 games
[i] EmulationStation: System `TRS-80 Color Computer` provided 365 games
[i] EmulationStation: System `ColecoVision` provided 140 games
[i] EmulationStation: System `Daphne` provided 14 games
[i] EmulationStation: System `Dragon 32` provided 491 games
[i] EmulationStation: System `Dreamcast` provided 279 games
[i] EmulationStation: System `Electron` provided 0 games
[i] EmulationStation: System `Famicom` provided 386 games
[i] EmulationStation: System `Final Burn Alpha` provided 0 games
[i] EmulationStation: System `Famicom Disk System` provided 91 games
[i] EmulationStation: System `Game and Watch` provided 0 games
[i] EmulationStation: System `Sega Gamegear` provided 332 games
[i] EmulationStation: System `Game Boy` provided 861 games
[i] EmulationStation: System `Game Boy Advance` provided 1066 games
[i] EmulationStation: System `Game Boy Advance Hacks` provided 0 games
[i] EmulationStation: System `Game Boy Color` provided 535 games
[i] EmulationStation: System `Game Boy Hacks` provided 18 games
[i] EmulationStation: System `Sega Genesis Hacks` provided 226 games
[i] EmulationStation: System `Sega Gamegear Hacks` provided 4 games
[i] EmulationStation: System `Intellivision` provided 137 games
[i] EmulationStation: System `Multiple Arcade Machine Emulator` provided 0 games
[i] EmulationStation: System `Multiple Arcade Machine Emulator` provided 0 games
[i] EmulationStation: System `Multiple Arcade Machine Emulator` provided 0 games
[i] EmulationStation: System `Sega Mark III` provided 58 games
[i] EmulationStation: System `Sega Master System` provided 343 games
[i] EmulationStation: System `Sega Mega Drive` provided 901 games
[i] EmulationStation: System `Sega Mega Drive Japan` provided 194 games
[i] EmulationStation: System `MSX` provided 439 games
[i] EmulationStation: System `MSX2` provided 83 games
[i] EmulationStation: System `Nintendo 64` provided 303 games
[i] EmulationStation: System `naomi` provided 181 games
[i] EmulationStation: System `Nintendo DS` provided 252 games
[i] EmulationStation: System `Neo Geo CD` provided 0 games
[i] EmulationStation: System `Neo Geo` provided 142 games
[i] EmulationStation: System `Nintendo Entertainment System` provided 864 games
[i] EmulationStation: System `Nintendo Entertainment System Hacks` provided 195 games
[i] EmulationStation: System `Neo Geo Pocket` provided 9 games
[i] EmulationStation: System `Neo Geo Pocket Color` provided 40 games
[i] EmulationStation: System `Oric 1` provided 134 games
[i] EmulationStation: System `PC` provided 0 games
[i] EmulationStation: System `NEC PC-8801` provided 0 games
[i] EmulationStation: System `NEC PC-9801` provided 0 games
[i] EmulationStation: System `PC Engine-CD` provided 0 games
[i] EmulationStation: System `PC Engine` provided 285 games
[i] EmulationStation: System `TurboGrafx 16 CD (PC Engine CD)` provided 0 games
[i] EmulationStation: System `PC-FX` provided 28 games
[i] EmulationStation: System `Commodore Plus 4` provided 0 games
[i] EmulationStation: System `Pokemon Mini` provided 0 games
[i] EmulationStation: System `Ports` provided 0 games
[i] EmulationStation: System `Power Menu` provided 2 games
[i] EmulationStation: System `PlayStation Portable` provided 126 games
[i] EmulationStation: System `PlayStation Portable Minis` provided 294 games
[i] EmulationStation: System `PlayStation` provided 466 games
[i] EmulationStation: System `ResidualVM` provided 0 games
[i] EmulationStation: System `RetroPie` provided 82 games
[i] EmulationStation: System `Satellaview` provided 41 games
[i] EmulationStation: System `Sega Saturn` provided 90 games
[i] EmulationStation: System `Sega SC-3000` provided 0 games
[i] EmulationStation: System `ScummVM` provided 181 games
[i] EmulationStation: System `Sega 32X` provided 33 games
[i] EmulationStation: System `Mega CD` provided 171 games
[i] EmulationStation: System `Super Famicom` provided 457 games
[i] EmulationStation: System `Sega SG-1000` provided 68 games
[i] EmulationStation: System `Super Game Boy` provided 0 games
[i] EmulationStation: System `Super Nintendo` provided 785 games
[i] EmulationStation: System `Super Nintendo Hacks` provided 151 games
[i] EmulationStation: System `Super Nintendo MSU1` provided 29 games
[i] EmulationStation: System `Sufami Turbo` provided 15 games
[i] EmulationStation: System `SuperGrafx` provided 5 games
[i] EmulationStation: System `Supervision` provided 0 games
[i] EmulationStation: System `Solarus Engine` provided 0 games
[i] EmulationStation: System `TurboGrafx CD` provided 47 games
[i] EmulationStation: System `TurboGrafx-16` provided 94 games
[i] EmulationStation: System `TI99` provided 0 games
[i] EmulationStation: System `trs-80` provided 0 games
[i] EmulationStation: System `Vectrex` provided 23 games
[i] EmulationStation: System `Commodore VIC-20` provided 236 games
[i] EmulationStation: System `Videopac` provided 131 games
[i] EmulationStation: System `Virtual Boy` provided 23 games
[i] EmulationStation: System `Wonderswan` provided 109 games
[i] EmulationStation: System `Wonderswan Color` provided 88 games
[i] EmulationStation: System `Sharp X1` provided 429 games
[i] EmulationStation: System `X68000` provided 235 games
[i] EmulationStation: System `Z-machine` provided 39 games
[i] EmulationStation: System `ZX81` provided 0 games
[i] EmulationStation: System `ZX Spectrum` provided 372 games
[i] EmulationStation: System `Nintendo Technos` provided 0 games
[i] EmulationStation: System `Apple Macintosh` provided 0 games
[i] EmulationStation: System `Kodi` provided 0 games
[i] EmulationStation: System `jukebox` provided 0 games
[i] EmulationStation: System `Pixel Desktop` provided 0 games
[i] EmulationStation: System `chromium` provided 0 games
[i] EmulationStation: System `Steam` provided 0 games
[i] EmulationStation: Found `/home/pi/RetroPie/roms/3do/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `openbor`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/amiga/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/amigacd32/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/amstradcpc/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/apple2/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/arcade/gamelist.xml`
[i] EmulationStation: Found `/home/pi/.emulationstation//gamelists/arcadia/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/astrocde/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/atari2600/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/atari5200/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/atari7800/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/atari800/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/atarijaguar/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/atarilynx/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/atarist/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `atarixegs`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/atomiswave/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `bbcmicro`
[w] EmulationStation: No gamelist file found for system `c128`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/c64/gamelist.xml`
[i] EmulationStation: Found `/home/pi/.emulationstation//gamelists/cdi/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/channelf/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/coco/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/coleco/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/daphne/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/dragon32/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/dreamcast/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `electron`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/famicom/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `fba`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/fds/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/gameandwatch/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/gamegear/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/gb/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/gba/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `gbah`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/gbc/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/gbh/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/genh/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/ggh/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/intellivision/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `mame-advmame`
[w] EmulationStation: No gamelist file found for system `mame-libretro`
[w] EmulationStation: No gamelist file found for system `mame-mame4all`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/markiii/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/mastersystem/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/megadrive/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/megadrive-japan/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/msx/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/msx2/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/n64/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/naomi/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/nds/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/neogeocd/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/neogeo/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/nes/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/nesh/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/ngp/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/ngpc/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/oric/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `pc`
[w] EmulationStation: No gamelist file found for system `pc88`
[w] EmulationStation: No gamelist file found for system `pc98`
[w] EmulationStation: No gamelist file found for system `pce-cd`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/pcengine/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/pcenginecd/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/pcfx/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `plus4`
[w] EmulationStation: No gamelist file found for system `pokemini`
[i] EmulationStation: Found `/home/pi/.emulationstation//gamelists/ports/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/power/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/psp/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/pspminis/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/psx/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `residualvm`
[i] EmulationStation: Found `/home/pi/RetroPie/retropiemenu/gamelist.xml`
[w] EmulationStation: The `<game>` node in `/home/pi/RetroPie/retropiemenu/gamelist.xml` at line 45 has no valid `<path>` entry
[i] EmulationStation: Found `/home/pi/RetroPie/roms/satellaview/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/saturn/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `sc-3000`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/scummvm/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/sega32x/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/segacd/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/sfc/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/sg-1000/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `sgb`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/snes/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/snesh/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/snesmsu1/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/sufami/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/supergrafx/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `supervision`
[w] EmulationStation: No gamelist file found for system `solarus`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/tg-cd/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/tg16/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `ti99`
[w] EmulationStation: No gamelist file found for system `trs-80`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/vectrex/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/vic20/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/videopac/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/virtualboy/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/wonderswan/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/wonderswancolor/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/x1/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/x68000/gamelist.xml`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/zmachine/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `zx81`
[i] EmulationStation: Found `/home/pi/RetroPie/roms/zxspectrum/gamelist.xml`
[w] EmulationStation: No gamelist file found for system `technos`
[w] EmulationStation: No gamelist file found for system `macintosh`
[w] EmulationStation: No gamelist file found for system `Kodi`
[w] EmulationStation: No gamelist file found for system `Jukebox`
[w] EmulationStation: No gamelist file found for system `pixel`
[w] EmulationStation: No gamelist file found for system `Chromium`
[i] EmulationStation: Ignoring the `steam` system in favor of the built-in Steam support
[i] EmulationStation: Finished searching in 10190ms
[i] Skraper Assets: 0 assets found
[i] Skraper Assets: Finished searching in 153ms
[i] Favorites: Finished searching in 0ms
[i] Playtime: Finished searching in 12ms
[w] The collection 'Steam' has no valid games, ignored
[w] The collection 'Pixel Desktop' has no valid games, ignored
[w] The collection 'Nintendo Technos' has no valid games, ignored
[w] The collection 'ZX81' has no valid games, ignored
[w] The collection 'Supervision' has no valid games, ignored
[w] The collection 'Super Game Boy' has no valid games, ignored
[w] The collection 'Game Boy Advance Hacks' has no valid games, ignored
[w] The collection 'OpenBOR' has no valid games, ignored
[w] The collection 'Game and Watch' has no valid games, ignored
[w] The collection 'Ports' has no valid games, ignored
[w] The collection 'Solarus Engine' has no valid games, ignored
[w] The collection 'Arcadia' has no valid games, ignored
[w] The collection 'Electron' has no valid games, ignored
[w] The collection 'ResidualVM' has no valid games, ignored
[w] The collection 'PC Engine-CD' has no valid games, ignored
[w] The collection 'Commodore 128' has no valid games, ignored
[w] The collection 'BBC Micro' has no valid games, ignored
[w] The collection 'Philips CD-i' has no valid games, ignored
[w] The collection 'Kodi' has no valid games, ignored
[w] The collection 'Multiple Arcade Machine Emulator' has no valid games, ignored
[w] The collection 'chromium' has no valid games, ignored
[w] The collection 'trs-80' has no valid games, ignored
[w] The collection 'jukebox' has no valid games, ignored
[w] The collection 'Neo Geo CD' has no valid games, ignored
[w] The collection 'Apple Macintosh' has no valid games, ignored
[w] The collection 'TurboGrafx 16 CD (PC Engine CD)' has no valid games, ignored
[w] The collection 'PC' has no valid games, ignored
[w] The collection 'TI99' has no valid games, ignored
[w] The collection 'NEC PC-8801' has no valid games, ignored
[w] The collection 'Final Burn Alpha' has no valid games, ignored
[w] The collection 'Commodore Plus 4' has no valid games, ignored
[w] The collection 'Pokemon Mini' has no valid games, ignored
[w] The collection 'Sega SC-3000' has no valid games, ignored
[w] The collection 'NEC PC-9801' has no valid games, ignored
[i] Game list post-processing took 2262ms
[i] 24660 games found
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/x68000.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/markiii.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/saturn.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/megadrive-japan.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/sfc.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/sufami.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/x1.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/snesh.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/supergrafx.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/ggh.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/genh.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/snesmsu1.svg
[w] qrc:/themes/pegasus-theme-grid/layer_platform/PlatformCard.qml:71:5: QML Image: Cannot open: qrc:/themes/pegasus-theme-grid/assets/logos/satellaview.svg
[w] qt.gui.icc: fromIccProfile: failed minimal tag size sanity
[w] QPngHandler: Failed to parse ICC profile

`

**Comment by HVR88** [comment]
Switched to another display...

After removing the OMX components (apt remove gstreamer1.0-omx) there's no change. Pegasus hangs immediately when I switch to a platform with a game video.

**Comment by HVR88** [comment]
Starting some new tests and will report back the results.

1. Brand new clean RetroPie install onto new media (so I can parallel test different media/assets/versions)
2. On original install, hide and substitute video assets to check for differences & failure point

**Comment by mmatyas** [comment]
Great! I guess this can be closed then, but feel free to post updates in case you do more testing.

**Comment by HVR88** [comment]
I just came back to close it myself, actually. :)

I'm going to open a new one to try and figure out the monitor out of sync issue - maybe you have some tips on anything I can do to debug that.

**Comment by mmatyas** [comment]
I'm not sure what out of sync means for a screen – does that mean the system tries to set some incorrect mode, for example?

Pegasus uses the default display, and the display's preferred resolution, based on what the device reports to the system (via EDID). If that's not good, you can change that, take a look at the docs here: https://pegasus-frontend.org/docs/user-guide/platform-linux/#gpu-driver-notes
