### ISSUE TITLE
api.memory.set writes null when passed a JsObject

### ISSUE THREAD

**Issue by waldnercharles** [mmatyas/pegasus-frontend#882]
`api.memory.set(key, val)` writes javascript objects as `null`

Example:

```
Component.onCompleted: {
    api.memory.set('helloWorld', ({ test: 'testing!' }));
}
```

The code above does not throw any exceptions or write any warnings to the log, but outputs the json:
```
{"helloWorld":null}
```

**Comment by mmatyas** [comment]
Thanks, should be fixed now in the latest version!
