### ISSUE TITLE
Raspberry Pi (RetroPie) Display out of sync range when starting Pegasus

### ISSUE THREAD

**Issue by HVR88** [mmatyas/pegasus-frontend#890]
### Display: DELL 2007FP  1600x1200 native, 4:3 LCD

RetroPie image (Supreme Ultra base image) with resolution defined as hdmi_group 2 (DMT) and hdmi_mode 32 (1280x960 60Hz) using Raspi-Config

hdmi_drive=1 in or hdmi_drive=2 config.txt both with same results

### What happens
The OS boots to terminal and Emulation Station with display as expected. I can launch all the usual emulators and play games without issue.

_When starting Pegasus however, something changes and the monitor reports out of sync._

This monitor can report the same out of sync error even when the resolution/mode is the same but HDMI audio is present in the signal from the Pi. Setting hdmi_drive=1 in config.txt or using an HDMI audio extractor prevents this and allows everything to work as expected with the Pi. 

### Different results with clean RetroPie image
Testing with a clean RetroPie image doesn't produce this issue - flashed with the Raspberry Pi flasher tool and then manually installed Pegasus from RetroPie Setup utility.

The only differences observed in Pegasus log apart from different number of platforms and media active for testing, are the following errors:

Log ends with during startup:
[w] qt.gui.icc: fromIccProfile: failed minimal tag size sanity
[w] QPngHandler: Failed to parse ICC profile

When moving the controller for the first time, there's also this warning
[w] libpng warning: iCCP: cHRM chunk does not match sRGB

**Comment by mmatyas** [comment]
Reposting from #880, just to be here too:

> I'm not sure what out of sync means for a screen – does that mean the system tries to set some incorrect mode, for example?
>
> Pegasus uses the default display, and the display's preferred resolution, based on what the device reports to the system (via EDID). If that's not good, you can change that, take a look at the docs here: https://pegasus-frontend.org/docs/user-guide/platform-linux/#gpu-driver-notes

**Comment by mmatyas** [comment]
When you mention _Testing with a clean RetroPie_, do you also mean the manual resolution change (by raspi-config) is not applied yet? Can we narrow the issue to this difference?

**Comment by HVR88** [comment]
Yes, out of sync means that the monitor is being sent a resolution/frequency/timing it can't display - or that its firmware thinks it can't display.

And yes, clean means no changes to raspi-config or manually to config.txt.  Raspi config still shows resolution set to "default"

**Comment by HVR88** [comment]
I found the culprit.

In config.txt this caused the problems:

hdmi_ignore_edid=0xa5000080

With that set, the multiple problems on this display were:
1. Resolution "default" in raspi-config produces out of sync on boot - can be fixed by hdmi_drive=1 (don't use audio in DVI modes) and setting a specific resolution in raspi-config
2. Pegasus changes mode when launched and display goes out of sync even if it was configured as above

When removing the offending line, no changes are needed to raspi-config or config.txt for resolution or audio and the display works correctly. Pegasus launches and the mode doesn't change to anything invalid.
