### ISSUE TITLE
CreateWindow() for QEventDispatcherWin32 internal window failed (The current process has used all of its system allowance of handles for Window Manager objects.)

### ISSUE THREAD

**Issue by msheehan79** [mmatyas/pegasus-frontend#891]
Hi, and thanks for reporting errors! You can help us locating the bug even more by providing detailed information in the sections below:

### The issue

When exiting a game, Pegasus normally will resume as expected. Have had a working setup using build alpha14-134-gc0273204 for several months. When I updated to current build alpha15-49-g8665fc41, now when exiting a game Pegasus will sometimes fail to resume. Checking the logfile the error reported is:

2021-09-03T15:53:27 [e] CreateWindow() for QEventDispatcherWin32 internal window failed (The current process has used all of its system allowance of handles for Window Manager objects.)
2021-09-03T15:53:27 [e] Qt: INTERNAL ERROR: failed to install GetMessage hook: 1158, The current process has used all of its system allowance of handles for Window Manager objects.

### System info

Windows 10 x64

### Pegasus version
alpha15-49-g8665fc41

### Pegasus log

Attached.
[lastrun.zip](https://github.com/mmatyas/pegasus-frontend/files/7108246/lastrun.zip)

**Comment by mmatyas** [comment]
Interesting! It's as if Pegasus is trying to do too many things at once, but what exactly is hard to tell. I see you have a lot of games, I wonder if it's related to that or their asset files. Could you try increasing and decreasing the number of games, and see if that affects how often this error comes up?

**Comment by msheehan79** [comment]
Sure, I will give it a shot. It probably is related, as I usually test new builds on a replicated setup I use for development that only have a small subset of games on it and did not see the issue there. I only noticed it on my main gaming setup which does have a fairly large number of games. I'll try and narrow down things a bit and report back, along with some metadata examples showing which assets I include.

**Comment by msheehan79** [comment]
After doing some additional testing today to try and narrow down how to replicate the issue, what I have noticed is the issue does not trigger unless you leave the emulator running for at least 5-10 minutes before closing/returning back to Pegasus. If I just open/close games fairly quickly without spending more than a few minutes, it doesn't seem to fail.

With regards to size of the system, I am not so sure that is the issue. I reduced the number of games significantly, down to just one system of games and could still replicate the issue consistently. The main key I had to do was to launch a game and let it run for at least 5-10 minutes before closing. I also switched themes to Pegasus Grid just to rule out any weirdness in the theme itself as a factor, but could still trigger the issue.

If it helps, I am including the metadata file I used with the last test, along with the latest logfile.

Let me know if you need any more info or have any other areas you want me to test this end that might help isolate what could be going on here.

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/7110756/lastrun.log)
[games.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/7110754/games.metadata.txt)
[system-nds.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/7110755/system-nds.metadata.txt)

**Comment by msheehan79** [comment]
Just adding some additional troubleshooting info, if it helps. 

- I reset all Pegasus settings back to default
- I simplified my metadata file down to just 3 games in one collection and use the default Grid theme
- I normally use Xpadder with many games for hotkeys, I removed Xpadder from the launch script and also removed the xpadder close script I normally use in the Pegasus scripts folder for game-end

I am still able to consistently replicate the issue by launching the game, waiting about 5 minutes then closing.

I then downloaded the last Alpha 15 stable release, and the issue does not occur there, so appears to have cropped up somewhere in between. I have a couple of interim builds from late May/June timeframe so will test those next and see if I can repro the issue there or not to see if it helps narrow down what change has caused this.

(Including most recent metadata, settings & logfiles. I turned off all the game providers to keep the log tidy but the issue occurred with it on and off.

[system-nds.metadata.txt](https://github.com/mmatyas/pegasus-frontend/files/7150981/system-nds.metadata.txt)
[settings.txt](https://github.com/mmatyas/pegasus-frontend/files/7150983/settings.txt)
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/7150984/lastrun.log)

**Comment by mmatyas** [comment]
Thanks for testing! Just to make sure then, version ` g3392060` (Alpha 15) works, but `g35fa7254` (5/31) does not, right? There was an SDL (gamepad support module) update there, I'll see if I can do something with it.

**Comment by msheehan79** [comment]
@mmatyas Tried the newest build from today, same issue unfortunately.

As a sanity check I then retested Alpha15 stable again (this is the one from the website and the releases page). Works fine 3/3 times.

**Comment by mmatyas** [comment]
Hm that's too bad, I fear it might be a problem in SDL then, which would be hard to find or fix. Can you try whether this happens on other computers too? I wonder if others have run into this problem before.

**Comment by msheehan79** [comment]
Indeed - I did reproduce it on two different Win 10 PCs before reporting, as I always want to assume its something I'm doing wrong before bugging the dev! 

They are different hardware although both Nvidia GPUs, different old ones though. I will see if I can try it on some other PCs too. 

Given how often it occurs for me, and since its technically been failing since a build in May, I am a bit surprised no one else has reported it, so I keep thinking there has to be something unusual with my setup that makes it unique. But I have tried to simplify it down to the bare minimum metadata files etc. I will continue to test on my end and if I find anything that seems relevant I'll post back.

**Comment by mmatyas** [comment]
Hm I've tried to reproduce this, similarly on Windows 10, with RetroArch and MelonDS core running for 10+ minutes, but so far I haven't run into issues.

**Comment by msheehan79** [comment]
Thanks for trying to reproduce it. Did you happen to have a controller connected when you tried?

I hadn't had much time to try again until today, but I noticed when I tried to test again I couldn't get it to fail either. But then I realized I had unplugged my controller and was only using the keyboard to test this time around.  As soon as I reconnected the controller I was able to get it to crash again. I then tried a few other controllers and it seems some of my controllers trigger a crash, while others did not. Not sure if this useful info, but figured Id add it.

These 3 controllers would cause the crash
- https://www.amazon.com/Controller-Gamepad-Computer-Windows-Android/dp/B07S8LGZLG/ref=sr_1_5?dchild=1&keywords=zd+xinput&qid=1631943759&sr=8-5 - crash in both Xinput and Dinput mode

- https://www.amazon.com/Retroflag-Classic-Gaming-Controller-Switch/dp/B07JPQY66K/ref=sr_1_6?dchild=1&keywords=retroflag&qid=1631943821&sr=8-6 - crash in Xinput mode only; no crash when in Dinput mode
 
- Official Xbox 360 Wireless controller using a receiver like this one - https://www.amazon.com/Microsoft-Xbox-Wireless-Receiver-Windows/dp/B000HZFCT2/ref=sr_1_49?dchild=1&keywords=xbox+360+wireless+adapter&qid=1631943897&sr=8-49

- Could not get it to crash with this Dinput controller: https://www.amazon.com/Buffalo-iBuffalo-Classic-Gamepad-BSGP815GY/dp/B06XWD8QQJ/ref=sr_1_2?dchild=1&keywords=buffalo+controller&qid=1631946926&sr=8-2

**Comment by mmatyas** [comment]
I wasn't sure, so I tested again (with an F310 in Xinput mode), but couldn't reproduce it. I also tried to set the input and gamepad input drivers in RetroArch to SDL2, in case that causes the issue, but everything still worked fine for me.

**Comment by HVR88** [comment]
I will give this a try on my Windows 10 system. I haven't been using Pegasus for much testing as it had extremely long startup times which have just been addressed. 

I have official XBOX One and Series controllers (XINPUT) plus two custom controllers using Brook boards that can switch between XINPUT and DINPUT and lastly another custom controller that is exclusively DINPUT for buttons.

**Comment by msheehan79** [comment]
Thanks both for checking. I have been trying various combinations of Pegasus settings just to see if there is any other common factors besides the controllers but I have been able to get it to fail with Pegasus pretty much at default settings with current builds, so it keeps pointing back to the XInput controllers and likely some other system factor yet to be isolated. 

Both the machines I have seen it occur on are Windows 10 x64, one is my main day-to-day PC with lots of other software running but the other is pretty much a dedicated gaming system so there is minimal other applications running in the background in that system.

What I have not specifically noticed is a different emulator besides various RetroArch cores cause the crash to see if that is a factor or not. I also haven't had a chance to try it on my wife's Windows 8 laptop to see if I can reproduce there or not but if I do get a chance to try, I will post back here either way.

**Comment by HunkDeath** [comment]
Hi, i have the same problem. It crash everytime on every systems (RetroArch, PC Game...) when i quit a game after 5 minutes. I used Windows 10 with a Xbox One X official controller. I send my lastlog if may help you.

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/7448882/lastrun.log)

**Comment by msheehan79** [comment]
I'll try and retest this week and post back here if the updated SDL changes this behavior for my setup.

**Comment by crtJoe** [comment]
A quick feedback: 
I have the same issue with the recent versions (including the latest alpha15-94-geb44f4a1)  I reverted back to Alpha 15 stable 3392060 (5/4) and so far so good.

Long version: 
I'm using an 8itbido Arcade Stick and a DS4 controller. Both recognized as a generic 360 pad in Retroarch/Windows 10. With recent versions of Pegasus, it wouldn't resume after ending about 5 or more minutes of playing sessions with Retroarch. (same error in the log: "Qt: INTERNAL ERROR: failed to install GetMessage hook: 1158...."  It happens consistently and I can easily reproduce the issue.  Tried to change the input driver from dinput to sdl2, and controller driver from xinput to sdl2 too in Retroarch, and that did not help. Perhaps we can get a test build with the old SDL module (the one included in Alpha 15 stable) and see if that SDL update was actually the culprit or if it's something else? I don't know about coding so not sure if it's possible to test this way...

**Comment by msheehan79** [comment]
Also can confirm the latest build still has the same crash for me as well, unfortunately.

**Comment by mmatyas** [comment]
Ok, here is a special build, the latest version with the SDL version (2.0.10) used in the Alpha 15:
[pegasus-fe_alpha15-97-ga6cf1fc5_win-mingw-static_WITH-SDL-2010.zip](https://github.com/mmatyas/pegasus-frontend/files/7770917/pegasus-fe_alpha15-97-ga6cf1fc5_win-mingw-static_WITH-SDL-2010.zip)
(Though I'm not sure what we'll do if this actually turns out to be the issue)

**Comment by msheehan79** [comment]
@mmatyas was able to test this build out this evening, and so far no crashes so it does seem pretty clear the SDL upgrade is tied to the issue.

Am attaching a log file of the current standard build with crash and the test build without. I made no changes to my test other than swapping the Pegasus file.

I do notice a difference in how Pegasus reports the connected controller between builds, for what it is worth. It was the same controller in both tests but in the working build it is reported as just an XInput Controller, whereas with the later build it shows as Xbox 360 Controller.

2021-12-23T20:19:25 [i] SDL version 2.0.10
2021-12-23T20:19:25 [i] Gamepad: Connected device 0x0 (XInput Controller)

2021-12-23T20:10:32 [i] SDL version 2.0.18
2021-12-23T20:10:33 [i] Gamepad: Connected device

[lastrun - Normal Build.log](https://github.com/mmatyas/pegasus-frontend/files/7772141/lastrun.-.Normal.Build.log)
[lastrun - Test Build.log](https://github.com/mmatyas/pegasus-frontend/files/7772142/lastrun.-.Test.Build.log)
 0x0 (Xbox 360 Controller)

**Comment by crtJoe** [comment]
After a quick test, here's my initial conclusion:
The updated SDL (newer than 2.0.10) seems to have some compatibility issues with older Retroarch version. In my case, it's 1.9.6. I updated it to the latest 1.9.14, the issue is now gone.

Some observations that might be useful:

This special build + Old Retroarch (1.9.6) >> no crash
Regular build (updated SDL) + New Retroarch (1.9.14) >> no crash

With this new information in mind, I decided to make sure if I can still reproduce the issue, and the answer is yes with the following combination:  
Regular build (updated SDL) + Old Retroarch (1.9.6) >> crash (Pegasus won't resume)

My new Retroarch setup is a fresh install (I haven't migrate most of my old settings yet) so it's also likely that the issue has something to do with some specific Retroarch settings that I haven't touched yet.  But at the moment, 1.9.14 seems to fix it for me.

**Comment by mmatyas** [comment]
@msheehan79 can you also confirm that RetroArch 1.9.14 fixes the issue? I wonder if this was something related to their input handling.
@HunkDeath could you try if the crash still happens with the version above?

**Comment by msheehan79** [comment]
@mmatyas Unfortunately I did not have the same experience here - when I tested 1.9.14 stable it still crashes. For my test the only swap was the RetroArch program however, so I left all my existing RA configuration files intact.

I also tested a standalone emulator next (PCSX2) to see if indeed there was something unusual with RA as a factor, but I get the same crash with PCSX2 as well, so its not limited to just one emulator in my instance.

**Comment by crtJoe** [comment]
@msheehan79
@mmatyas

I spoke too soon. Today I got the same crash multiple times with  Retroarch 1.9.14 + regular Pegasus build (gfff1a5b2 with SDL 2.0.16)

Switched back to the special build (SDL 2.0.10) and again, it worked perfectly. Perhaps it was just a fluke yesterday : (

**Comment by msheehan79** [comment]
FWIW, I tested the latest build after the SDL 2.0.20 update and the issue remains, unfortunately.

**Comment by PlayingKarrde** [comment]
Can confirm, I'm getting this error also with the latest release and stable and so far 100% reproducible. Seems to happen when the game is played for a minute or more but if I exit the game fairly quickly it doesn't happen.

```
2022-05-04T13:54:01 [e] create: CreateWindowEx failed (The current process has used all of its system allowance of handles for Window Manager objects.)
2022-05-04T13:54:01 [w] Failed to create platform window for QQuickWindowQmlImpl_QML_138(0x182d56b8) with flags QFlags<Qt::WindowType>(Window)
```

**Comment by mmatyas** [comment]
I've made some changes to the gamepad handling, could you try the latest version (`alpha16-35-gcf2e2d1c`)?

**Comment by msheehan79** [comment]
@mmatyas Ran a quick test today and so far this change looks good, I haven't been able to reproduce the crash anymore. Thanks! 

I will update my main system and spend a little more time testing to make sure this is fully resolved and if so will close this issue.

**Comment by msheehan79** [comment]
Have been using the new version for a bit and have yet to encounter a crash, so appears this is now fixed!  Nice to be able to use a current version again.
