### ISSUE TITLE
Playnite: ScreenshotsVisualizer Support

### ISSUE THREAD

**Issue by A983Hub** [mmatyas/pegasus-frontend#906]
So, there is this Playnite Extension called **"ScreenshotsVisualizer"**, in which you can set a specific folder with images to show Screenshots using a Menu. Now, here is something wrong that i found out: **Basically, Pegasus only loads the background image instead of the screenshots. So, why not add the Background Image AND the screenshots? That would make a great idea!**

**Comment by HVR88** [comment]
I'm sure these will be relevant:

What version of Pegasus? What theme? And lastly, which view?

I don't know what relevance the Playnite extension has as Pegasus most surely doesn't use any such extensions or use any Playnite code. It sounds like you're asking for Pegasus to import the screenshot images you're using with this extension as its own screenshots - this is fair, but as they're not a standard part of Playnite, it's probably the reason they don't show up at this time.
