### ISSUE TITLE
Favorites from external PC games not added

### ISSUE THREAD

**Issue by Beats24-7** [mmatyas/pegasus-frontend#910]
Hi there,
I have the same issue as someone had in this post: https://github.com/mmatyas/pegasus-frontend/issues/814#issuecomment-952938862
It's already closed though so I opened a new one. I start PC games in Pegasus (latest stable version) from a different hard drive. Everything is working fine but adding them to my favorites within Pegasus doesn't really work. They are added correctly but if I restart Pegasus they are gone. It works fine if I add the path to the exe file in the favorites.txt myself, it would be great if it would work within Pegasus as well though.

What's weird is that Pegasus adds the correct path to the favorites.txt but it's still not showing up upon restart. I have to manually remove the line and save the txt, restart Pegasus, add the line manually again, save and restart Pegasus. So only if I manually add the path it's working somehow.

Any idea how to fix this? Thanks in adance!

Pegasus version
alpha15-85-gfff1a5b2 (2021-10-04)

Windows
Windows 10 Pro 19043.1288

**Comment by mmatyas** [comment]
There have been some Windows related fixes in the latest version, could you check if these helped with the favorites issue?

**Comment by mmatyas** [comment]
There have been reports in #814 that it's working now, closing in favor of that.
