### ISSUE TITLE
Bug: Pegasus (flatpak) unable to detect Lutris games

### ISSUE THREAD

**Issue by Learning5Life** [mmatyas/pegasus-frontend#913]
### The issue

Upon a fresh install of Pegasus, no Lutris games were detected, only games in my Steam library. These Lutris games included standalone games and games from GOG, but installed in my own games directory and not the usual ~/GOG Games directory.

### System info

Pop!_OS 21.04

### Pegasus version

fff1a5b (flatpak)

### Pegasus log

Attached bug report:
[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/7589722/lastrun.log)

Love this bug report template by the way. It makes it so much easier for me to provide good information.

**Comment by mmatyas** [comment]
Hi, yes, at the moment you can't add additional GOG directories from the settings menu, but you can do it by manually editing the settings file.

In the case of Flatpak, that should be at `/home/yourname/.var/app/org.pegasus_frontend.Pegasus/config/pegasus-frontend/settings.txt`. Open that in some plain text editor and the following to the bottom:

```
providers.gog.directories:
  /home/yourname/Game1/
  /home/yourname/Game2/
  /home/yourname/GameN/
```

Edit the paths to your liking, just make sure each directory line starts with at least one space. Pegasus will look for `start.sh` files in the directories you add this way.

**Comment by mmatyas** [comment]
I guess this is solved, but feel free to report if there are still some issues.

**Comment by entropicdrifter** [comment]
I'm seeing this same issue in Mint 20.3
Lutris games are not detected by the Flatpak version of Pegasus at all

**Comment by mmatyas** [comment]
Ok; @entropicdrifter could you also attach a log file of the Flatpak version?

**Comment by entropicdrifter** [comment]
Sure:
```Gtk-Message: 20:55:45.871: Failed to load module "xapp-gtk3-module"
Qt: Session management error: None of the authentication protocols specified are supported
[i] Pegasus 9bd055a (2022-03-28)
[i] Running on KDE Flatpak runtime (x86_64, xcb)
[i] Qt version 5.15.3
[i] Program settings loaded (`/home/nolan/.var/app/org.pegasus_frontend.Pegasus/config/pegasus-frontend/settings.txt`)
[i] Found locale `ar`
[i] Found locale `bs`
[i] Found locale `de`
[i] Found locale `en-GB`
[i] Found locale `en`
[i] Found locale `es`
[i] Found locale `fr`
[i] Found locale `hu`
[i] Found locale `ja`
[i] Found locale `ko`
[i] Found locale `lt`
[i] Found locale `nl`
[i] Found locale `pt-BR`
[i] Found locale `ru`
[i] Found locale `zh-TW`
[i] Found locale `zh`
[i] Locale set to `en`
[i] Found theme `Pegasus Grid` at `:/themes/pegasus-theme-grid/`
[i] SDL version 2.0.16
[w] Requested theme `:/themes/pegasus-theme-grid` not found, falling back to default
[i] Theme set to `Pegasus Grid` (`:/themes/pegasus-theme-grid/`)
[i] Gamepad: Connected device 0x0 (Xbox 360 Controller)
[i] Gamepad: Connected device 0x1 (Xbox 360 Controller)
[i] Gamepad: Connected device 0x2 (Steam Virtual Gamepad)
[i] Gamepad: Connected device 0x3 (Steam Virtual Gamepad)
[i] Metafiles: No metadata files found
[i] Metafiles: Finished searching in 0ms
[i] Media: Finished searching in 0ms
[i] Logiqx: Finished searching in 0ms
[i] Lutris: No installation found
[i] Lutris: Finished searching in 0ms
[i] Skraper Assets: 0 assets found
[i] Skraper Assets: Finished searching in 0ms
[i] Favorites: Finished searching in 0ms
[i] Playtime: Finished searching in 0ms
[i] Game list post-processing took 0ms
[i] 0 games found
[i] Closing Pegasus, goodbye!```

**Comment by entropicdrifter** [comment]
So far I've tried launching it with a few different Flatpak filesystem permissions set, but none of them seem to work.
My Lutris pga.db file is located at `~/.local/share/lutris`, which is one of the folders the current code should be checking [per this function](https://github.com/mmatyas/pegasus-frontend/blob/33920608ac0d3f1a707ecec14527386e167e06b1/src/backend/providers/lutris/LutrisProvider.cpp#L33), so I really have no idea why it's not being scanned. Even adding the --filesystem=host permission to the command line args does nothing.

**Comment by entropicdrifter** [comment]
Thanks for looking into this, I really appreciate it. I've never published
a flatpak myself but I definitely know how annoying sandboxes can be.

**Comment by mmatyas** [comment]
Ok, this should be fixed in the latest Flatpak release. Thanks for the report!

**Comment by senz** [comment]
In case anyone is having trouble when Lutris itself is in a flatpak (EmuDeck installs it like that), workaround:

```
ln -s ~/.var/app/net.lutris.Lutris/data/lutris ~/.local/share/lutris

cat > ~/.local/bin/lutris <<'EOF'
#!/bin/sh
exec /usr/bin/flatpak run net.lutris.Lutris "$@"
EOF
chmod +x ~/.local/bin/lutris
```

Steam -> Pegasus -> Launch Options: `env PATH="$HOME/.local/bin:$PATH" %command%`
