### ISSUE TITLE
Bash script as collection command not recognized

### ISSUE THREAD

**Issue by katawful** [mmatyas/pegasus-frontend#914]
### The issue

I am trying to use a bash script to pass emulator configs for an entire collection, however the bash script is not found by Pegasus. I placed the bash script in the working directory I set with the metadata:
```
collection: Wii U
shortcut: wii-u
directory: /run/media/ROMs/Wii-U/
workdir: /run/media/ROMs/Wii-U/
extensions: rpx
launch: /run/media/ROMs/Wii-U/game_launch.sh {file.path}
```

### System info

Arch Linux

### Pegasus version

alpha15-85-gfff1a5b2

### Pegasus log

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/7589945/lastrun.log)

**Comment by katawful** [comment]
The script is executable and runs at the location when in a terminal

**Comment by valsou** [comment]
In the logs it says that the path of your WiiU folder is `/run/media/HDD/Roms/WiiU`, and Pegasus finds your metadata.txt inside.

Isn't it just a typo ? (missing `HDD` intermediate folder)

**Comment by katawful** [comment]
It was a typo
