### ISSUE TITLE
Pass system/game launch information to script on launch [Android]

### ISSUE THREAD

**Issue by klandrith** [mmatyas/pegasus-frontend#919]
I am setting up an Odroid N2 running LineageOS/Android 11 inside of one of their OGST N64-ish cases designed for the XU4. It comes with a little 2.4" TFT display on the front that is supposed to be setup to launch video snaps/box art if you use their gaming distro, or run recalbox or batocera. I haven't gotten to the point of setting up pegasus yet as I'm still setting up the system and my collection. But, I would like to be able to have the ability to run scripts depending on what system, or specific game, is launched from pegasus. Is there a simple way for pegasus to pass the android system calls to a script that I could write that could then parse the system and game launched for the purposes of displaying video snaps, etc? I know this is an edge case...

**Comment by mmatyas** [comment]
Hi, yes, the launch command in Pegasus can be anything you like. You can set it to a script that accepts the platform and the game path as parameters, and you can call the actual emulator/app for there as well. This is similar to what RetroPie does, for example, to show platform specific launch screens.

**Comment by klandrith** [comment]
Awesome, I was hoping it would be easy like that. I have pegasus installed, but haven't fiddled with it at all yet. Thanks for the reply, and the app!
