### ISSUE TITLE
Add Support for Playstation Controllers with xboxdrv

### ISSUE THREAD

**Issue by dudleydes** [mmatyas/pegasus-frontend#92]
Playstation controllers are not natively supported by Qt but can work with xboxdrv to emulate a Xbox 360 controller.

The command suggested in the [Qt Gamepad documentation](https://doc.qt.io/qt-5/qtgamepad-index.html#getting-started) is

```
sudo xboxdrv --detach-kernel-driver --mimic-xpad -s
```

A wired PS3 controller works in the Pegasus frontend with this command but it's not available in emulators. Running `cat /proc/bus/input/devices`,  the virtual Xbox 360 pad appears as js0 with no assignment for the PS3 controller.

I can add a flag `--evdev /dev/input/by-id/usb-Sony_PLAYSTATION_R_3_Controller-event-joystick` but the PS3 controller does not work in Pegasus. It works fine once a rom is launched. This is because the PS3 controller is assigned `js0` and the virtual Xbox 360 pad `js1`.

I do have a solution working using [Linux Joystick Mapper](https://sourceforge.net/projects/linuxjoymap/).

**Comment by mmatyas** [comment]
There have been a large set of changes to the gamepad handling recently, and I think PS3 controllers should also work now out of the box. If you still have one around, could you test it with the latest release?

**Comment by mmatyas** [comment]
In theory, the current gamepad engine (SDL 2.0.14) supports even PS5 gamepads, so I think this can be closed now.
