### ISSUE TITLE
Unable to Load Model 2 Games (Windows 10)

### ISSUE THREAD

**Issue by crtJoe** [mmatyas/pegasus-frontend#927]
Is the Sega Model 2 Emulator supported? When starting a model 2 game from Pegasus, the emulator opens but no game is loaded. I'm aware that for this specific emulator, I need to set up a hotkey with AutoHotkey to quit/close the emulator, but I couldn't even get it to load the game. The game loads fine if I start it from the emulator's game list.

The directory structure of Pegasus/Sega Model 2 Emulator/Roms is like this:

D:\Emulator\Pegasus\pegasus-fe.exe
D:\Emulator\Pegasus\roms\Model2\daytona.zip
D:\Emulator\SegaM2\emulator_multicpu.exe

A snippet of the metadata file is like this:

collection: Sega Model 2
shortname: model2
extensions: zip, bin
launch: D:\Emulator\SegaM2\emulator_multicpu.exe {file.path}

game: Daytona USA
file: ./daytona.zip
developer: SEGA
publisher: SEGA
genre: Race 3rd Pers. view-Race, Driving
description: Daytona USA is an excellent checkpoint-style racing game.

Any suggestions?

**Comment by mmatyas** [comment]
Hi, every emulator is supported that is able to open files from the command line, but the actual command depends on the emulator itself. Usually you can find this in its documentation, if the emulator is able to do this. If in doubt, you could also try to contact the developers.

**Comment by crtJoe** [comment]
Thanks for the reply. I found a tip from the interface of Launchbox which might be useful. A checkbox says:
 "Use file name only without file extension or folder path (Sega Model 2 Emulator, etc. Compatibility)"

It seems that they have to check this option to launch a Model 2 game. Is there any other variable other than {file.path} that might suit this requirement?

**Comment by mmatyas** [comment]
In that case, I think `launch: D:\Emulator\SegaM2\emulator_multicpu.exe "{file.dir}\{file.basename}"` is what you're looking for. If that doesn't help, you can find all variables here: https://pegasus-frontend.org/docs/user-guide/meta-files/#launch-command-parameters

**Comment by crtJoe** [comment]
Thanks a lot! I confirm the following works with this emulator:

launch: D:\Emulator\SegaM2\emulator_multicpu.exe {file.basename}

Just replacing {file.path} with {file.basename} will work. (without quotes and {file.dir} ). Thanks again!

**Comment by mmatyas** [comment]
You're welcome!
