### ISSUE TITLE
Favorites & Recent/Most Played Not Saving

### ISSUE THREAD

**Issue by crono3** [mmatyas/pegasus-frontend#929]
I’m using the game-OS theme under Windows 11 and none of my data seems to be getting saved. If I mark anything as a favorite, it’s gone next time I launch Pegasus. Same with the list of recently played or lost played games. I’m stuck with a list of games that I think were some of the first ones I tested. Everything works fine while running the application, but as soon as I quit and restart everything is reset.

**Comment by mmatyas** [comment]
Hi! Could you attach the log file Pegasus makes, after you mark a game as favorite and quit Pegasus? (See [this page](https://github.com/mmatyas/pegasus-frontend/blob/master/.github/ISSUE_TEMPLATE/bug.md) for more details.)

**Comment by HVR88** [comment]
This is a duplicate issue of https://github.com/mmatyas/pegasus-frontend/issues/814

I thought it was fixed, but looks like it was reported as happening again last October.

**Comment by mmatyas** [comment]
Ah, it seems I've forgot to reopen the issue back then. @crono3 could you post a comment and your log files in that thread too? I'm closing this in favor of #814 then (thanks @HVR88!)
