### ISSUE TITLE
Manual parsing/hiding of Android apps?

### ISSUE THREAD

**Issue by RevolverUnit** [mmatyas/pegasus-frontend#934]
Sorry if this is already a feature, but I couldn't find anything about it in the documentation.

Currently, as far as I can tell enabling Android apps as a data source is all-or-nothing. I have a ton of non-game apps that I would love to hide from the launcher. 

Also, it would be great to be able to add metadata for apps and games that aren't on the Play Store.

Is this already possible, and if not, would it be a feasible feature?

**Comment by mmatyas** [comment]
Hi, the built-in Android support will show all apps, but if you don't mind some manual work, by creating your own metadata file you can replace this entirely.

In a metadata file, create a collection called "Android", without a default launch command. Then, for each app you'd like to see, create a game entry, with the `file` set to `android:<your-package-id>`, and the launch command set to `launch: am start -n <package-activity> -a <package-launch-action>`. Unfortunately, these 3 parameters tend to be different between games, but if you can find them out (eg. with some app explorer tool) you can make a custom metadata file from them.

**Comment by RevolverUnit** [comment]
This is exactly what I was looking for. Thank you!

**Comment by traffisco** [comment]
> Sorry if this is already a feature, but I couldn't find anything about it in the documentation.
> 
> Currently, as far as I can tell enabling Android apps as a data source is all-or-nothing. I have a ton of non-game apps that I would love to hide from the launcher.
> 
> Also, it would be great to be able to add metadata for apps and games that aren't on the Play Store.
> 
> Is this already possible, and if not, would it be a feasible feature?

You can also do it on the theme level. Just filter out apps you want to hide in collection 0
