### ISSUE TITLE
Android file permissions needed to be manually set before opening

### ISSUE THREAD

**Issue by JeffersonBledsoe** [mmatyas/pegasus-frontend#935]
### The issue

I just tried to load pegasus on my Shield TV (2017) and it just gives me a white screen. I had to manually enable the files permission before opening Pegasus. Once open, Pegasus then asks me for the file permission. After I have allowed it within pegasus everything works okay.

### System info

NVIDIA SHIELD TV (Android 11)

### Pegasus version

Both stable release (alpha15-85-gfff1a5b2 (2021-12-13)) and latest version: alpha15-101-g8425a4f6 (2022-01-21)

### Pegasus log

No last-run log can be found before the permissions are allowed

**Comment by mmatyas** [comment]
Interesting, does this happen with a fresh install of Pegasus, or after upgrading the Shield?

**Comment by JeffersonBledsoe** [comment]
I've just upgraded to android 11, not used Pegasus on the system before. If I disable the permission, clear the app days, uninstall and reinstall, the issue re-occurs.

**Comment by mmatyas** [comment]
Do you have some way to access the device logs (eg. by `logcat`)? I wonder if there's anything related there.

**Comment by JeffersonBledsoe** [comment]
I'll take a look through the logs when I can.

I just came across an article regarding Scoped Storage breaking numerous apps on the Shield after the Android 11 upgrade 
(https://www.androidpolice.com/android-11-nvidia-shield-breaking-apps-plex-servers/amp/). Could it be related?

**Comment by mmatyas** [comment]
Hm scoped storage shouldn't stop an app from drawing its own interface, at least in theory, but anything is possible.

**Comment by JeffersonBledsoe** [comment]
Not at a computer to check the code right now, but is there any logging being done on startup that could be failing because we don't have permission, preventing the app from reaching the UI rendering?

**Comment by mmatyas** [comment]
As far as I know, nothing blocking, it would probably crash in that case.

**Comment by mmatyas** [comment]
A [new update came out for the Shield](https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/485389/shield-experience-upgrade-901-released-21522/) that _Fixes storage permission issues on media players, file browsers, and emulator apps_. Does it affect the issue here?

**Comment by JeffersonBledsoe** [comment]
@mmatyas  Just updated to 9.0.1 on the shield. Reset the permission, uninstalled & re-installed Pegasus. It pops up asking for permission now, all seems good!

**Comment by mmatyas** [comment]
Great!
