### ISSUE TITLE
[android] Replace "Quit" with "Reload" in main menu

### ISSUE THREAD

**Issue by sargant** [mmatyas/pegasus-frontend#936]
At the moment, the main menu has "Settings", "Help", and "Quit" options. I find myself having to "Quit" and re-open Pegasus in order to re-scan the filesystem after I've made some changes to the content. 

However, if Pegasus is set as the launcher app on Android, when you quit the home app repeatedly, the OS doesn't like it and starts bothering you to change your launcher app.

It would be great if a "Reload" kind of option was in that same main menu, in order to do a soft reset & rescan without fully closing the app. Additionally, "Quit" isn't a conventional thing you find in Android apps, so this probably isn't necessary.

**Comment by mmatyas** [comment]
Ok, there's now a reload option in the settings menu of the latest version!
The quit button sounds like a separate topic; I have seen apps with self closing behavior, and might be useful for some people. Feel free to open an issue for it you'd like to.
