### ISSUE TITLE
Change metadata for android apps

### ISSUE THREAD

**Issue by JohnGhostly** [mmatyas/pegasus-frontend#939]
There seems to be no way to change the metadata for android apps without adding new files to the collection, leading to duplicates. A lot of the android app Icons are done in inconsistent styles to the ability to change them would be very nice.

**Comment by mmatyas** [comment]
Custom Android entries weren't too well documented before, but there's now a section about it here: https://pegasus-frontend.org/docs/user-guide/faq/#adding-android-games-manually. You can then set custom assets and metadata for the apps, [like with regular games](https://pegasus-frontend.org/docs/user-guide/meta-assets/#game-assets-in-the-metadata-file).
