### ISSUE TITLE
Pegasus crash on start

### ISSUE THREAD

**Issue by IvanMagana** [mmatyas/pegasus-frontend#948]
### The issue

I tried stable and nightly pegasus both now. When I boot up it loads to library and I can see games but then it crashes a second later

### System info
Lenovo yoga 7 laptop
Windows 11 home, 10.0.22000 build 22000
X64
11th gen Intel core i7-11657G7 @2.8ghz 2803 mhz 4cores 8logic cores 

### Pegasus version
(I tried both)
Stable alpha15-85-gfff1a5b2
Latest alpha15-105-g3a2425ca

### Pegasus log

You can find a log file with detailed information about the launch of Pegasus under the following locations:

- Windows: `C:\Users\[username]\AppData\Local\pegasus-frontend\lastrun.log`
- Linux: `~/.config/pegasus-frontend/lastrun.log`
- macOS: `~/Library/Preferences/pegasus-frontend/lastrun.log`
- Android: `<storage>/pegasus-frontend/lastrun.log`
- portable mode: `<directory of the program>/config/lastrun.log`

If possible, please attach the file to this bug report.

**Comment by mmatyas** [comment]
Hi, this sounds like an issue of [missing video codecs](https://pegasus-frontend.org/docs/user-guide/platform-windows/#multimedia-support). Could you attach `C:\Users\[username]\AppData\Local\pegasus-frontend\lastrun.log`, if you have one?

**Comment by IvanMagana** [comment]
[lastrun - Copy.log](https://github.com/mmatyas/pegasus-frontend/files/8126273/lastrun.-.Copy.log)

**Comment by mmatyas** [comment]
Yeah, the last message before the crash is `DirectShowPlayerService::doRender: Unresolved error code 0x80040218` – this shows a video codec error. Take a look at the link above for more info about this.

**Comment by mmatyas** [comment]
(Confirmed working on Discord)
