### ISSUE TITLE
Removing

### ISSUE THREAD

**Issue by FieryMewtwo** [mmatyas/pegasus-frontend#951]
Sorry to open a blank issue; couldn't find a template to really go with this. How do I remove Pegasus (specifically the aur version)? (Want to install with flatpak)

**Comment by mmatyas** [comment]
Hi, I'm not familiar with Arch, but I 'd assume there's an uninstall command you can use. Something like `pacman -R packagename`?

**Comment by FieryMewtwo** [comment]
I got it to work by going in and manually deleting the files. Thanks anyway!
