### ISSUE TITLE
Can't launch game directly on Linux

### ISSUE THREAD

**Issue by liviecollete** [mmatyas/pegasus-frontend#972]
Hi!
I'm trying to run native games directly via {file.path} in the metadata file, but it always gives me the error "Could not launch `/path/to/file.extension`. Either the program is missing, or you don't have the permission to run it." When I run the game from the file manager it works fine.
I'm on Linux Mint 20.3 Xfce Edition.
Am I doing anything wrong here? Would appreciate any pointers, as I really like the interface and flow of Pegasus. :)

**Comment by mmatyas** [comment]
Hi! Most likely it's as the message says: either the file is not located at a place accessible by Pegasus (eg. there's a typo or some kind of sandbox, like Flatpak, is involved), or the file is not executable (and thus cannot be launched).

If you believe none of these hold, please attach the log file `~/.config/pegasus-frontend/lastrun.log` and I'll try to reproduce the issue.

**Comment by mmatyas** [comment]
I'll assume this got solved then, but feel free to report if there are still issues.
