### ISSUE TITLE
Windows ARM64 support

### ISSUE THREAD

**Issue by holaimscott** [mmatyas/pegasus-frontend#981]
Howdy, I've been a huge fan of Pegasus. I wanted to ask if this launcher has native Windows ARM64 support? If not, it would be great if your team could consider also making the windows version compatible to run natively on ARM64 or give us the option to build/have an ARM64 version available.

With the rise of ARM devices, and current support for other ARM platforms like Android, this would be great and put this frontend ahead of the curve!

**Comment by mmatyas** [comment]
Hi, our main dependency is Qt, which does have experimental support for Windows on ARM. If you can build it to your device, Pegasus should also just work with it.
