### ISSUE TITLE
Double inputs with Steam open in Linux

### ISSUE THREAD

**Issue by entropicdrifter** [mmatyas/pegasus-frontend#988]
### The issue

Describe here what you've tried to do, what you've expected to see and what actually happens. If necessary, describe step-by-step the way to reproduce the problem.

When I use a controller for input with Steam open in the background, the controller is detected as both its native input and as the Steam-Input wrapped version. Is there a way to disable one of them other than closing Steam?

### System info

I'm running Pegasus Flatpak on Linux Mint 20.3

### Pegasus version

Latest Flatpak build 2022-04-04

**Comment by mmatyas** [comment]
Hi, if I understand correctly, other than the device, Steam too sends input events to the system, right? I'd assume it's something to disable on Steam's side then, or perhaps a script could take away temporarily its permission for this.

**Comment by mmatyas** [comment]
I've made some changes to the gamepad handling, could you try the latest version (`alpha16-35-gcf2e2d1c`)?
