### ISSUE TITLE
Crashes on Steam Tile

### ISSUE THREAD

**Issue by Mobeeuz** [mmatyas/pegasus-frontend#991]
Selecting the Steam tile with cause a crash after a few moments. Moving the selection box or not. I suspect it's how you are enumerating the Steam games (through the manifest files I surmise). Maybe a game I haven't played in a while has old data that causes the crash?

[PegasusCrashDumps.zip](https://github.com/mmatyas/pegasus-frontend/files/8548391/PegasusCrashDumps.zip)

**Comment by mmatyas** [comment]
Hi, this usually happens when the necessary video codecs are missing from the system. I assume you're on Windows, but please see the [issue template](https://github.com/mmatyas/pegasus-frontend/blob/master/.github/ISSUE_TEMPLATE/bug.md) and tell us the details it mentions.

**Comment by Mobeeuz** [comment]
My bad, thought the crashdumps would be the key.

[lastrun.zip](https://github.com/mmatyas/pegasus-frontend/files/8548419/lastrun.zip)

**Comment by mmatyas** [comment]
Thanks! The log confirms the codec issue:

```
2022-04-23T12:56:13 [w] DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()
2022-04-23T12:56:14 [w] DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()
2022-04-23T12:56:15 [w] DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()
2022-04-23T12:56:15 [w] DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()
2022-04-23T12:56:16 [w] DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()
2022-04-23T12:56:17 [w] DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()
2022-04-23T12:56:17 [w] DirectShowPlayerService::doSetUrlSource: Unresolved error code 0x80004004 ()
2022-04-23T12:56:17 [w] DirectShowPlayerService::doRender: Unresolved error code 0x80040218 ()
```

Pegasus uses the built-in video support of Windows cassd DirectShow. Unfortunately it likes to crash when the codec required by the vido file is missing. (See [the docs](https://pegasus-frontend.org/docs/user-guide/platform-windows/#multimedia-support) for more details.)

**Comment by Mobeeuz** [comment]
Does this only apply to Steam? GOG worked just fine. Can we have an option not to have videos, or a localized solution such as ffmpeg for playback? Codec packs cause system and software issues for me elsewhere.

**Comment by mmatyas** [comment]
Different sources tend to use different video codecs; in this case Steam just happens to use one that is not on your system. As for whether videos are shown, that depends on the theme. There are themes that don't show videos, take a look at https://pegasus-frontend.org/tools/themes/

> or a localized solution such as ffmpeg for playback? Codec packs cause system and software issues for me elsewhere.

That would be nice, and in fact there's #347 for that, but someone will have to write the code for it.

**Comment by mmatyas** [comment]
The issue was confirmed, and the alternative is tracked in https://github.com/mmatyas/pegasus-frontend/issues/347, so I think this can be closed.
