### ISSUE TITLE
Nintendo Switch Pro Controller doesn't works when in an emulated game (Tested with RetroArch, Dolphin, Citra and Yuzu, the emulators most people use)

### ISSUE THREAD

**Issue by SamuelTheTechnoKid** [mmatyas/pegasus-frontend#994]
### The issue

So, the Switch Pro Controller fully works in the interface, in the games (when not opened by Pegasus), but when the games are opened via the front-end, the input doesn't work. Happens when using RetroArch and Dolphin, not in Citra (Standalone, no RetroArch core) or Yuzu. Tried BetterJoyForCemu, but not that great with Pegasus. Tried x360ce (Assigned for Pegasus only), and yet NOTHING! The latest version, and STILL NOTHING FOR GOD'S SAKE!

### System info

Windows 11 (Insider Build 22598.200)

### Pegasus versions tested

Alpha 16 (March 28, 2022)
Latest Release (April 26th, 2022)

**Comment by mmatyas** [comment]
I've made some changes to the gamepad handling, could you try the latest version (`alpha16-35-gcf2e2d1c`)?

**Comment by mmatyas** [comment]
I'll assume it worked out.
